using System.Globalization;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using TTSmartEcom.Application.Abstractions.Products;
using TTSmartEcom.Domain.Products;

namespace TTSmartEcom.Infrastructure.SqlServer.Products;

#pragma warning disable CA1725

/// <summary>SQL implementation for the product/variant mutation subset; review/media follow separately.</summary>
public sealed class SqlProductMutationRepository(ISqlConnectionFactory factory, SqlProductCatalogRepository reads) : IProductCatalogWriteRepository, IProductMediaRepository
{
    public async Task<ProductRecord?> FindEquivalentCodeAsync(string code,string? exclude,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT PublicId FROM dbo.Products WHERE UPPER(REPLACE(REPLACE(Code,N' ',N''),N'-',N''))=@code AND IsDeleted=0 AND (@exclude IS NULL OR PublicId<>@exclude);",c);q.Parameters.AddWithValue("@code",code);q.Parameters.AddWithValue("@exclude",(object?)exclude??DBNull.Value);object? value=await q.ExecuteScalarAsync(ct);return value is string id?await reads.FindByIdAsync(id,true,ct):null;}
    public async Task<ProductMutationResult> CreateAsync(ProductMutation p,CancellationToken ct){string id=SqlPublicIds.New();await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlTransaction tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{await using(SqlCommand q=new("INSERT dbo.Products(ProductId,PublicId,Name,NameUnsigned,Code,BrandName,TypeName,CategoryName,CategoryValue,Description,VatRaw,Display,Adjusted,DetailsJson,DocumentsJson,Version) VALUES(NEWID(),@id,@name,@unsigned,@code,@brand,@type,@section,@value,@description,@vat,@display,@adjusted,@details,@docs,0);",c,tx)){ProductParams(q,id,p);await q.ExecuteNonQueryAsync(ct);}foreach((ProductVariantMutation v,int i) in (p.Variants??[]).Select((x,i)=>(x,i)))await AddVariantAsync(c,tx,id,i,v,ct);await tx.CommitAsync(ct);return new(ProductMutationStatus.Success,await reads.FindByIdAsync(id,true,ct));}catch(SqlException e)when(e.Number is 2601 or 2627){await tx.RollbackAsync(ct);return new(ProductMutationStatus.Conflict,Message:"Mã sản phẩm đã tồn tại");}catch{await tx.RollbackAsync(ct);throw;}}
    public async Task<ProductMutationResult> UpdateAsync(string id,ProductMutation p,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE dbo.Products SET Name=COALESCE(@name,Name),Code=COALESCE(@code,Code),BrandName=COALESCE(@brand,BrandName),TypeName=COALESCE(@type,TypeName),CategoryName=COALESCE(@section,CategoryName),CategoryValue=COALESCE(@value,CategoryValue),Description=COALESCE(@description,Description),VatRaw=COALESCE(@vat,VatRaw),Display=COALESCE(@display,Display),Adjusted=COALESCE(@adjusted,Adjusted),Version=Version+1,SourceUpdatedAtUtc=SYSUTCDATETIME() WHERE PublicId=@id AND IsDeleted=0;",c);ProductParams(q,id,p);return await q.ExecuteNonQueryAsync(ct)==0?new(ProductMutationStatus.NotFound,Message:"Product not found"):new(ProductMutationStatus.Success,await reads.FindByIdAsync(id,true,ct));}
    public async Task<ProductMutationResult> DeleteAsync(string id,CancellationToken ct){ProductRecord? before=await reads.FindByIdAsync(id,true,ct);if(before is null)return new(ProductMutationStatus.NotFound,Message:"Product not found");await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE dbo.Products SET IsDeleted=1,Version=Version+1 WHERE PublicId=@id;",c);q.Parameters.AddWithValue("@id",id);await q.ExecuteNonQueryAsync(ct);return new(ProductMutationStatus.Success,before);}
    public async Task<ProductMutationResult> ToggleDisplayAsync(string id,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE dbo.Products SET Display=CASE WHEN Display=1 THEN 0 ELSE 1 END,Version=Version+1 WHERE PublicId=@id AND IsDeleted=0;",c);q.Parameters.AddWithValue("@id",id);return await q.ExecuteNonQueryAsync(ct)==0?new(ProductMutationStatus.NotFound):new(ProductMutationStatus.Success,await reads.FindByIdAsync(id,true,ct));}
    public async Task<ProductMutationResult> DeleteManyAsync(IReadOnlyCollection<string> ids,CancellationToken ct){if(ids.Count==0)return new(ProductMutationStatus.Success,AffectedCount:0);await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new($"UPDATE dbo.Products SET IsDeleted=1,Version=Version+1 WHERE PublicId IN ({string.Join(',',ids.Select((_,i)=>"@p"+i))});",c);for(int i=0;i<ids.Count;i++)q.Parameters.AddWithValue("@p"+i,ids.ElementAt(i));long count=await q.ExecuteNonQueryAsync(ct);return new(ProductMutationStatus.Success,AffectedCount:count);}
    public async Task<ProductMutationResult> AddVariantAsync(string id,ProductVariantMutation v,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlTransaction tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{await using SqlCommand sequence=new("SELECT COALESCE(MAX(v.SortOrder),-1)+1 FROM dbo.ProductVariants v JOIN dbo.Products p ON p.ProductId=v.ProductId WHERE p.PublicId=@id;",c,tx);sequence.Parameters.AddWithValue("@id",id);int next=Convert.ToInt32(await sequence.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);await AddVariantAsync(c,tx,id,next,v,ct);await tx.CommitAsync(ct);return new(ProductMutationStatus.Success,await reads.FindByIdAsync(id,true,ct));}catch{await tx.RollbackAsync(ct);throw;}}
    public async Task<ProductMutationResult> UpdateVariantAsync(string id,int index,ProductVariantMutation v,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE v SET PriceRaw=COALESCE(@price,PriceRaw),ImportPriceRaw=COALESCE(@import,ImportPriceRaw),QuantityForSale=COALESCE(@sale,QuantityForSale),QuantityInStorage=COALESCE(@storage,QuantityInStorage),DetailsJson=COALESCE(@details,DetailsJson),Version=Version+1 FROM dbo.ProductVariants v JOIN dbo.Products p ON p.ProductId=v.ProductId WHERE p.PublicId=@id AND v.SortOrder=@index;",c);VariantParams(q,id,index,v);return await q.ExecuteNonQueryAsync(ct)==0?new(ProductMutationStatus.NotFound):new(ProductMutationStatus.Success,await reads.FindByIdAsync(id,true,ct));}
    public async Task<ProductMutationResult> DeleteVariantAsync(string id,int index,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("DELETE v FROM dbo.ProductVariants v JOIN dbo.Products p ON p.ProductId=v.ProductId WHERE p.PublicId=@id AND v.SortOrder=@index AND v.QuantityForSale=0 AND v.QuantityInStorage=0;",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@index",index);return await q.ExecuteNonQueryAsync(ct)==0?new(ProductMutationStatus.Invalid,Message:"Không thể xóa phiên bản") :new(ProductMutationStatus.Success,await reads.FindByIdAsync(id,true,ct));}
    public Task<ProductMutationResult> UpdateVariantEarnAsync(string id,int index,double earn,CancellationToken ct)=>UpdateVariantAsync(id,index,new ProductVariantMutation(null,null,null,earn,null,null,null,null,null,null,null,null),ct);
    public Task<ProductMutationResult> UpdateVariantImportPriceAsync(string id,int index,string price,CancellationToken ct)=>UpdateVariantAsync(id,index,new ProductVariantMutation(null,null,price,null,null,null,null,null,null,null,null,null),ct);
    public async Task<ProductMutationResult> AdjustPurchaseCountAsync(string id,long delta,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE dbo.Products SET PurchaseCount=PurchaseCount+@delta,Version=Version+1 WHERE PublicId=@id AND IsDeleted=0 AND (@delta>=0 OR PurchaseCount>=-@delta);",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@delta",delta);return await q.ExecuteNonQueryAsync(ct)==0?new(ProductMutationStatus.Invalid,Message:"Số lượng đã mua không đủ để giảm"):new(ProductMutationStatus.Success,await reads.FindByIdAsync(id,true,ct));}
    public async Task<long> BackfillDisplayAsync(CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE dbo.Products SET Display=1 WHERE Display IS NULL;",c);return await q.ExecuteNonQueryAsync(ct);}
    public Task<IReadOnlyList<ProductRecord>> FindByCodesAsync(IReadOnlyCollection<string> codes,bool include,CancellationToken ct)=>reads.FindByIdsAsync(codes,include,ct);
    public async Task<ProductTypeMutationResult> CreateTypeAsync(string name,string icon,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);string id=SqlPublicIds.New();try{await using SqlCommand q=new("INSERT dbo.ProductTypes(ProductTypeId,PublicId,Name,Icon,Version) VALUES(NEWID(),@id,@name,@icon,0);",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@name",name);q.Parameters.AddWithValue("@icon",icon);await q.ExecuteNonQueryAsync(ct);return new(ProductMutationStatus.Success,new ProductTypeRecord(id,name,icon,null,null));}catch(SqlException e)when(e.Number is 2601 or 2627){return new(ProductMutationStatus.Conflict,Message:"Loại sản phẩm đã tồn tại");}}
    public async Task<ProductTypeMutationResult> UpdateTypeAsync(string id,string name,string icon,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE dbo.ProductTypes SET Name=@name,Icon=@icon,Version=Version+1 WHERE PublicId=@id;",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@name",name);q.Parameters.AddWithValue("@icon",icon);return await q.ExecuteNonQueryAsync(ct)==0?new(ProductMutationStatus.NotFound):new(ProductMutationStatus.Success,new ProductTypeRecord(id,name,icon,null,null));}
    public async Task<ProductTypeMutationResult> DeleteTypeAsync(string id,bool unused,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("DELETE FROM dbo.ProductTypes OUTPUT deleted.PublicId,deleted.Name,deleted.Icon WHERE PublicId=@id;",c);q.Parameters.AddWithValue("@id",id);await using SqlDataReader r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?new(ProductMutationStatus.Success,new ProductTypeRecord(r.GetString(0),r.IsDBNull(1)?null:r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),null,null)):new(ProductMutationStatus.NotFound);}
    public async Task<IReadOnlyList<ProductReview>?> GetReviewsAsync(string id,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT PublicId,ReviewerName,Content,Rating FROM dbo.ProductReviews WHERE ProductId=(SELECT ProductId FROM dbo.Products WHERE PublicId=@id) ORDER BY SortOrder;",c);q.Parameters.AddWithValue("@id",id);List<ProductReview> x=[];await using SqlDataReader r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))x.Add(new(r.GetString(0),r.IsDBNull(1)?null:r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),r.IsDBNull(3)?null:(double)r.GetDecimal(3),null));return x;}
    public async Task<ProductReviewMutationResult> CreateReviewAsync(string id,string email,string? comment,double rating,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);string review=SqlPublicIds.New();await using SqlCommand q=new("INSERT dbo.ProductReviews(ProductReviewId,PublicId,ProductId,SortOrder,Rating,Content,ReviewerName,Version) SELECT NEWID(),@review,ProductId,(SELECT COUNT(*) FROM dbo.ProductReviews WHERE ProductId=p.ProductId),@rating,@content,@email,0 FROM dbo.Products p WHERE PublicId=@id AND IsDeleted=0;",c);q.Parameters.AddWithValue("@review",review);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@rating",rating);q.Parameters.AddWithValue("@content",(object?)comment??DBNull.Value);q.Parameters.AddWithValue("@email",email);return await q.ExecuteNonQueryAsync(ct)==0?new(ProductMutationStatus.NotFound):new(ProductMutationStatus.Success,new ProductReview(review,email,comment,rating,DateTimeOffset.UtcNow));}
    public async Task<ProductReviewMutationResult> UpdateReviewAsync(string id,string review,string? comment,double? rating,string actor,bool moderator,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE r SET Content=COALESCE(@content,Content),Rating=COALESCE(@rating,Rating),Version=Version+1 OUTPUT inserted.PublicId,inserted.ReviewerName,inserted.Content,inserted.Rating FROM dbo.ProductReviews r JOIN dbo.Products p ON p.ProductId=r.ProductId WHERE p.PublicId=@id AND r.PublicId=@review AND (@moderator=1 OR r.ReviewerName=@actor);",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@review",review);q.Parameters.AddWithValue("@content",(object?)comment??DBNull.Value);q.Parameters.AddWithValue("@rating",(object?)rating??DBNull.Value);q.Parameters.AddWithValue("@actor",actor);q.Parameters.AddWithValue("@moderator",moderator);await using SqlDataReader r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?new(ProductMutationStatus.Success,new ProductReview(r.GetString(0),r.IsDBNull(1)?null:r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),r.IsDBNull(3)?null:(double)r.GetDecimal(3),null)):new(ProductMutationStatus.NotFound);}
    public async Task<ProductReviewMutationResult> DeleteReviewAsync(string id,string review,string actor,bool moderator,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("DELETE r FROM dbo.ProductReviews r JOIN dbo.Products p ON p.ProductId=r.ProductId WHERE p.PublicId=@id AND r.PublicId=@review AND (@moderator=1 OR r.ReviewerName=@actor);",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@review",review);q.Parameters.AddWithValue("@actor",actor);q.Parameters.AddWithValue("@moderator",moderator);return await q.ExecuteNonQueryAsync(ct)==0?new(ProductMutationStatus.NotFound):new(ProductMutationStatus.Success);}
    public async Task<ProductStockMutationResult> AdjustStockAsync(string id,int index,ProductStockMutation mutation,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE v SET QuantityForSale=COALESCE(QuantityForSale,0)+@qty,QuantityInStorage=COALESCE(QuantityInStorage,0)+@qty WHERE ProductId=(SELECT ProductId FROM dbo.Products WHERE PublicId=@id) AND SortOrder=@index AND (@qty>=0 OR COALESCE(QuantityForSale,0)>=-@qty AND COALESCE(QuantityInStorage,0)>=-@qty);",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@index",index);q.Parameters.AddWithValue("@qty",mutation.Quantity);return await q.ExecuteNonQueryAsync(ct)==0?new(ProductMutationStatus.Invalid,Message:"Insufficient stock"):new(ProductMutationStatus.Success,await reads.FindByIdAsync(id,true,ct));}
    public async Task<ProductVariantImageReference?> GetVariantImageReferenceAsync(string id,int index,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT DetailsJson FROM dbo.ProductVariants WHERE ProductId=(SELECT ProductId FROM dbo.Products WHERE PublicId=@id) AND SortOrder=@index;",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@index",index);object? value=await q.ExecuteScalarAsync(ct);if(value is null)return await reads.FindByIdAsync(id,true,ct) is null?null:new ProductVariantImageReference(false,null);using JsonDocument d=JsonDocument.Parse(Convert.ToString(value,CultureInfo.InvariantCulture)??"{}");JsonElement root=d.RootElement;string? url=root.TryGetProperty("imgUrl",out var image)&&image.ValueKind==JsonValueKind.String?image.GetString():root.TryGetProperty("imageUrl",out var alternate)&&alternate.ValueKind==JsonValueKind.String?alternate.GetString():null;return new ProductVariantImageReference(true,url);}
    public async Task<bool> IsProductImageReferencedElsewhereAsync(string id,int index,string filename,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT COUNT(*) FROM dbo.ProductVariants v JOIN dbo.Products p ON p.ProductId=v.ProductId WHERE (p.PublicId<>@id OR v.SortOrder<>@index) AND v.DetailsJson LIKE @file;",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@index",index);q.Parameters.AddWithValue("@file","%"+filename+"%");return Convert.ToInt64(await q.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture)>0;}
    public async Task<ProductRecord?> ClearVariantImageAsync(string id,int index,string expected,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE v SET DetailsJson=JSON_MODIFY(JSON_MODIFY(DetailsJson,'$.imgUrl',NULL),'$.imageUrl',NULL),Version=Version+1 FROM dbo.ProductVariants v JOIN dbo.Products p ON p.ProductId=v.ProductId WHERE p.PublicId=@id AND v.SortOrder=@index AND v.DetailsJson LIKE @expected;",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@index",index);q.Parameters.AddWithValue("@expected","%"+expected+"%");return await q.ExecuteNonQueryAsync(ct)==1?await reads.FindByIdAsync(id,true,ct):null;}
    public async Task<bool> IsInvoiceImageReferencedAsync(string filename,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT CASE WHEN EXISTS(SELECT 1 FROM dbo.SalesOrders WHERE ImagesJson LIKE @file) OR EXISTS(SELECT 1 FROM dbo.InventoryOrders WHERE ImagesJson LIKE @file) THEN 1 ELSE 0 END;",c);q.Parameters.AddWithValue("@file","%"+filename+"%");return Convert.ToInt32(await q.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture)==1;}
    private static async Task AddVariantAsync(SqlConnection c,SqlTransaction tx,string id,int index,ProductVariantMutation v,CancellationToken ct){await using SqlCommand q=new("INSERT dbo.ProductVariants(ProductVariantId,PublicId,ProductId,SortOrder,PriceRaw,ImportPriceRaw,QuantityForSale,QuantityInStorage,DetailsJson,Version) VALUES(NEWID(),@variant,(SELECT ProductId FROM dbo.Products WHERE PublicId=@id),@index,@price,@import,@sale,@storage,@details,0);",c,tx);VariantParams(q,id,index,v);q.Parameters.AddWithValue("@variant",SqlPublicIds.New());await q.ExecuteNonQueryAsync(ct);}private static void ProductParams(SqlCommand q,string id,ProductMutation p){q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@name",(object?)p.Name??DBNull.Value);q.Parameters.AddWithValue("@unsigned",(object?)p.Name?.ToLowerInvariant()??DBNull.Value);q.Parameters.AddWithValue("@code",(object?)p.Code??DBNull.Value);q.Parameters.AddWithValue("@brand",(object?)p.Brand??DBNull.Value);q.Parameters.AddWithValue("@type",(object?)p.Type??DBNull.Value);q.Parameters.AddWithValue("@section",(object?)p.Section??DBNull.Value);q.Parameters.AddWithValue("@value",(object?)p.Value??DBNull.Value);q.Parameters.AddWithValue("@description",(object?)p.Description??DBNull.Value);q.Parameters.AddWithValue("@vat",(object?)p.Vat??DBNull.Value);q.Parameters.AddWithValue("@display",(object?)p.Display??DBNull.Value);q.Parameters.AddWithValue("@adjusted",(object?)p.Adjusted??DBNull.Value);q.Parameters.AddWithValue("@details",JsonSerializer.Serialize(p));q.Parameters.AddWithValue("@docs",JsonSerializer.Serialize(p.Documents??[]));}private static void VariantParams(SqlCommand q,string id,int index,ProductVariantMutation v){q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@index",index);q.Parameters.AddWithValue("@price",(object?)v.Price??DBNull.Value);q.Parameters.AddWithValue("@import",(object?)v.ImportPrice??DBNull.Value);q.Parameters.AddWithValue("@sale",(object?)v.QuantityForSale??DBNull.Value);q.Parameters.AddWithValue("@storage",(object?)v.QuantityInStorage??DBNull.Value);q.Parameters.AddWithValue("@details",JsonSerializer.Serialize(v));}
}
