using System.Text.Json;
using Microsoft.Data.SqlClient;
using TTSmartEcom.Application.Integrations;
using TTSmartEcom.Domain.Integrations;

namespace TTSmartEcom.Infrastructure.SqlServer.Integrations;

#pragma warning disable CA1725, CS8602, CS8604

public sealed class SqlProviderSettingsRepository(ISqlConnectionFactory factory,ISqlLocalSecretStore secrets) : IProviderSettingsRepository
{
    private static readonly JsonSerializerOptions Json=new(){PropertyNameCaseInsensitive=true,PropertyNamingPolicy=JsonNamingPolicy.CamelCase};
    public async Task<TelegramSettings> GetTelegramAsync(CancellationToken ct){Config c=await GetAsync("Telegram",ct);List<TelegramRecipient> list=[];foreach(Recipient x in c.Recipients){string? chat=await secrets.GetAsync(x.ChatSecretReference,ct);list.Add(new TelegramRecipient(x.Id,x.Label??string.Empty,chat??string.Empty,x.Type??"personal",x.Enabled,x.NotifyTypes??["new_order"]));}return new TelegramSettings(c.Enabled??false,list);}
    public async Task<TelegramSettings> SetTelegramEnabledAsync(bool enabled,CancellationToken ct){Config c=await GetAsync("Telegram",ct);await SaveAsync("Telegram",c with{Enabled=enabled},null,ct);return await GetTelegramAsync(ct);}
    public async Task<TelegramRecipient> AddTelegramRecipientAsync(TelegramRecipientInput input,CancellationToken ct){Config c=await GetAsync("Telegram",ct);Recipient r=new(SqlPublicIds.New(),input.Label??string.Empty,await secrets.PutAsync(input.ChatId??string.Empty,ct),input.Type??"personal",input.Enabled??true,input.NotifyTypes??["new_order"]);await SaveAsync("Telegram",c with{Recipients=[..c.Recipients,r]},null,ct);return new TelegramRecipient(r.Id,r.Label, input.ChatId??string.Empty,r.Type,r.Enabled,r.NotifyTypes);}
    public async Task<TelegramRecipient?> UpdateTelegramRecipientAsync(string id,TelegramRecipientInput input,CancellationToken ct){Config c=await GetAsync("Telegram",ct);int i=c.Recipients.ToList().FindIndex(x=>x.Id==id);if(i<0)return null;Recipient current=c.Recipients[i];Recipient updated=current with{Label=input.Label??current.Label,Type=input.Type??current.Type,Enabled=input.Enabled??current.Enabled,NotifyTypes=input.NotifyTypes??current.NotifyTypes,ChatSecretReference=input.ChatId is null?current.ChatSecretReference:await secrets.PutAsync(input.ChatId,ct)};List<Recipient> list=c.Recipients.ToList();list[i]=updated;await SaveAsync("Telegram",c with{Recipients=list},null,ct);return new TelegramRecipient(updated.Id,updated.Label,input.ChatId??await secrets.GetAsync(updated.ChatSecretReference,ct)??string.Empty,updated.Type,updated.Enabled,updated.NotifyTypes);}
    public async Task<bool> DeleteTelegramRecipientAsync(string id,CancellationToken ct){Config c=await GetAsync("Telegram",ct);Recipient[] values=c.Recipients.Where(x=>x.Id!=id).ToArray();if(values.Length==c.Recipients.Count)return false;await SaveAsync("Telegram",c with{Recipients=values},null,ct);return true;}
    public async Task<ZaloSettings> GetZaloAsync(CancellationToken ct){Config c=await GetAsync("Zalo",ct);return new ZaloSettings(c.AppId??string.Empty,c.OaId??string.Empty,c.RecipientUserId??string.Empty,!string.IsNullOrWhiteSpace(c.AccessTokenReference)&&c.ExpiresAt> DateTimeOffset.UtcNow,c.ExpiresAt,!string.IsNullOrWhiteSpace(c.SecretKeyReference));}
    public async Task<ZaloSettings> UpdateZaloAsync(ZaloSettingsInput input,CancellationToken ct){Config c=await GetAsync("Zalo",ct);string? key=input.SecretKey is null?c.SecretKeyReference:await secrets.PutAsync(input.SecretKey,ct);await SaveAsync("Zalo",c with{AppId=input.AppId??c.AppId,OaId=input.OaId??c.OaId,RecipientUserId=input.RecipientUserId??c.RecipientUserId,SecretKeyReference=key},key,ct);return await GetZaloAsync(ct);}
    public async Task<string?> GetZaloSecretKeyAsync(CancellationToken ct)=>await secrets.GetAsync((await GetAsync("Zalo",ct)).SecretKeyReference,ct);
    public async Task SaveZaloOAuthTokensAsync(string accessToken,string? refreshToken,DateTimeOffset expiresAt,string? oaId,CancellationToken ct){Config c=await GetAsync("Zalo",ct);await SaveAsync("Zalo",c with{AccessTokenReference=await secrets.PutAsync(accessToken,ct),RefreshTokenReference=refreshToken is null?null:await secrets.PutAsync(refreshToken,ct),ExpiresAt=expiresAt,OaId=oaId??c.OaId},c.SecretKeyReference,ct);}
    internal async Task<Config> GetAsync(string type,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT ConfigurationJson,SecretReference FROM dbo.Integrations WHERE IntegrationType=@type;",c);q.Parameters.AddWithValue("@type",type);await using SqlDataReader r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return new Config(Recipients:[]);Config result=JsonSerializer.Deserialize<Config>(r.GetString(0),Json)??new Config(Recipients:[]);return result with{Recipients=result.Recipients??[],SecretKeyReference=result.SecretKeyReference??(r.IsDBNull(1)?null:r.GetString(1))};}
    internal async Task SaveAsync(string type,Config config,string? primarySecret,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("MERGE dbo.Integrations WITH(HOLDLOCK) AS t USING(SELECT @type AS IntegrationType) s ON t.IntegrationType=s.IntegrationType WHEN MATCHED THEN UPDATE SET ConfigurationJson=@json,SecretReference=@secret,Version=t.Version+1 WHEN NOT MATCHED THEN INSERT(IntegrationId,PublicId,IntegrationType,ConfigurationJson,SecretReference,Version) VALUES(NEWID(),@id,@type,@json,@secret,0);",c);q.Parameters.AddWithValue("@id",SqlPublicIds.New());q.Parameters.AddWithValue("@type",type);q.Parameters.AddWithValue("@json",JsonSerializer.Serialize(config,Json));q.Parameters.AddWithValue("@secret",(object?)primarySecret??DBNull.Value);await q.ExecuteNonQueryAsync(ct);}
    internal sealed record Config(bool? Enabled=null,IReadOnlyList<Recipient>? Recipients=null,string? AppId=null,string? OaId=null,string? RecipientUserId=null,string? SecretKeyReference=null,string? AccessTokenReference=null,string? RefreshTokenReference=null,DateTimeOffset? ExpiresAt=null);
    internal sealed record Recipient(string Id,string Label,string ChatSecretReference,string Type,bool Enabled,IReadOnlyList<string> NotifyTypes);
}
