SET NOCOUNT ON; SET XACT_ABORT ON; SET ANSI_NULLS ON; SET QUOTED_IDENTIFIER ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT ON; SET CONCAT_NULL_YIELDS_NULL ON; SET NUMERIC_ROUNDABORT OFF;
GO
USE [TTSmart];
GO
IF DB_NAME()<>N'TTSmart' THROW 51120,N'Script phải chạy trên [TTSmart].',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=2) BEGIN PRINT N'Migration 002 đã được áp dụng; không có thay đổi.'; RETURN; END;
IF NOT EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=1) THROW 51121,N'Chưa áp dụng migration 001.',1;
BEGIN TRANSACTION;
CREATE TABLE dbo.Brands (BrandId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, Name nvarchar(200) NOT NULL, NormalizedName nvarchar(200) NOT NULL, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT CK_Brands_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_Brands_LegacyObjectId ON dbo.Brands(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE INDEX IX_Brands_NormalizedName ON dbo.Brands(NormalizedName) WHERE IsDeleted=0;
CREATE TABLE dbo.ProductTypes (ProductTypeId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, Name nvarchar(200) NOT NULL, NormalizedName nvarchar(200) NOT NULL, Icon nvarchar(120) NULL, Source nvarchar(20) NOT NULL, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT CK_ProductTypes_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_ProductTypes_LegacyObjectId ON dbo.ProductTypes(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE TABLE dbo.Categories (CategoryId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, Name nvarchar(200) NOT NULL, NormalizedName nvarchar(200) NOT NULL, ImageUrl nvarchar(1000) NULL, SortOrder int NOT NULL DEFAULT 0, Source nvarchar(20) NOT NULL, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT CK_Categories_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_Categories_LegacyObjectId ON dbo.Categories(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE TABLE dbo.CategoryValues (CategoryValueId uniqueidentifier NOT NULL PRIMARY KEY, CategoryId uniqueidentifier NOT NULL, Name nvarchar(200) NOT NULL, NormalizedName nvarchar(200) NOT NULL, SortOrder int NOT NULL DEFAULT 0, Source nvarchar(20) NOT NULL, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_CategoryValues_Categories FOREIGN KEY(CategoryId) REFERENCES dbo.Categories(CategoryId), CONSTRAINT UQ_CategoryValues_Category_Value UNIQUE(CategoryId,CategoryValueId), CONSTRAINT CK_CategoryValues_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_CategoryValues_Category_NormalizedName ON dbo.CategoryValues(CategoryId,NormalizedName) WHERE IsDeleted=0;
CREATE TABLE dbo.Units (UnitId uniqueidentifier NOT NULL PRIMARY KEY, Name nvarchar(100) NOT NULL, NormalizedName nvarchar(100) NOT NULL, DecimalScale tinyint NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT CK_Units_DecimalScale CHECK(DecimalScale BETWEEN 0 AND 6), CONSTRAINT CK_Units_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_Units_NormalizedName ON dbo.Units(NormalizedName) WHERE IsDeleted=0;
CREATE TABLE dbo.ProductOptions (ProductOptionId uniqueidentifier NOT NULL PRIMARY KEY, OptionType nvarchar(30) NOT NULL, Value nvarchar(200) NOT NULL, NormalizedValue nvarchar(200) NOT NULL, SortOrder int NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT CK_ProductOptions_Type CHECK(OptionType IN(N'Color',N'Shape',N'Frame',N'ButtonCount')), CONSTRAINT CK_ProductOptions_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_ProductOptions_Type_Value ON dbo.ProductOptions(OptionType,NormalizedValue) WHERE IsDeleted=0;
CREATE TABLE dbo.Products (ProductId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, ProductTypeId uniqueidentifier NULL, BrandId uniqueidentifier NULL, CategoryId uniqueidentifier NULL, CategoryValueId uniqueidentifier NULL, Code nvarchar(100) NULL, NormalizedCode nvarchar(100) NULL, Name nvarchar(300) NOT NULL, SearchName nvarchar(300) NOT NULL, IsVisible bit NOT NULL DEFAULT 1, IsAdjusted bit NOT NULL DEFAULT 0, VatRate decimal(5,2) NULL, LegacyVat nvarchar(20) NULL, Warranty nvarchar(1000) NULL, Solution nvarchar(max) NULL, Description nvarchar(max) NULL, Features nvarchar(max) NULL, OperatingMethod nvarchar(max) NULL, Advantages nvarchar(max) NULL, Specifications nvarchar(max) NULL, PurchaseCount int NOT NULL DEFAULT 0, TotalRating decimal(19,4) NOT NULL DEFAULT 0, ReviewCount int NOT NULL DEFAULT 0, AverageRating decimal(9,4) NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_Products_Types FOREIGN KEY(ProductTypeId) REFERENCES dbo.ProductTypes(ProductTypeId), CONSTRAINT FK_Products_Brands FOREIGN KEY(BrandId) REFERENCES dbo.Brands(BrandId), CONSTRAINT FK_Products_Categories FOREIGN KEY(CategoryId) REFERENCES dbo.Categories(CategoryId), CONSTRAINT FK_Products_CategoryValues FOREIGN KEY(CategoryId,CategoryValueId) REFERENCES dbo.CategoryValues(CategoryId,CategoryValueId), CONSTRAINT CK_Products_Code CHECK((Code IS NULL AND NormalizedCode IS NULL) OR (Code IS NOT NULL AND NormalizedCode=UPPER(LTRIM(RTRIM(Code))))), CONSTRAINT CK_Products_NonNegative CHECK(PurchaseCount>=0 AND TotalRating>=0 AND ReviewCount>=0 AND AverageRating>=0), CONSTRAINT CK_Products_Vat CHECK(VatRate IS NULL OR VatRate BETWEEN 0 AND 100), CONSTRAINT CK_Products_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_Products_LegacyObjectId ON dbo.Products(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE UNIQUE INDEX UX_Products_NormalizedCode ON dbo.Products(NormalizedCode) WHERE NormalizedCode IS NOT NULL AND IsDeleted=0;
CREATE INDEX IX_Products_Search ON dbo.Products(SearchName,IsVisible,IsDeleted);
CREATE TABLE dbo.ProductVariants (ProductVariantId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, ProductId uniqueidentifier NOT NULL, Position int NOT NULL, SalePrice decimal(19,4) NULL, ImportPrice decimal(19,4) NULL, ProfitPercent decimal(9,4) NULL, ImageUrl nvarchar(1000) NULL, Color nvarchar(200) NULL, Shape nvarchar(200) NULL, ButtonCount nvarchar(100) NULL, Frame nvarchar(200) NULL, Note nvarchar(2000) NULL, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_ProductVariants_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT UQ_ProductVariants_Product_Position UNIQUE(ProductId,Position), CONSTRAINT CK_ProductVariants_Position CHECK(Position>=0), CONSTRAINT CK_ProductVariants_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_ProductVariants_Product_Legacy ON dbo.ProductVariants(ProductId,LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE TABLE dbo.ProductFiles (ProductFileId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, ProductId uniqueidentifier NOT NULL, FileType nvarchar(30) NOT NULL, Label nvarchar(200) NULL, Url nvarchar(1000) NOT NULL, SourceType nvarchar(50) NULL, SortOrder int NOT NULL DEFAULT 0, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, CONSTRAINT FK_ProductFiles_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT CK_ProductFiles_Type CHECK(FileType IN(N'Manual',N'DataSheet',N'Catalog',N'Other',N'Document')));
CREATE TABLE dbo.ProductReviews (ProductReviewId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, ProductId uniqueidentifier NOT NULL, ReviewerEmail nvarchar(320) NULL, Comment nvarchar(4000) NULL, Rating tinyint NOT NULL, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, CONSTRAINT FK_ProductReviews_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT CK_ProductReviews_Rating CHECK(Rating BETWEEN 1 AND 5));
CREATE UNIQUE INDEX UX_ProductReviews_LegacyObjectId ON dbo.ProductReviews(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
INSERT dbo.SchemaVersions(SchemaVersionId,MigrationNumber,MigrationName,ScriptChecksum,AppliedBy) VALUES(NEWID(),2,N'002_CreateCatalogTables.sql',NULL,ORIGINAL_LOGIN());
COMMIT TRANSACTION;
GO
