SET NOCOUNT ON; SET XACT_ABORT ON; SET ANSI_NULLS ON; SET QUOTED_IDENTIFIER ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT ON; SET CONCAT_NULL_YIELDS_NULL ON; SET NUMERIC_ROUNDABORT OFF;
GO
USE [TTSmart];
GO
IF DB_NAME()<>N'TTSmart' THROW 51130,N'Script phải chạy trên [TTSmart].',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=3) BEGIN PRINT N'Migration 003 đã được áp dụng; không có thay đổi.'; RETURN; END;
IF NOT EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=2) THROW 51131,N'Chưa áp dụng migration 002.',1;
BEGIN TRANSACTION;
CREATE TABLE dbo.Users (UserId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, Name nvarchar(200) NOT NULL, Phone nvarchar(32) NULL, Email nvarchar(320) NULL, RoleCode nvarchar(30) NULL, IsActive bit NOT NULL DEFAULT 1, SourceCreatedAtUtc datetime2(7) NULL, SourceUpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, Version bigint NOT NULL DEFAULT 1, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT CK_Users_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_Users_LegacyObjectId ON dbo.Users(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE INDEX IX_Users_Phone ON dbo.Users(Phone) WHERE IsDeleted=0;
CREATE TABLE dbo.Customers (CustomerId uniqueidentifier NOT NULL PRIMARY KEY, UserId uniqueidentifier NULL, LegacyUserObjectId char(24) NULL, Name nvarchar(200) NOT NULL, Phone nvarchar(32) NULL, NormalizedPhone nvarchar(32) NULL, Email nvarchar(320) NULL, Status nvarchar(20) NOT NULL DEFAULT N'Active', Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_Customers_Users FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId), CONSTRAINT CK_Customers_Status CHECK(Status IN(N'Active',N'Inactive')), CONSTRAINT CK_Customers_Phone CHECK((Phone IS NULL AND NormalizedPhone IS NULL) OR NormalizedPhone=UPPER(LTRIM(RTRIM(Phone)))), CONSTRAINT CK_Customers_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_Customers_User ON dbo.Customers(UserId) WHERE UserId IS NOT NULL AND IsDeleted=0;
CREATE TABLE dbo.CustomerContacts (CustomerContactId uniqueidentifier NOT NULL PRIMARY KEY, CustomerId uniqueidentifier NOT NULL, ContactType nvarchar(20) NOT NULL, Value nvarchar(320) NOT NULL, NormalizedValue nvarchar(320) NOT NULL, IsPrimary bit NOT NULL DEFAULT 0, IsVerified bit NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_CustomerContacts_Customers FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(CustomerId), CONSTRAINT CK_CustomerContacts_Type CHECK(ContactType IN(N'Phone',N'Email',N'Other')), CONSTRAINT CK_CustomerContacts_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_CustomerContacts_Primary ON dbo.CustomerContacts(CustomerId) WHERE IsPrimary=1 AND IsDeleted=0;
CREATE TABLE dbo.CustomerAddresses (CustomerAddressId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, CustomerId uniqueidentifier NOT NULL, Label nvarchar(100) NULL, ReceiverName nvarchar(200) NOT NULL, ReceiverPhone nvarchar(32) NULL, AddressDetail nvarchar(1000) NOT NULL, IsDefault bit NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_CustomerAddresses_Customers FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(CustomerId), CONSTRAINT CK_CustomerAddresses_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_CustomerAddresses_Default ON dbo.CustomerAddresses(CustomerId) WHERE IsDefault=1 AND IsDeleted=0;
CREATE TABLE dbo.Carts (CartId uniqueidentifier NOT NULL PRIMARY KEY, LegacyUserObjectId char(24) NULL, UserId uniqueidentifier NOT NULL, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), Version bigint NOT NULL DEFAULT 1, RowVersion rowversion NOT NULL, CONSTRAINT FK_Carts_Users FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId), CONSTRAINT UQ_Carts_User UNIQUE(UserId), CONSTRAINT CK_Carts_Version CHECK(Version>0));
CREATE TABLE dbo.CartItems (CartItemId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, CartId uniqueidentifier NOT NULL, ProductId uniqueidentifier NOT NULL, ProductVariantId uniqueidentifier NOT NULL, LegacyProductObjectId char(24) NULL, LegacyVariantIndex int NULL, Quantity int NOT NULL, IsSelected bit NOT NULL DEFAULT 1, SortOrder int NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL, CONSTRAINT FK_CartItems_Carts FOREIGN KEY(CartId) REFERENCES dbo.Carts(CartId), CONSTRAINT FK_CartItems_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT FK_CartItems_Variants FOREIGN KEY(ProductVariantId) REFERENCES dbo.ProductVariants(ProductVariantId), CONSTRAINT CK_CartItems_Quantity CHECK(Quantity>0), CONSTRAINT CK_CartItems_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_CartItems_Cart_Variant ON dbo.CartItems(CartId,ProductVariantId);
CREATE TABLE dbo.OrderTemplates (OrderTemplateId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, UserId uniqueidentifier NOT NULL, DisplayName nvarchar(200) NOT NULL, Note nvarchar(2000) NULL, SortOrder int NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_OrderTemplates_Users FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId), CONSTRAINT CK_OrderTemplates_Version CHECK(Version>0));
CREATE TABLE dbo.OrderTemplateItems (OrderTemplateItemId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, OrderTemplateId uniqueidentifier NOT NULL, ProductId uniqueidentifier NOT NULL, LegacyProductObjectId char(24) NULL, Quantity int NOT NULL, SortOrder int NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL, CONSTRAINT FK_OrderTemplateItems_Templates FOREIGN KEY(OrderTemplateId) REFERENCES dbo.OrderTemplates(OrderTemplateId), CONSTRAINT FK_OrderTemplateItems_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT CK_OrderTemplateItems_Quantity CHECK(Quantity>0), CONSTRAINT CK_OrderTemplateItems_Version CHECK(Version>0));
INSERT dbo.SchemaVersions(SchemaVersionId,MigrationNumber,MigrationName,ScriptChecksum,AppliedBy) VALUES(NEWID(),3,N'003_CreateUserAndCustomerTables.sql',NULL,ORIGINAL_LOGIN());
COMMIT TRANSACTION;
GO
