SET NOCOUNT ON; SET XACT_ABORT ON; SET ANSI_NULLS ON; SET QUOTED_IDENTIFIER ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT ON; SET CONCAT_NULL_YIELDS_NULL ON; SET NUMERIC_ROUNDABORT OFF;
GO
USE [TTSmart];
GO
IF DB_NAME()<>N'TTSmart' THROW 51140,N'Script phải chạy trên [TTSmart].',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=4) BEGIN PRINT N'Migration 004 đã được áp dụng; không có thay đổi.'; RETURN; END;
IF NOT EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=3) THROW 51141,N'Chưa áp dụng migration 003.',1;
BEGIN TRANSACTION;
CREATE TABLE dbo.SalesOrders (SalesOrderId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, OrderCode nvarchar(50) NOT NULL, CustomerId uniqueidentifier NULL, CustomerName nvarchar(200) NULL, CustomerPhone nvarchar(32) NULL, Total decimal(19,4) NOT NULL, Status nvarchar(20) NOT NULL, State nvarchar(20) NOT NULL, IsPaid bit NOT NULL DEFAULT 0, CompletedAtUtc datetime2(7) NULL, CompletedAtMissing bit NOT NULL DEFAULT 0, LegacyOrderName nvarchar(300) NULL, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_SalesOrders_Customers FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(CustomerId), CONSTRAINT UQ_SalesOrders_OrderCode UNIQUE(OrderCode), CONSTRAINT CK_SalesOrders_Status CHECK(Status IN(N'Processing',N'Delivering',N'Completed')), CONSTRAINT CK_SalesOrders_State CHECK(State IN(N'Processing',N'Cancelled')), CONSTRAINT CK_SalesOrders_Total CHECK(Total>=0), CONSTRAINT CK_SalesOrders_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_SalesOrders_LegacyObjectId ON dbo.SalesOrders(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE INDEX IX_SalesOrders_CustomerPhone ON dbo.SalesOrders(CustomerPhone,CreatedAtUtc DESC);
CREATE INDEX IX_SalesOrders_Status_State_Date ON dbo.SalesOrders(Status,State,CreatedAtUtc DESC) WHERE IsDeleted=0;
CREATE TABLE dbo.SalesOrderItems (SalesOrderItemId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, SalesOrderId uniqueidentifier NOT NULL, ProductId uniqueidentifier NULL, ProductVariantId uniqueidentifier NULL, LegacyProductObjectId char(24) NOT NULL, LegacyVariantIndex int NULL, Quantity int NOT NULL, UnitPrice decimal(19,4) NULL, LegacyPrice nvarchar(100) NULL, LegacyUnit nvarchar(100) NULL, LegacyNote nvarchar(2000) NULL, LegacyStatus bit NULL, SortOrder int NOT NULL DEFAULT 0, DataStatus nvarchar(20) NOT NULL DEFAULT N'Valid', CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_SalesOrderItems_Orders FOREIGN KEY(SalesOrderId) REFERENCES dbo.SalesOrders(SalesOrderId), CONSTRAINT FK_SalesOrderItems_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT FK_SalesOrderItems_Variants FOREIGN KEY(ProductVariantId) REFERENCES dbo.ProductVariants(ProductVariantId), CONSTRAINT CK_SalesOrderItems_Quantity CHECK(Quantity>0), CONSTRAINT CK_SalesOrderItems_Status CHECK(DataStatus IN(N'Valid',N'Orphan',N'MissingData')));
CREATE UNIQUE INDEX UX_SalesOrderItems_Order_Legacy ON dbo.SalesOrderItems(SalesOrderId,LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE TABLE dbo.SalesOrderFiles (SalesOrderFileId uniqueidentifier NOT NULL PRIMARY KEY, SalesOrderId uniqueidentifier NOT NULL, Url nvarchar(1000) NOT NULL, SortOrder int NOT NULL DEFAULT 0, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, CONSTRAINT FK_SalesOrderFiles_Orders FOREIGN KEY(SalesOrderId) REFERENCES dbo.SalesOrders(SalesOrderId));
INSERT dbo.SchemaVersions(SchemaVersionId,MigrationNumber,MigrationName,ScriptChecksum,AppliedBy) VALUES(NEWID(),4,N'004_CreateSalesTables.sql',NULL,ORIGINAL_LOGIN());
COMMIT TRANSACTION;
GO
