SET NOCOUNT ON; SET XACT_ABORT ON; SET ANSI_NULLS ON; SET QUOTED_IDENTIFIER ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT ON; SET CONCAT_NULL_YIELDS_NULL ON; SET NUMERIC_ROUNDABORT OFF;
GO
USE [TTSmart];
GO
IF DB_NAME()<>N'TTSmart' THROW 51150,N'Script phải chạy trên [TTSmart].',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=5) BEGIN PRINT N'Migration 005 đã được áp dụng; không có thay đổi.'; RETURN; END;
IF NOT EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=4) THROW 51151,N'Chưa áp dụng migration 004.',1;
BEGIN TRANSACTION;
CREATE TABLE dbo.Stocks (StockId uniqueidentifier NOT NULL PRIMARY KEY, ProductVariantId uniqueidentifier NOT NULL, QuantityForSale int NOT NULL DEFAULT 0, QuantityInStorage int NOT NULL DEFAULT 0, AsOfUtc datetime2(7) NOT NULL, Version bigint NOT NULL DEFAULT 1, UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL, CONSTRAINT FK_Stocks_Variants FOREIGN KEY(ProductVariantId) REFERENCES dbo.ProductVariants(ProductVariantId), CONSTRAINT UQ_Stocks_Variant UNIQUE(ProductVariantId), CONSTRAINT CK_Stocks_NonNegative CHECK(QuantityForSale>=0 AND QuantityInStorage>=0), CONSTRAINT CK_Stocks_Version CHECK(Version>0));
CREATE TABLE dbo.StockMovements (StockMovementId uniqueidentifier NOT NULL PRIMARY KEY, ProductVariantId uniqueidentifier NOT NULL, SourceType nvarchar(30) NOT NULL, SourceId uniqueidentifier NULL, SourceItemId uniqueidentifier NULL, QuantityForSaleChange int NOT NULL DEFAULT 0, QuantityInStorageChange int NOT NULL DEFAULT 0, PurchaseCountChange int NOT NULL DEFAULT 0, Note nvarchar(2000) NULL, ActorUserId uniqueidentifier NULL, OccurredAtUtc datetime2(7) NOT NULL, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_StockMovements_Variants FOREIGN KEY(ProductVariantId) REFERENCES dbo.ProductVariants(ProductVariantId), CONSTRAINT FK_StockMovements_Users FOREIGN KEY(ActorUserId) REFERENCES dbo.Users(UserId), CONSTRAINT CK_StockMovements_Source CHECK(SourceId IS NOT NULL OR SourceType=N'Manual'));
CREATE UNIQUE INDEX UX_StockMovements_Source ON dbo.StockMovements(SourceType,SourceId,SourceItemId) WHERE SourceId IS NOT NULL;
CREATE INDEX IX_StockMovements_Variant_Date ON dbo.StockMovements(ProductVariantId,OccurredAtUtc DESC);
CREATE TABLE dbo.LegacyStockHistories (LegacyStockHistoryId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NOT NULL, ProductId uniqueidentifier NULL, LegacyProductObjectId char(24) NOT NULL, ProductName nvarchar(300) NULL, Quantity int NOT NULL, UserName nvarchar(200) NULL, LegacyOrderId nvarchar(100) NULL, OrderName nvarchar(300) NULL, Note nvarchar(2000) NULL, IsAiScan bit NOT NULL DEFAULT 0, Source nvarchar(50) NULL, DataStatus nvarchar(20) NOT NULL, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_LegacyStockHistories_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT UQ_LegacyStockHistories_ObjectId UNIQUE(LegacyObjectId), CONSTRAINT CK_LegacyStockHistories_Status CHECK(DataStatus IN(N'Valid',N'Orphan',N'MissingSource')));
CREATE TABLE dbo.ImportOrders (ImportOrderId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, OrderName nvarchar(300) NOT NULL, Note nvarchar(2000) NULL, ActorUserId uniqueidentifier NULL, UserName nvarchar(200) NOT NULL, Total decimal(19,4) NOT NULL, LegacyTotal nvarchar(100) NULL, IsCompleted bit NOT NULL DEFAULT 0, CompletedAtUtc datetime2(7) NULL, CompletedAtMissing bit NOT NULL DEFAULT 0, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, Version bigint NOT NULL DEFAULT 1, RowVersion rowversion NOT NULL, CONSTRAINT FK_ImportOrders_Users FOREIGN KEY(ActorUserId) REFERENCES dbo.Users(UserId), CONSTRAINT CK_ImportOrders_Total CHECK(Total>=0), CONSTRAINT CK_ImportOrders_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_ImportOrders_LegacyObjectId ON dbo.ImportOrders(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE TABLE dbo.ImportOrderItems (ImportOrderItemId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, ImportOrderId uniqueidentifier NOT NULL, ProductId uniqueidentifier NULL, LegacyProductObjectId char(24) NOT NULL, UnitId uniqueidentifier NULL, UnitName nvarchar(100) NOT NULL, UnitPrice decimal(19,4) NULL, LegacyPrice nvarchar(100) NULL, VatRate decimal(5,2) NULL, LegacyVat nvarchar(20) NULL, Quantity int NOT NULL, ReceivedQuantity int NOT NULL DEFAULT 0, StockAppliedQuantity int NULL, IsCompleted bit NOT NULL DEFAULT 0, Note nvarchar(2000) NULL, SortOrder int NOT NULL DEFAULT 0, DataStatus nvarchar(20) NOT NULL DEFAULT N'Valid', CONSTRAINT FK_ImportOrderItems_Orders FOREIGN KEY(ImportOrderId) REFERENCES dbo.ImportOrders(ImportOrderId), CONSTRAINT FK_ImportOrderItems_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT FK_ImportOrderItems_Units FOREIGN KEY(UnitId) REFERENCES dbo.Units(UnitId), CONSTRAINT CK_ImportOrderItems_Quantity CHECK(Quantity>=0 AND ReceivedQuantity>=0 AND (StockAppliedQuantity IS NULL OR StockAppliedQuantity>=0)), CONSTRAINT CK_ImportOrderItems_Status CHECK(DataStatus IN(N'Valid',N'Orphan',N'MissingData')));
CREATE UNIQUE INDEX UX_ImportOrderItems_Order_Legacy ON dbo.ImportOrderItems(ImportOrderId,LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE TABLE dbo.ImportOrderFiles (ImportOrderFileId uniqueidentifier NOT NULL PRIMARY KEY, ImportOrderId uniqueidentifier NOT NULL, Url nvarchar(1000) NOT NULL, SortOrder int NOT NULL DEFAULT 0, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, CONSTRAINT FK_ImportOrderFiles_Orders FOREIGN KEY(ImportOrderId) REFERENCES dbo.ImportOrders(ImportOrderId));
CREATE TABLE dbo.ExportOrders (ExportOrderId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, OrderName nvarchar(300) NOT NULL, Note nvarchar(2000) NULL, ActorUserId uniqueidentifier NULL, UserName nvarchar(200) NOT NULL, Total decimal(19,4) NOT NULL, LegacyTotal nvarchar(100) NULL, IsCompleted bit NOT NULL DEFAULT 0, CompletedAtUtc datetime2(7) NULL, CompletedAtMissing bit NOT NULL DEFAULT 0, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, Version bigint NOT NULL DEFAULT 1, RowVersion rowversion NOT NULL, CONSTRAINT FK_ExportOrders_Users FOREIGN KEY(ActorUserId) REFERENCES dbo.Users(UserId), CONSTRAINT CK_ExportOrders_Total CHECK(Total>=0), CONSTRAINT CK_ExportOrders_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_ExportOrders_LegacyObjectId ON dbo.ExportOrders(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE TABLE dbo.ExportOrderItems (ExportOrderItemId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, ExportOrderId uniqueidentifier NOT NULL, ProductId uniqueidentifier NULL, LegacyProductObjectId char(24) NOT NULL, UnitId uniqueidentifier NULL, UnitName nvarchar(100) NOT NULL, UnitPrice decimal(19,4) NULL, LegacyPrice nvarchar(100) NULL, ImportPriceSnapshot decimal(19,4) NULL, ProfitPercent decimal(9,4) NULL, VatRate decimal(5,2) NULL, LegacyVat nvarchar(20) NULL, Quantity int NOT NULL, ExportedQuantity int NOT NULL DEFAULT 0, StockAppliedQuantity int NULL, StockUpdateSkipped bit NOT NULL DEFAULT 0, IsCompleted bit NOT NULL DEFAULT 0, Note nvarchar(2000) NULL, SortOrder int NOT NULL DEFAULT 0, DataStatus nvarchar(20) NOT NULL DEFAULT N'Valid', CONSTRAINT FK_ExportOrderItems_Orders FOREIGN KEY(ExportOrderId) REFERENCES dbo.ExportOrders(ExportOrderId), CONSTRAINT FK_ExportOrderItems_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT FK_ExportOrderItems_Units FOREIGN KEY(UnitId) REFERENCES dbo.Units(UnitId), CONSTRAINT CK_ExportOrderItems_Quantity CHECK(Quantity>=0 AND ExportedQuantity>=0 AND (StockAppliedQuantity IS NULL OR StockAppliedQuantity>=0)), CONSTRAINT CK_ExportOrderItems_Status CHECK(DataStatus IN(N'Valid',N'Orphan',N'MissingData')));
CREATE UNIQUE INDEX UX_ExportOrderItems_Order_Legacy ON dbo.ExportOrderItems(ExportOrderId,LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE TABLE dbo.ExportOrderFiles (ExportOrderFileId uniqueidentifier NOT NULL PRIMARY KEY, ExportOrderId uniqueidentifier NOT NULL, Url nvarchar(1000) NOT NULL, SortOrder int NOT NULL DEFAULT 0, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, CONSTRAINT FK_ExportOrderFiles_Orders FOREIGN KEY(ExportOrderId) REFERENCES dbo.ExportOrders(ExportOrderId));
INSERT dbo.SchemaVersions(SchemaVersionId,MigrationNumber,MigrationName,ScriptChecksum,AppliedBy) VALUES(NEWID(),5,N'005_CreateInventoryTables.sql',NULL,ORIGINAL_LOGIN());
COMMIT TRANSACTION;
GO
