SET NOCOUNT ON; SET XACT_ABORT ON; SET ANSI_NULLS ON; SET QUOTED_IDENTIFIER ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT ON; SET CONCAT_NULL_YIELDS_NULL ON; SET NUMERIC_ROUNDABORT OFF;
GO
USE [TTSmart];
GO
IF DB_NAME()<>N'TTSmart' THROW 51160,N'Script phải chạy trên [TTSmart].',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=6) BEGIN PRINT N'Migration 006 đã được áp dụng; không có thay đổi.'; RETURN; END;
IF NOT EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=5) THROW 51161,N'Chưa áp dụng migration 005.',1;
BEGIN TRANSACTION;
CREATE TABLE dbo.Stations (StationId uniqueidentifier NOT NULL PRIMARY KEY, LegacyObjectId char(24) NULL, StationCode nvarchar(100) NOT NULL, NormalizedStationCode nvarchar(100) NOT NULL, Name nvarchar(300) NOT NULL, ImageUrl nvarchar(1000) NULL, Location nvarchar(1000) NULL, AllowPublicSignup bit NOT NULL DEFAULT 1, DefaultApplied bit NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT UQ_Stations_NormalizedCode UNIQUE(NormalizedStationCode), CONSTRAINT CK_Stations_Code CHECK(NormalizedStationCode=UPPER(LTRIM(RTRIM(StationCode)))), CONSTRAINT CK_Stations_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_Stations_LegacyObjectId ON dbo.Stations(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
CREATE TABLE dbo.StationProducts (StationProductId uniqueidentifier NOT NULL PRIMARY KEY, StationId uniqueidentifier NOT NULL, ProductId uniqueidentifier NOT NULL, LegacyProductObjectId char(24) NULL, SortOrder int NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_StationProducts_Stations FOREIGN KEY(StationId) REFERENCES dbo.Stations(StationId), CONSTRAINT FK_StationProducts_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT CK_StationProducts_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_StationProducts_Station_Product ON dbo.StationProducts(StationId,ProductId) WHERE IsDeleted=0;
CREATE TABLE dbo.UserStations (UserStationId uniqueidentifier NOT NULL PRIMARY KEY, UserId uniqueidentifier NOT NULL, StationId uniqueidentifier NOT NULL, LegacyStationObjectId char(24) NULL, AssignedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, CONSTRAINT FK_UserStations_Users FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId), CONSTRAINT FK_UserStations_Stations FOREIGN KEY(StationId) REFERENCES dbo.Stations(StationId));
CREATE UNIQUE INDEX UX_UserStations_User_Station ON dbo.UserStations(UserId,StationId) WHERE IsDeleted=0;
CREATE TABLE dbo.StorefrontSettings (StorefrontSettingId uniqueidentifier NOT NULL PRIMARY KEY, SingletonKey tinyint NOT NULL UNIQUE, DisplayPartners bit NOT NULL DEFAULT 0, FooterLogo nvarchar(1000) NULL, FooterDescription nvarchar(max) NULL, FooterAddress nvarchar(1000) NULL, FooterPhone nvarchar(32) NULL, FooterEmail nvarchar(320) NULL, NewProductUrl nvarchar(1000) NULL, TopPurchaseUrl nvarchar(1000) NULL, HighestRatingUrl nvarchar(1000) NULL, IntroductionVi nvarchar(max) NULL, IntroductionEn nvarchar(max) NULL, IntroductionZh nvarchar(max) NULL, MainPolicy nvarchar(max) NULL, HomeCategoriesConfigured bit NOT NULL DEFAULT 0, SidebarTitleVi nvarchar(300) NULL, SidebarTitleEn nvarchar(300) NULL, SidebarTitleZh nvarchar(300) NULL, ShowSidebar bit NOT NULL DEFAULT 0, ShowQuickCategories bit NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, RowVersion rowversion NOT NULL, CONSTRAINT CK_StorefrontSettings_Singleton CHECK(SingletonKey=1), CONSTRAINT CK_StorefrontSettings_Version CHECK(Version>0));
CREATE TABLE dbo.StorefrontImages (StorefrontImageId uniqueidentifier NOT NULL PRIMARY KEY, ImageType nvarchar(20) NOT NULL, Url nvarchar(1000) NOT NULL, SortOrder int NOT NULL DEFAULT 0, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, CONSTRAINT CK_StorefrontImages_Type CHECK(ImageType IN(N'Overview',N'Partner')));
CREATE TABLE dbo.StorefrontSections (StorefrontSectionId uniqueidentifier NOT NULL PRIMARY KEY, LegacySectionNumber tinyint NOT NULL, NameVi nvarchar(300) NULL, NameEn nvarchar(300) NULL, NameZh nvarchar(300) NULL, ImageUrl nvarchar(1000) NULL, Link nvarchar(1000) NULL, IsVisible bit NOT NULL DEFAULT 1, SortOrder int NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT UQ_StorefrontSections_Number UNIQUE(LegacySectionNumber), CONSTRAINT CK_StorefrontSections_Version CHECK(Version>0));
CREATE TABLE dbo.StorefrontSectionProducts (StorefrontSectionProductId uniqueidentifier NOT NULL PRIMARY KEY, StorefrontSectionId uniqueidentifier NOT NULL, ProductId uniqueidentifier NOT NULL, LegacyProductObjectId char(24) NULL, SortOrder int NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_StorefrontSectionProducts_Sections FOREIGN KEY(StorefrontSectionId) REFERENCES dbo.StorefrontSections(StorefrontSectionId), CONSTRAINT FK_StorefrontSectionProducts_Products FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT CK_StorefrontSectionProducts_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_StorefrontSectionProducts_Section_Product ON dbo.StorefrontSectionProducts(StorefrontSectionId,ProductId) WHERE IsDeleted=0;
CREATE TABLE dbo.HomeCategories (HomeCategoryId uniqueidentifier NOT NULL PRIMARY KEY, LegacyKey nvarchar(100) NULL, LabelVi nvarchar(300) NULL, LabelEn nvarchar(300) NULL, LabelZh nvarchar(300) NULL, CategoryType nvarchar(50) NULL, Link nvarchar(1000) NULL, Icon nvarchar(1000) NULL, ImageUrl nvarchar(1000) NULL, ShowSidebar bit NOT NULL DEFAULT 0, ShowQuick bit NOT NULL DEFAULT 0, SortOrder int NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT CK_HomeCategories_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_HomeCategories_LegacyKey ON dbo.HomeCategories(LegacyKey) WHERE LegacyKey IS NOT NULL AND IsDeleted=0;
CREATE TABLE dbo.Policies (PolicyId uniqueidentifier NOT NULL PRIMARY KEY, PolicyKey nvarchar(30) NOT NULL, TitleVi nvarchar(300) NULL, TitleEn nvarchar(300) NULL, TitleZh nvarchar(300) NULL, SummaryVi nvarchar(max) NULL, SummaryEn nvarchar(max) NULL, SummaryZh nvarchar(max) NULL, SourceUpdatedAtUtc datetime2(7) NULL, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT UQ_Policies_Key UNIQUE(PolicyKey), CONSTRAINT CK_Policies_Key CHECK(PolicyKey IN(N'purchase',N'warranty',N'shipping',N'privacy')), CONSTRAINT CK_Policies_Version CHECK(Version>0));
CREATE TABLE dbo.PolicySections (PolicySectionId uniqueidentifier NOT NULL PRIMARY KEY, PolicyId uniqueidentifier NOT NULL, SortOrder int NOT NULL DEFAULT 0, TitleVi nvarchar(300) NULL, TitleEn nvarchar(300) NULL, TitleZh nvarchar(300) NULL, ContentVi nvarchar(max) NULL, ContentEn nvarchar(max) NULL, ContentZh nvarchar(max) NULL, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_PolicySections_Policies FOREIGN KEY(PolicyId) REFERENCES dbo.Policies(PolicyId), CONSTRAINT CK_PolicySections_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_PolicySections_Policy_Sort ON dbo.PolicySections(PolicyId,SortOrder) WHERE IsDeleted=0;
INSERT dbo.SchemaVersions(SchemaVersionId,MigrationNumber,MigrationName,ScriptChecksum,AppliedBy) VALUES(NEWID(),6,N'006_CreateStorefrontTables.sql',NULL,ORIGINAL_LOGIN());
COMMIT TRANSACTION;
GO
