SET NOCOUNT ON; SET XACT_ABORT ON; SET ANSI_NULLS ON; SET QUOTED_IDENTIFIER ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT ON; SET CONCAT_NULL_YIELDS_NULL ON; SET NUMERIC_ROUNDABORT OFF;
GO
USE [TTSmart];
GO
IF DB_NAME()<>N'TTSmart' THROW 51170,N'Script phải chạy trên [TTSmart].',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=7) BEGIN PRINT N'Migration 007 đã được áp dụng; không có thay đổi.'; RETURN; END;
IF NOT EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE MigrationNumber=6) THROW 51171,N'Chưa áp dụng migration 006.',1;
BEGIN TRANSACTION;
CREATE TABLE dbo.VoiceWords (VoiceWordId uniqueidentifier NOT NULL PRIMARY KEY, WordType nvarchar(20) NOT NULL, Value nvarchar(300) NOT NULL, NormalizedValue nvarchar(300) NOT NULL, SortOrder int NOT NULL DEFAULT 0, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, CONSTRAINT CK_VoiceWords_Type CHECK(WordType IN(N'Stopword',N'Brand',N'ProductType')));
CREATE UNIQUE INDEX UX_VoiceWords_Type_Value ON dbo.VoiceWords(WordType,NormalizedValue) WHERE IsDeleted=0;
CREATE TABLE dbo.VoiceAliases (VoiceAliasId uniqueidentifier NOT NULL PRIMARY KEY, AliasType nvarchar(20) NOT NULL, Name nvarchar(300) NULL, Keyword nvarchar(300) NULL, Label nvarchar(300) NULL, BrandName nvarchar(200) NULL, ProductTypeName nvarchar(200) NULL, Code nvarchar(100) NULL, Compact nvarchar(300) NULL, SortOrder int NOT NULL DEFAULT 0, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, CONSTRAINT CK_VoiceAliases_Type CHECK(AliasType IN(N'Brand',N'ProductType',N'Intent',N'Code')));
CREATE TABLE dbo.VoiceAliasValues (VoiceAliasValueId uniqueidentifier NOT NULL PRIMARY KEY, VoiceAliasId uniqueidentifier NOT NULL, ValueType nvarchar(20) NOT NULL, Value nvarchar(500) NOT NULL, SortOrder int NOT NULL DEFAULT 0, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_VoiceAliasValues_Aliases FOREIGN KEY(VoiceAliasId) REFERENCES dbo.VoiceAliases(VoiceAliasId), CONSTRAINT CK_VoiceAliasValues_Type CHECK(ValueType IN(N'Alias',N'Pattern')));
CREATE UNIQUE INDEX UX_VoiceAliasValues_Alias_Value ON dbo.VoiceAliasValues(VoiceAliasId,Value);
CREATE TABLE dbo.Integrations (IntegrationId uniqueidentifier NOT NULL PRIMARY KEY, ProviderCode nvarchar(30) NOT NULL, IsEnabled bit NOT NULL DEFAULT 0, PublicAppId nvarchar(200) NULL, PublicAccountId nvarchar(200) NULL, PublicRecipientId nvarchar(200) NULL, SecretReferenceId uniqueidentifier NULL, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL, CONSTRAINT UQ_Integrations_Provider UNIQUE(ProviderCode), CONSTRAINT CK_Integrations_Provider CHECK(ProviderCode IN(N'Zalo',N'Telegram')), CONSTRAINT CK_Integrations_Version CHECK(Version>0));
CREATE TABLE dbo.NotificationRecipients (NotificationRecipientId uniqueidentifier NOT NULL PRIMARY KEY, IntegrationId uniqueidentifier NOT NULL, LegacyObjectId char(24) NULL, Label nvarchar(200) NULL, RecipientSecretReferenceId uniqueidentifier NOT NULL, RecipientType nvarchar(30) NOT NULL, IsEnabled bit NOT NULL DEFAULT 1, NotifyNewOrder bit NOT NULL DEFAULT 1, SortOrder int NOT NULL DEFAULT 0, Version bigint NOT NULL DEFAULT 1, CreatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL DEFAULT SYSUTCDATETIME(), IsDeleted bit NOT NULL DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_NotificationRecipients_Integrations FOREIGN KEY(IntegrationId) REFERENCES dbo.Integrations(IntegrationId), CONSTRAINT CK_NotificationRecipients_Version CHECK(Version>0));
CREATE UNIQUE INDEX UX_NotificationRecipients_LegacyObjectId ON dbo.NotificationRecipients(LegacyObjectId) WHERE LegacyObjectId IS NOT NULL;
INSERT dbo.SchemaVersions(SchemaVersionId,MigrationNumber,MigrationName,ScriptChecksum,AppliedBy) VALUES(NEWID(),7,N'007_CreateVoiceAndIntegrationTables.sql',NULL,ORIGINAL_LOGIN());
COMMIT TRANSACTION;
GO
