using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using TTSmartEcom.Application.Users;
using TTSmartEcom.Domain.Users;

namespace TTSmartEcom.Infrastructure.SqlServer.Users;

#pragma warning disable CA1725, CA1068, CA1859

public sealed class SqlUserProfileRepository(ISqlConnectionFactory factory) : IUserProfileRepository
{
    private static readonly JsonSerializerOptions Json=new(){PropertyNamingPolicy=JsonNamingPolicy.CamelCase,PropertyNameCaseInsensitive=true};
    public async Task<UserProfile?> FindProfileAsync(string userId,CancellationToken ct)=>await FindAsync(userId,ct) is { } x?Profile(x):null;
    public async Task<UserProfile?> UpdateProfileAsync(string userId,string? name,string? email,CancellationToken ct){Row? row=await UpdateAsync(userId,null,x=>x with{Name=name??x.Name,Email=email??x.Email},ct);return row is null?null:Profile(row);}
    public async Task<IReadOnlyList<UserAddress>?> AddAddressAsync(string userId,UserAddress address,CancellationToken ct){Row? row=await MutateAsync(userId,null,x=>x with{Addresses=[..x.Addresses,address with{Id=ValidId(address.Id)?address.Id:SqlPublicIds.New(),Label=address.Label??"Công trình",IsDefault=x.Addresses.Count==0}]},ct);return row?.Addresses;}
    public async Task<IReadOnlyList<UserAddress>?> UpdateAddressAsync(string userId,string addressId,UserAddressPatch patch,CancellationToken ct){bool found=false;Row? row=await MutateAsync(userId,null,x=>{List<UserAddress>a=x.Addresses.ToList();int i=a.FindIndex(z=>z.Id==addressId);if(i<0)return x;found=true;a[i]=a[i] with{Label=patch.Label??a[i].Label,ReceiverName=patch.ReceiverName??a[i].ReceiverName,ReceiverPhone=patch.ReceiverPhone??a[i].ReceiverPhone,AddressDetail=patch.AddressDetail??a[i].AddressDetail};return x with{Addresses=a};},ct);return row is null?null:found?row.Addresses:[];}
    public async Task<IReadOnlyList<UserAddress>?> DeleteAddressAsync(string userId,string addressId,CancellationToken ct){bool found=false;Row? row=await MutateAsync(userId,null,x=>{List<UserAddress>a=x.Addresses.ToList();int i=a.FindIndex(z=>z.Id==addressId);if(i<0)return x;found=true;bool selected=a[i].IsDefault;a.RemoveAt(i);if(selected&&a.Count>0)a[0]=a[0] with{IsDefault=true};return x with{Addresses=a};},ct);return row is null?null:found?row.Addresses:[];}
    public async Task<IReadOnlyList<UserAddress>?> SetDefaultAddressAsync(string userId,string addressId,CancellationToken ct){bool found=false;Row? row=await MutateAsync(userId,null,x=>{if(!x.Addresses.Any(a=>a.Id==addressId))return x;found=true;return x with{Addresses=x.Addresses.Select(a=>a with{IsDefault=a.Id==addressId}).ToArray()};},ct);return row is null?null:found?row.Addresses:[];}
    public async Task<IReadOnlyList<UserOrderTemplate>?> GetOrderTemplatesAsync(string userId,CancellationToken ct)=>(await FindAsync(userId,ct))?.Templates;
    public async Task<UserOrderTemplate?> AddOrderTemplateAsync(string userId,string? displayName,IReadOnlyList<UserTemplateProduct> products,CancellationToken ct){UserOrderTemplate item=new(SqlPublicIds.New(),displayName,string.Empty,products);Row? row=await MutateAsync(userId,null,x=>x with{Templates=[..x.Templates,item]},ct);return row is null?null:item;}
    public async Task<UserOrderTemplate?> UpdateOrderTemplateAsync(string userId,int index,string? displayName,IReadOnlyList<UserTemplateProduct>? products,CancellationToken ct){UserOrderTemplate? result=null;await MutateAsync(userId,null,x=>{if(index<0||index>=x.Templates.Count)return x;List<UserOrderTemplate>a=x.Templates.ToList();result=a[index] with{DisplayName=displayName??a[index].DisplayName,Products=products??a[index].Products};a[index]=result;return x with{Templates=a};},ct);return result;}
    public async Task<bool> DeleteOrderTemplateAsync(string userId,int index,CancellationToken ct){bool result=false;await MutateAsync(userId,null,x=>{if(index<0||index>=x.Templates.Count)return x;List<UserOrderTemplate>a=x.Templates.ToList();a.RemoveAt(index);result=true;return x with{Templates=a};},ct);return result;}
    public async Task<IReadOnlyList<UserSummary>> ListUsersAsync(string viewerRole,bool customersOnly,CancellationToken ct){string[] roles=customersOnly?["customer"]:viewerRole switch{"superadmin"=>["customer","staff","admin","superadmin"],"admin"=>["customer","staff","admin"],"staff"=>["customer","staff"],_=>[]};if(roles.Length==0)return[];await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new($"SELECT PublicId,Email,Phone,Name,Role,FunctionsJson,PermissionsJson,AddressesJson,OrderTemplatesJson,StationIdsJson,Version FROM dbo.Users WHERE IsDeleted=0 AND Role IN ({string.Join(',',roles.Select((_,i)=>"@p"+i))});",c);for(int i=0;i<roles.Length;i++)q.Parameters.AddWithValue("@p"+i,roles[i]);return(await RowsAsync(q,ct)).Select(Summary).ToArray();}
    public async Task<UserSummary?> FindUserSummaryAsync(string userId,CancellationToken ct)=>await FindAsync(userId,ct) is { } x?Summary(x):null;
    public async Task<UserSummary?> FindUserSummaryByPhoneAsync(string phone,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT PublicId,Email,Phone,Name,Role,FunctionsJson,PermissionsJson,AddressesJson,OrderTemplatesJson,StationIdsJson,Version FROM dbo.Users WHERE Phone=@phone AND IsDeleted=0;",c);q.Parameters.AddWithValue("@phone",phone);return(await RowsAsync(q,ct)).FirstOrDefault() is { } x?Summary(x):null;}
    public async Task<bool> HasOtherUserWithRoleAsync(string role,string? excludingUserId,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT COUNT(*) FROM dbo.Users WHERE Role=@role AND IsDeleted=0 AND (@except IS NULL OR PublicId<>@except);",c);q.Parameters.AddWithValue("@role",role);q.Parameters.AddWithValue("@except",(object?)excludingUserId??DBNull.Value);return Convert.ToInt64(await q.ExecuteScalarAsync(ct),System.Globalization.CultureInfo.InvariantCulture)>0;}
    public async Task<UserSummary?> CreateUserAsync(NewUserData user,CancellationToken ct){string id=SqlPublicIds.New();await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("INSERT dbo.Users(UserId,PublicId,Email,Phone,Name,PasswordHash,Role,FunctionsJson,PermissionsJson,AddressesJson,OrderTemplatesJson,StationIdsJson,AutoLoginTokenHash,Version) VALUES(NEWID(),@id,@email,@phone,@name,@hash,@role,N'[]',@permissions,N'[]',N'[]',@stations,@token,0);",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@email",(object?)user.Email??DBNull.Value);q.Parameters.AddWithValue("@phone",user.Phone);q.Parameters.AddWithValue("@name",(object?)user.Name??DBNull.Value);q.Parameters.AddWithValue("@hash",user.PasswordHash);q.Parameters.AddWithValue("@role",user.Role);q.Parameters.AddWithValue("@permissions",JsonSerializer.Serialize(user.Permissions,Json));q.Parameters.AddWithValue("@stations",JsonSerializer.Serialize(user.Stations??[],Json));q.Parameters.AddWithValue("@token",Hash(user.LoginToken));return await q.ExecuteNonQueryAsync(ct)==1?await FindUserSummaryAsync(id,ct):null;}
    public async Task<UserSummary?> UpdateUserAsync(string userId,string expectedRole,UserUpdateData update,CancellationToken ct)=>await UpdateAsync(userId,expectedRole,x=>x with{Name=update.Name??x.Name,Email=update.Email??x.Email,Phone=update.Phone??x.Phone},ct) is { } row?Summary(row):null;
    public async Task<UserSummary?> UpdatePermissionsAsync(string userId,string expectedRole,UserPermissionUpdate update,CancellationToken ct)=>await UpdateAsync(userId,expectedRole,x=>x with{Role=update.Role??x.Role,Permissions=update.Permissions??x.Permissions,Functions=update.Role is null&&update.Permissions is null?x.Functions:[],Name=update.Name??x.Name,Email=update.Email??x.Email,Phone=update.Phone??x.Phone,PasswordHash=update.PasswordHash??x.PasswordHash,TokenHash=update.LoginToken is null?x.TokenHash:Hash(update.LoginToken),PasswordChangedAt=update.PasswordChangedAt??x.PasswordChangedAt},ct) is { } row?Summary(row):null;
    public async Task<string?> RotateAutologinTokenAsync(string userId,string expectedRole,CancellationToken ct){string token=Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();return await UpdateAsync(userId,expectedRole,x=>x with{TokenHash=Hash(token)},ct) is null?null:token;}
    public async Task<UserSummary?> AddStationAsync(string userId,string expectedRole,string stationId,CancellationToken ct)=>await MutateAsync(userId,expectedRole,x=>x.Stations.Contains(stationId,StringComparer.Ordinal)?x:x with{Stations=[..x.Stations,stationId]},ct) is { } row?Summary(row):null;
    public async Task<IReadOnlyList<string>?> ReplaceStationsByPhoneAsync(string phone,string expectedRole,IReadOnlyList<string> stations,CancellationToken ct){UserSummary? user=await FindUserSummaryByPhoneAsync(phone,ct);if(user is null)return null;return await MutateAsync(user.Id,expectedRole,x=>x with{Stations=stations.ToArray()},ct) is null?null:stations.ToArray();}
    public async Task<bool> DeleteUserAsync(string userId,string expectedRole,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE dbo.Users SET IsDeleted=1,Version=Version+1 WHERE PublicId=@id AND Role=@role AND IsDeleted=0;",c);q.Parameters.AddWithValue("@id",userId);q.Parameters.AddWithValue("@role",expectedRole);return await q.ExecuteNonQueryAsync(ct)==1;}
    public async Task<UserPasswordRecord?> FindPasswordAsync(string userId,CancellationToken ct)=>await FindAsync(userId,ct) is {PasswordHash:{Length:>0} hash} x?new UserPasswordRecord(x.Id,hash):null;
    public async Task<bool> ReplacePasswordAsync(string userId,string passwordHash,string loginToken,DateTimeOffset passwordChangedAt,CancellationToken ct)=>await UpdateAsync(userId,null,x=>x with{PasswordHash=passwordHash,TokenHash=Hash(loginToken),PasswordChangedAt=passwordChangedAt},ct) is not null;
    private async Task<Row?> FindAsync(string id,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT PublicId,Email,Phone,Name,Role,FunctionsJson,PermissionsJson,AddressesJson,OrderTemplatesJson,StationIdsJson,Version,PasswordHash,AutoLoginTokenHash,PasswordChangedAtUtc FROM dbo.Users WHERE PublicId=@id AND IsDeleted=0;",c);q.Parameters.AddWithValue("@id",id);return(await RowsAsync(q,ct)).FirstOrDefault();}
    private async Task<Row?> MutateAsync(string id,string? role,Func<Row,Row> mutation,CancellationToken ct){for(int i=0;i<3;i++){Row? source=await FindAsync(id,ct);if(source is null||role is not null&&source.Role!=role)return null;Row desired=mutation(source);if(Equal(source,desired))return desired;Row? saved=await UpdateAsync(id,role,_=>desired,ct,source.Version);if(saved is not null)return saved;}throw new InvalidOperationException("User was changed by another request");}
    private Task<Row?> UpdateAsync(string id,string? role,Func<Row,Row> change,CancellationToken ct)=>UpdateAsync(id,role,change,ct,null);
    private async Task<Row?> UpdateAsync(string id,string? role,Func<Row,Row> change,CancellationToken ct,int? version){Row? source=version is null?await FindAsync(id,ct):await FindAsync(id,ct);if(source is null||role is not null&&source.Role!=role)return null;Row value=change(source);await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE dbo.Users SET Email=@email,Phone=@phone,Name=@name,Role=@role,FunctionsJson=@functions,PermissionsJson=@permissions,AddressesJson=@addresses,OrderTemplatesJson=@templates,StationIdsJson=@stations,PasswordHash=@password,AutoLoginTokenHash=@token,PasswordChangedAtUtc=@changed,Version=Version+1 WHERE PublicId=@id AND Version=@version AND IsDeleted=0;",c);Params(q,id,value);q.Parameters.AddWithValue("@version",version??source.Version);if(await q.ExecuteNonQueryAsync(ct)!=1)return null;return value with{Version=checked(source.Version+1)};}
    private static void Params(SqlCommand q,string id,Row x){q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@email",(object?)x.Email??DBNull.Value);q.Parameters.AddWithValue("@phone",x.Phone);q.Parameters.AddWithValue("@name",(object?)x.Name??DBNull.Value);q.Parameters.AddWithValue("@role",x.Role);q.Parameters.AddWithValue("@functions",JsonSerializer.Serialize(x.Functions,Json));q.Parameters.AddWithValue("@permissions",JsonSerializer.Serialize(x.Permissions,Json));q.Parameters.AddWithValue("@addresses",JsonSerializer.Serialize(x.Addresses,Json));q.Parameters.AddWithValue("@templates",JsonSerializer.Serialize(x.Templates,Json));q.Parameters.AddWithValue("@stations",JsonSerializer.Serialize(x.Stations,Json));q.Parameters.AddWithValue("@password",(object?)x.PasswordHash??DBNull.Value);q.Parameters.AddWithValue("@token",(object?)x.TokenHash??DBNull.Value);q.Parameters.AddWithValue("@changed",(object?)x.PasswordChangedAt?.UtcDateTime??DBNull.Value);}
    private static async Task<List<Row>> RowsAsync(SqlCommand q,CancellationToken ct){List<Row> result=[];await using SqlDataReader r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))result.Add(new(r.GetString(0),r.IsDBNull(1)?null:r.GetString(1),r.IsDBNull(2)?string.Empty:r.GetString(2),r.IsDBNull(3)?null:r.GetString(3),r.IsDBNull(4)?"customer":r.GetString(4),Read<string[]>(r,5)??[],Read<string[]>(r,6)??[],Read<UserAddress[]>(r,7)??[],Read<UserOrderTemplate[]>(r,8)??[],Read<string[]>(r,9)??[],checked((int)r.GetInt64(10)),r.FieldCount>11&&!r.IsDBNull(11)?r.GetString(11):null,r.FieldCount>12&&!r.IsDBNull(12)?r.GetString(12):null,r.FieldCount>13&&!r.IsDBNull(13)?new DateTimeOffset(r.GetDateTime(13),TimeSpan.Zero):null));return result;}
    private static T? Read<T>(SqlDataReader r,int i){try{return r.IsDBNull(i)?default:JsonSerializer.Deserialize<T>(r.GetString(i),Json);}catch(JsonException){return default;}}private static UserProfile Profile(Row x)=>new(x.Id,x.Email,x.Phone,x.Name,x.Role,x.Functions,x.Permissions,x.Stations,x.Addresses,x.Templates);private static UserSummary Summary(Row x)=>new(x.Id,x.Email,x.Phone,x.Name,x.Role,x.Functions,x.Permissions,x.Stations,x.Addresses,x.Templates);private static bool Equal(Row a,Row b)=>a==b;private static bool ValidId(string x)=>x.Length==24&&x.All(Uri.IsHexDigit);private static string Hash(string x)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(x)));private sealed record Row(string Id,string? Email,string Phone,string? Name,string Role,IReadOnlyList<string> Functions,IReadOnlyList<string> Permissions,IReadOnlyList<UserAddress> Addresses,IReadOnlyList<UserOrderTemplate> Templates,IReadOnlyList<string> Stations,int Version,string? PasswordHash,string? TokenHash,DateTimeOffset? PasswordChangedAt);
}
