SET NOCOUNT ON; SET XACT_ABORT ON;
IF DB_NAME() <> N'TTSmart_Operational_V1_Test' THROW 58100,N'Chỉ chạy trên đúng database Operational v1 test.',1;
IF OBJECT_ID(N'dbo.SchemaVersions',N'U') IS NOT NULL
BEGIN
 IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=1 AND ScriptChecksum='$(ScriptChecksum)') RETURN;
 THROW 58101,N'Migration 001 hoặc checksum không khớp.',1;
END;
BEGIN TRANSACTION;
DECLARE @OperationalMigrationLockResult int;
EXEC @OperationalMigrationLockResult = sys.sp_getapplock @Resource=N'TTSmart.Operational.V1.Baseline', @LockMode=N'Exclusive', @LockOwner=N'Transaction', @LockTimeout=60000;
IF @OperationalMigrationLockResult < 0 THROW 58190,N'Không lấy được application lock Operational v1.',1;
IF OBJECT_ID(N'dbo.SchemaVersions',N'U') IS NOT NULL
BEGIN
 IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=1 AND ScriptChecksum='$(ScriptChecksum)') BEGIN COMMIT; RETURN; END;
 THROW 58101,N'Migration 001 hoặc checksum không khớp.',1;
END;
CREATE TABLE dbo.SchemaVersions (SchemaVersionId uniqueidentifier NOT NULL CONSTRAINT PK_SchemaVersions PRIMARY KEY, ModuleCode nvarchar(64) NOT NULL, MigrationNumber int NOT NULL, MigrationName nvarchar(300) NOT NULL, ScriptChecksum char(64) NOT NULL, AppliedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_SchemaVersions_AppliedAtUtc DEFAULT SYSUTCDATETIME(), AppliedBy nvarchar(128) NOT NULL, CONSTRAINT UQ_SchemaVersions_Module_Number UNIQUE(ModuleCode,MigrationNumber), CONSTRAINT CK_SchemaVersions_Number CHECK(MigrationNumber>0), CONSTRAINT CK_SchemaVersions_Checksum CHECK(ScriptChecksum NOT LIKE '%[^0-9A-F]%'));
CREATE TABLE dbo.DatabaseInfo (DatabaseInfoId uniqueidentifier NOT NULL CONSTRAINT PK_DatabaseInfo PRIMARY KEY, SingletonKey tinyint NOT NULL, DatabaseKind nvarchar(30) NOT NULL, CompanyId uniqueidentifier NOT NULL, BranchId uniqueidentifier NULL, DatabaseCode nvarchar(100) NOT NULL, StorageNamespace nvarchar(200) NOT NULL, OperationalRelease nvarchar(100) NOT NULL, CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_DatabaseInfo_CreatedAtUtc DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_DatabaseInfo_UpdatedAtUtc DEFAULT SYSUTCDATETIME(), Version int NOT NULL CONSTRAINT DF_DatabaseInfo_Version DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT UQ_DatabaseInfo_Singleton UNIQUE(SingletonKey), CONSTRAINT UQ_DatabaseInfo_Code UNIQUE(DatabaseCode), CONSTRAINT CK_DatabaseInfo_Singleton CHECK(SingletonKey=1), CONSTRAINT CK_DatabaseInfo_Kind CHECK(DatabaseKind IN(N'TTSmart',N'BranchOnline')), CONSTRAINT CK_DatabaseInfo_Branch CHECK((DatabaseKind=N'TTSmart' AND BranchId IS NULL) OR (DatabaseKind=N'BranchOnline' AND BranchId IS NOT NULL)), CONSTRAINT CK_DatabaseInfo_Namespace CHECK(StorageNamespace<>N'' AND StorageNamespace NOT LIKE N'%:%' AND StorageNamespace NOT LIKE N'%' + NCHAR(92) + N'%' AND StorageNamespace NOT LIKE N'%/%' AND StorageNamespace NOT LIKE N'%..%' AND StorageNamespace NOT LIKE N'%//%'), CONSTRAINT CK_DatabaseInfo_Version CHECK(Version>=0));
CREATE TABLE dbo.MigrationRuns (MigrationRunId uniqueidentifier NOT NULL CONSTRAINT PK_MigrationRuns PRIMARY KEY, SourceSystem nvarchar(100) NOT NULL, SourceDatabase nvarchar(200) NULL, SourceCollection nvarchar(200) NULL, Status nvarchar(20) NOT NULL, StartedAtUtc datetime2(7) NOT NULL, FinishedAtUtc datetime2(7) NULL, Summary nvarchar(1000) NULL, CONSTRAINT CK_MigrationRuns_Status CHECK(Status IN(N'Pending',N'Running',N'Completed',N'Failed')), CONSTRAINT CK_MigrationRuns_Time CHECK(FinishedAtUtc IS NULL OR FinishedAtUtc>=StartedAtUtc));
CREATE TABLE dbo.MigrationMappings (MigrationMappingId uniqueidentifier NOT NULL CONSTRAINT PK_MigrationMappings PRIMARY KEY, MigrationRunId uniqueidentifier NOT NULL, SourceSystem nvarchar(100) NOT NULL, SourceDatabase nvarchar(200) NULL, SourceCollection nvarchar(200) NOT NULL, SourceKey nvarchar(1000) NOT NULL, SourceKeyType nvarchar(40) NOT NULL, SourcePath nvarchar(1000) NOT NULL CONSTRAINT DF_MigrationMappings_Path DEFAULT N'', SourceHash char(64) NULL, MappingFingerprint char(64) COLLATE Latin1_General_100_BIN2 NOT NULL, TargetTable nvarchar(128) NOT NULL, TargetId uniqueidentifier NOT NULL, CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_MigrationMappings_CreatedAtUtc DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_MigrationMappings_Run FOREIGN KEY(MigrationRunId) REFERENCES dbo.MigrationRuns(MigrationRunId), CONSTRAINT UQ_MigrationMappings_Fingerprint UNIQUE(MappingFingerprint), CONSTRAINT CK_MigrationMappings_SourceKey CHECK(LEN(LTRIM(RTRIM(SourceKey)))>0), CONSTRAINT CK_MigrationMappings_SourceKeyType CHECK(SourceKeyType IN(N'ObjectId',N'String',N'DocumentPath',N'SubdocumentPath',N'Generated')), CONSTRAINT CK_MigrationMappings_Hash CHECK(SourceHash IS NULL OR SourceHash NOT LIKE '%[^0-9A-F]%'), CONSTRAINT CK_MigrationMappings_Fingerprint CHECK(MappingFingerprint NOT LIKE '%[^0-9A-F]%'));
CREATE TABLE dbo.LegacyRecords (LegacyRecordId uniqueidentifier NOT NULL CONSTRAINT PK_LegacyRecords PRIMARY KEY, MigrationRunId uniqueidentifier NOT NULL, SourceDatabase nvarchar(200) COLLATE Latin1_General_100_BIN2 NOT NULL, SourceCollection nvarchar(200) COLLATE Latin1_General_100_BIN2 NOT NULL, SourceKey nvarchar(1000) COLLATE Latin1_General_100_BIN2 NOT NULL, SourceKeyType nvarchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL, SourcePath nvarchar(1000) COLLATE Latin1_General_100_BIN2 NOT NULL CONSTRAINT DF_LegacyRecords_Path DEFAULT N'', SourceFingerprint char(64) COLLATE Latin1_General_100_BIN2 NOT NULL, CanonicalExtendedJson nvarchar(max) NOT NULL, ContentSha256 char(64) COLLATE Latin1_General_100_BIN2 NOT NULL, PreservationReason nvarchar(100) NOT NULL, CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_LegacyRecords_Created DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_LegacyRecords_Run FOREIGN KEY(MigrationRunId) REFERENCES dbo.MigrationRuns(MigrationRunId), CONSTRAINT UQ_LegacyRecords_Source UNIQUE(MigrationRunId,SourceFingerprint), CONSTRAINT CK_LegacyRecords_Key CHECK(LEN(LTRIM(RTRIM(SourceKey)))>0), CONSTRAINT CK_LegacyRecords_KeyType CHECK(SourceKeyType IN(N'ObjectId',N'String',N'DocumentPath',N'SubdocumentPath',N'Generated')), CONSTRAINT CK_LegacyRecords_SourceFingerprint CHECK(SourceFingerprint NOT LIKE '%[^0-9A-F]%'), CONSTRAINT CK_LegacyRecords_Hash CHECK(ContentSha256 NOT LIKE '%[^0-9A-F]%'));
CREATE INDEX IX_LegacyRecords_Collection ON dbo.LegacyRecords(MigrationRunId,SourceCollection);
CREATE INDEX IX_MigrationMappings_Target ON dbo.MigrationMappings(TargetTable,TargetId);
CREATE TABLE dbo.MigrationIssues (MigrationIssueId uniqueidentifier NOT NULL CONSTRAINT PK_MigrationIssues PRIMARY KEY, MigrationRunId uniqueidentifier NULL, SourcePath nvarchar(1000) NOT NULL, TargetTable nvarchar(128) NULL, TargetId uniqueidentifier NULL, IssueCode nvarchar(100) NOT NULL, Severity nvarchar(20) NOT NULL, SafeDetail nvarchar(2000) NULL, Status nvarchar(20) NOT NULL CONSTRAINT DF_MigrationIssues_Status DEFAULT N'Open', ResolvedAtUtc datetime2(7) NULL, ResolvedBy nvarchar(128) NULL, CONSTRAINT FK_MigrationIssues_Run FOREIGN KEY(MigrationRunId) REFERENCES dbo.MigrationRuns(MigrationRunId), CONSTRAINT CK_MigrationIssues_Severity CHECK(Severity IN(N'Info',N'Warning',N'Error')), CONSTRAINT CK_MigrationIssues_Status CHECK(Status IN(N'Open',N'Resolved',N'Accepted')));
CREATE TABLE dbo.MigrationManifests (MigrationManifestId uniqueidentifier NOT NULL CONSTRAINT PK_MigrationManifests PRIMARY KEY, MigrationRunId uniqueidentifier NOT NULL, SourceDatabase nvarchar(200) NOT NULL, SourceCollection nvarchar(200) NOT NULL, ManifestVersion nvarchar(50) NOT NULL, ToolVersion nvarchar(100) NOT NULL, DocumentCount bigint NOT NULL, ChildDocumentCount bigint NOT NULL CONSTRAINT DF_MigrationManifests_ChildCount DEFAULT 0, MappedCount bigint NOT NULL CONSTRAINT DF_MigrationManifests_MappedCount DEFAULT 0, BlockedCount bigint NOT NULL CONSTRAINT DF_MigrationManifests_BlockedCount DEFAULT 0, ArchivedCount bigint NOT NULL CONSTRAINT DF_MigrationManifests_ArchivedCount DEFAULT 0, EmptyCount bigint NOT NULL CONSTRAINT DF_MigrationManifests_EmptyCount DEFAULT 0, FileCount bigint NOT NULL CONSTRAINT DF_MigrationManifests_FileCount DEFAULT 0, QuantityTotal decimal(19,6) NULL, AmountTotal decimal(19,4) NULL, ManifestChecksum char(64) COLLATE Latin1_General_100_BIN2 NOT NULL, ProfiledAtUtc datetime2(7) NOT NULL, CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_MigrationManifests_CreatedAtUtc DEFAULT SYSUTCDATETIME(), CONSTRAINT FK_MigrationManifests_Run FOREIGN KEY(MigrationRunId) REFERENCES dbo.MigrationRuns(MigrationRunId), CONSTRAINT UQ_MigrationManifests_Run_Collection UNIQUE(MigrationRunId,SourceDatabase,SourceCollection), CONSTRAINT CK_MigrationManifests_Counts CHECK(DocumentCount>=0 AND ChildDocumentCount>=0 AND MappedCount>=0 AND BlockedCount>=0 AND ArchivedCount>=0 AND EmptyCount>=0 AND FileCount>=0), CONSTRAINT CK_MigrationManifests_Checksum CHECK(ManifestChecksum NOT LIKE '%[^0-9A-F]%'));
CREATE TABLE dbo.NumberSequences (NumberSequenceId uniqueidentifier NOT NULL CONSTRAINT PK_NumberSequences PRIMARY KEY, SequenceCode nvarchar(64) NOT NULL, NextValue bigint NOT NULL, Prefix nvarchar(30) NULL, Version int NOT NULL CONSTRAINT DF_NumberSequences_Version DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT UQ_NumberSequences_Code UNIQUE(SequenceCode), CONSTRAINT CK_NumberSequences_Next CHECK(NextValue>0), CONSTRAINT CK_NumberSequences_Version CHECK(Version>=0));
CREATE ROLE OperationalMigrationWriter AUTHORIZATION dbo;
CREATE ROLE OperationalRuntime AUTHORIZATION dbo;
CREATE ROLE OperationalAuditMaintenance AUTHORIZATION dbo;
EXEC(N'CREATE FUNCTION dbo.IsValidStoragePath(@Value nvarchar(600), @MaximumBytes int)
RETURNS bit
AS
BEGIN
 IF @Value IS NULL OR DATALENGTH(@Value)=0 OR DATALENGTH(@Value)>@MaximumBytes OR LEFT(@Value,1)=N''/'' OR RIGHT(@Value,1)=N''/'' OR CHARINDEX(NCHAR(92),@Value)>0 OR CHARINDEX(N'':'',@Value)>0 OR @Value LIKE N''%//%'' RETURN 0;
 IF EXISTS(SELECT 1 FROM STRING_SPLIT(@Value,N''/'') s WHERE s.value IN(N''.'',N''..'') OR DATALENGTH(s.value)=0 OR DATALENGTH(s.value)<>DATALENGTH(RTRIM(s.value)) OR RIGHT(s.value,1)=N''.'' OR LEN(LTRIM(RTRIM(s.value)))=0 OR UPPER(s.value) IN(N''CON'',N''PRN'',N''AUX'',N''NUL'',N''COM1'',N''COM2'',N''COM3'',N''COM4'',N''COM5'',N''COM6'',N''COM7'',N''COM8'',N''COM9'',N''LPT1'',N''LPT2'',N''LPT3'',N''LPT4'',N''LPT5'',N''LPT6'',N''LPT7'',N''LPT8'',N''LPT9'') OR UPPER(s.value) LIKE N''CON.%'' OR UPPER(s.value) LIKE N''PRN.%'' OR UPPER(s.value) LIKE N''AUX.%'' OR UPPER(s.value) LIKE N''NUL.%'' OR UPPER(s.value) LIKE N''COM[1-9].%'' OR UPPER(s.value) LIKE N''LPT[1-9].%'') RETURN 0;
 RETURN 1;
END;');
ALTER TABLE dbo.DatabaseInfo DROP CONSTRAINT CK_DatabaseInfo_Namespace;
ALTER TABLE dbo.DatabaseInfo ADD CONSTRAINT CK_DatabaseInfo_Namespace CHECK(dbo.IsValidStoragePath(StorageNamespace,400)=1);
ALTER TABLE dbo.MigrationMappings DROP CONSTRAINT CK_MigrationMappings_Hash;
ALTER TABLE dbo.MigrationMappings DROP CONSTRAINT CK_MigrationMappings_SourceKey;
ALTER TABLE dbo.MigrationMappings DROP CONSTRAINT CK_MigrationMappings_SourceKeyType;
ALTER TABLE dbo.MigrationMappings DROP CONSTRAINT DF_MigrationMappings_Path;
DROP INDEX IX_MigrationMappings_Target ON dbo.MigrationMappings;
ALTER TABLE dbo.MigrationMappings ALTER COLUMN SourceSystem nvarchar(100) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE dbo.MigrationMappings ALTER COLUMN SourceDatabase nvarchar(200) COLLATE Latin1_General_100_BIN2 NULL;
ALTER TABLE dbo.MigrationMappings ALTER COLUMN SourceCollection nvarchar(200) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE dbo.MigrationMappings ALTER COLUMN SourceKey nvarchar(1000) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE dbo.MigrationMappings ALTER COLUMN SourceKeyType nvarchar(40) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE dbo.MigrationMappings ALTER COLUMN SourcePath nvarchar(1000) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE dbo.MigrationMappings ALTER COLUMN TargetTable nvarchar(128) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE dbo.MigrationMappings ALTER COLUMN SourceHash char(64) COLLATE Latin1_General_100_BIN2 NULL;
ALTER TABLE dbo.MigrationMappings ADD CONSTRAINT DF_MigrationMappings_Path DEFAULT N'' FOR SourcePath;
ALTER TABLE dbo.MigrationMappings ADD CONSTRAINT CK_MigrationMappings_SourceKey CHECK(LEN(LTRIM(RTRIM(SourceKey)))>0);
ALTER TABLE dbo.MigrationMappings ADD CONSTRAINT CK_MigrationMappings_SourceKeyType CHECK(SourceKeyType IN(N'ObjectId',N'String',N'DocumentPath',N'SubdocumentPath',N'Generated'));
ALTER TABLE dbo.MigrationMappings ADD CONSTRAINT CK_MigrationMappings_Hash CHECK(SourceHash IS NULL OR SourceHash NOT LIKE '%[^0-9A-F]%');
CREATE INDEX IX_MigrationMappings_Target ON dbo.MigrationMappings(TargetTable,TargetId);
INSERT dbo.SchemaVersions(SchemaVersionId,ModuleCode,MigrationNumber,MigrationName,ScriptChecksum,AppliedBy) VALUES(NEWID(),N'Operational',1,N'001_CreateSystemAndMigrationTables.sql','$(ScriptChecksum)',ORIGINAL_LOGIN());
COMMIT;
GO
