SET NOCOUNT ON; SET XACT_ABORT ON;
IF DB_NAME() <> N'TTSmart_Operational_V1_Test' OR NOT EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=4) THROW 58500,N'Thiếu tiền điều kiện.',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=5 AND ScriptChecksum='$(ScriptChecksum)') RETURN;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=5) THROW 58501,N'Checksum không khớp.',1;
BEGIN TRANSACTION;
DECLARE @OperationalMigrationLockResult int;
EXEC @OperationalMigrationLockResult = sys.sp_getapplock @Resource=N'TTSmart.Operational.V1.Baseline', @LockMode=N'Exclusive', @LockOwner=N'Transaction', @LockTimeout=60000;
IF @OperationalMigrationLockResult < 0 THROW 58590,N'Không lấy được application lock Operational v1.',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=5 AND ScriptChecksum='$(ScriptChecksum)') BEGIN COMMIT; RETURN; END;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=5) THROW 58501,N'Checksum không khớp.',1;
CREATE TABLE dbo.Customers (CustomerId uniqueidentifier NOT NULL CONSTRAINT PK_Customers PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, UserId uniqueidentifier NULL, Name nvarchar(200) NOT NULL, Phone nvarchar(32) NULL, NormalizedPhone nvarchar(32) NULL, Email nvarchar(320) NULL, NormalizedEmail nvarchar(320) NULL, DataStatus nvarchar(20) NOT NULL CONSTRAINT DF_Customers_Status DEFAULT N'Valid', Version int NOT NULL CONSTRAINT DF_Customers_Version DEFAULT 0, SourceCreatedAtUtc datetime2(7) NULL, SourceUpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, RowVersion rowversion NOT NULL, CONSTRAINT FK_Customers_User FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId), CONSTRAINT UQ_Customers_PublicId UNIQUE(PublicId), CONSTRAINT CK_Customers_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_Customers_Email_Normalized CHECK((Email IS NULL AND NormalizedEmail IS NULL) OR (Email IS NOT NULL AND NormalizedEmail IS NOT NULL)), CONSTRAINT CK_Customers_Phone_Normalized CHECK((Phone IS NULL AND NormalizedPhone IS NULL) OR (Phone IS NOT NULL AND NormalizedPhone IS NOT NULL)), CONSTRAINT CK_Customers_Status CHECK(DataStatus IN(N'Valid',N'Incomplete',N'Archived')), CONSTRAINT CK_Customers_Version CHECK(Version>=0));
CREATE TABLE dbo.CustomerContacts (CustomerContactId uniqueidentifier NOT NULL CONSTRAINT PK_CustomerContacts PRIMARY KEY, CustomerId uniqueidentifier NOT NULL, ContactType nvarchar(20) NOT NULL, Value nvarchar(320) NOT NULL, IsPrimary bit NOT NULL CONSTRAINT DF_CustomerContacts_Primary DEFAULT 0, CONSTRAINT FK_CustomerContacts_Customer FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(CustomerId), CONSTRAINT CK_CustomerContacts_Type CHECK(ContactType IN(N'Phone',N'Email',N'Other')));
CREATE TABLE dbo.CustomerAddresses (CustomerAddressId uniqueidentifier NOT NULL CONSTRAINT PK_CustomerAddresses PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, CustomerId uniqueidentifier NOT NULL, Label nvarchar(100) NULL, ReceiverName nvarchar(200) NOT NULL, ReceiverPhone nvarchar(32) NULL, AddressDetail nvarchar(1000) NOT NULL, IsDefault bit NOT NULL CONSTRAINT DF_CustomerAddresses_Default DEFAULT 0, Version int NOT NULL CONSTRAINT DF_CustomerAddresses_Version DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_CustomerAddresses_Customer FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(CustomerId), CONSTRAINT UQ_CustomerAddresses_PublicId UNIQUE(PublicId), CONSTRAINT CK_CustomerAddresses_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_CustomerAddresses_Version CHECK(Version>=0));
CREATE TABLE dbo.Carts (CartId uniqueidentifier NOT NULL CONSTRAINT PK_Carts PRIMARY KEY, UserId uniqueidentifier NOT NULL, Version int NOT NULL CONSTRAINT DF_Carts_Version DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_Carts_User FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId), CONSTRAINT UQ_Carts_User UNIQUE(UserId), CONSTRAINT CK_Carts_Version CHECK(Version>=0));
CREATE TABLE dbo.CartItems (CartItemId uniqueidentifier NOT NULL CONSTRAINT PK_CartItems PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, CartId uniqueidentifier NOT NULL, ProductId uniqueidentifier NOT NULL, ProductVariantId uniqueidentifier NULL, Quantity decimal(19,6) NOT NULL, IsSelected bit NOT NULL CONSTRAINT DF_CartItems_Selected DEFAULT 1, SortOrder int NOT NULL CONSTRAINT DF_CartItems_Sort DEFAULT 0, Version int NOT NULL CONSTRAINT DF_CartItems_Version DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_CartItems_Cart FOREIGN KEY(CartId) REFERENCES dbo.Carts(CartId), CONSTRAINT FK_CartItems_Product FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT FK_CartItems_ProductVariant FOREIGN KEY(ProductId,ProductVariantId) REFERENCES dbo.ProductVariants(ProductId,ProductVariantId), CONSTRAINT UQ_CartItems_PublicId UNIQUE(PublicId), CONSTRAINT CK_CartItems_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_CartItems_Quantity CHECK(Quantity>0), CONSTRAINT CK_CartItems_Version CHECK(Version>=0));
CREATE TABLE dbo.OrderTemplates (OrderTemplateId uniqueidentifier NOT NULL CONSTRAINT PK_OrderTemplates PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, UserId uniqueidentifier NOT NULL, DisplayName nvarchar(200) NOT NULL, Note nvarchar(2000) NULL, SortOrder int NOT NULL CONSTRAINT DF_OrderTemplates_Sort DEFAULT 0, Version int NOT NULL CONSTRAINT DF_OrderTemplates_Version DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_OrderTemplates_User FOREIGN KEY(UserId) REFERENCES dbo.Users(UserId), CONSTRAINT UQ_OrderTemplates_PublicId UNIQUE(PublicId), CONSTRAINT CK_OrderTemplates_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_OrderTemplates_Version CHECK(Version>=0));
CREATE TABLE dbo.OrderTemplateItems (OrderTemplateItemId uniqueidentifier NOT NULL CONSTRAINT PK_OrderTemplateItems PRIMARY KEY, OrderTemplateId uniqueidentifier NOT NULL, ProductId uniqueidentifier NOT NULL, ProductVariantId uniqueidentifier NULL, Quantity decimal(19,6) NOT NULL, SortOrder int NOT NULL CONSTRAINT DF_OrderTemplateItems_Sort DEFAULT 0, CONSTRAINT FK_OrderTemplateItems_Template FOREIGN KEY(OrderTemplateId) REFERENCES dbo.OrderTemplates(OrderTemplateId), CONSTRAINT FK_OrderTemplateItems_Product FOREIGN KEY(ProductId) REFERENCES dbo.Products(ProductId), CONSTRAINT FK_OrderTemplateItems_ProductVariant FOREIGN KEY(ProductId,ProductVariantId) REFERENCES dbo.ProductVariants(ProductId,ProductVariantId), CONSTRAINT CK_OrderTemplateItems_Quantity CHECK(Quantity>0));
INSERT dbo.SchemaVersions SELECT NEWID(),N'Operational',5,N'005_CreateCustomerCartAndTemplateTables.sql','$(ScriptChecksum)',SYSUTCDATETIME(),ORIGINAL_LOGIN(); COMMIT;
GO
