SET NOCOUNT ON; SET XACT_ABORT ON;
IF DB_NAME() <> N'TTSmart_Operational_V1_Test' OR NOT EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=5) THROW 58600,N'Thiếu tiền điều kiện.',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=6 AND ScriptChecksum='$(ScriptChecksum)') RETURN;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=6) THROW 58601,N'Checksum không khớp.',1;
BEGIN TRANSACTION;
DECLARE @OperationalMigrationLockResult int;
EXEC @OperationalMigrationLockResult = sys.sp_getapplock @Resource=N'TTSmart.Operational.V1.Baseline', @LockMode=N'Exclusive', @LockOwner=N'Transaction', @LockTimeout=60000;
IF @OperationalMigrationLockResult < 0 THROW 58690,N'Không lấy được application lock Operational v1.',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=6 AND ScriptChecksum='$(ScriptChecksum)') BEGIN COMMIT; RETURN; END;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=6) THROW 58601,N'Checksum không khớp.',1;
CREATE TABLE dbo.SalesOrders (SalesOrderId uniqueidentifier NOT NULL CONSTRAINT PK_SalesOrders PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, CustomerId uniqueidentifier NULL, CustomerNameSnapshot nvarchar(200) NULL, CustomerPhoneSnapshot nvarchar(32) NULL, CustomerAddressSnapshot nvarchar(1000) NULL, OrderCode nvarchar(50) NULL, PaymentMethod nvarchar(100) NULL, Status nvarchar(30) NOT NULL, State nvarchar(30) NULL, PaidState nvarchar(30) NULL, Total decimal(19,4) NULL, LegacyTotalRaw nvarchar(100) NULL, ExtraJson nvarchar(max) NULL, RecordOrigin nvarchar(20) NOT NULL CONSTRAINT DF_SalesOrders_Origin DEFAULT N'Sql', DataStatus nvarchar(20) NOT NULL CONSTRAINT DF_SalesOrders_Status DEFAULT N'Valid', Version int NOT NULL CONSTRAINT DF_SalesOrders_Version DEFAULT 0, SourceCreatedAtUtc datetime2(7) NULL, SourceUpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, CompletedAtUtc datetime2(7) NULL, RowVersion rowversion NOT NULL, CONSTRAINT FK_SalesOrders_Customer FOREIGN KEY(CustomerId) REFERENCES dbo.Customers(CustomerId), CONSTRAINT UQ_SalesOrders_PublicId UNIQUE(PublicId), CONSTRAINT CK_SalesOrders_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_SalesOrders_Origin CHECK(RecordOrigin IN(N'Legacy',N'Sql')), CONSTRAINT CK_SalesOrders_DataStatus CHECK(DataStatus IN(N'Valid',N'Incomplete',N'Orphan',N'Archived')), CONSTRAINT CK_SalesOrders_NewSnapshot CHECK(RecordOrigin=N'Legacy' OR (CustomerNameSnapshot IS NOT NULL AND CustomerPhoneSnapshot IS NOT NULL)), CONSTRAINT CK_SalesOrders_Version CHECK(Version>=0));
CREATE TABLE dbo.SalesOrderItems (SalesOrderItemId uniqueidentifier NOT NULL CONSTRAINT PK_SalesOrderItems PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, SalesOrderId uniqueidentifier NOT NULL, ProductId uniqueidentifier NULL, ProductVariantId uniqueidentifier NULL, LegacyProductObjectId char(24) NULL, LegacyVariantIndex int NULL, ProductName nvarchar(300) NULL, ProductCode nvarchar(120) NULL, VariantPublicId char(24) COLLATE Latin1_General_100_BIN2 NULL, VariantPosition int NULL, Quantity decimal(19,6) NOT NULL, UnitPrice decimal(19,4) NULL, UnitPriceRaw nvarchar(100) NULL, LineTotal decimal(19,4) NULL, LineTotalRaw nvarchar(100) NULL, VatRate decimal(19,4) NULL, VatRateRaw nvarchar(100) NULL, LineNote nvarchar(2000) NULL, SortOrder int NOT NULL CONSTRAINT DF_SalesOrderItems_Sort DEFAULT 0, RecordOrigin nvarchar(20) NOT NULL CONSTRAINT DF_SalesOrderItems_Origin DEFAULT N'Sql', DataStatus nvarchar(20) NOT NULL CONSTRAINT DF_SalesOrderItems_Status DEFAULT N'Valid', Version int NOT NULL CONSTRAINT DF_SalesOrderItems_Version DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_SalesOrderItems_Order FOREIGN KEY(SalesOrderId) REFERENCES dbo.SalesOrders(SalesOrderId), CONSTRAINT FK_SalesOrderItems_ProductVariant FOREIGN KEY(ProductId,ProductVariantId) REFERENCES dbo.ProductVariants(ProductId,ProductVariantId), CONSTRAINT UQ_SalesOrderItems_PublicId UNIQUE(PublicId), CONSTRAINT CK_SalesOrderItems_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_SalesOrderItems_Origin CHECK(RecordOrigin IN(N'Legacy',N'Sql')), CONSTRAINT CK_SalesOrderItems_Status CHECK(DataStatus IN(N'Valid',N'Orphan',N'Incomplete',N'Archived')), CONSTRAINT CK_SalesOrderItems_Reference CHECK(((ProductId IS NOT NULL AND ProductVariantId IS NOT NULL) OR (ProductId IS NULL AND ProductVariantId IS NULL AND LegacyProductObjectId IS NOT NULL)) AND NOT (ProductId IS NULL AND DataStatus=N'Valid')), CONSTRAINT CK_SalesOrderItems_Quantity CHECK(Quantity>0), CONSTRAINT CK_SalesOrderItems_NewSnapshot CHECK(RecordOrigin=N'Legacy' OR (ProductName IS NOT NULL AND (VariantPublicId IS NOT NULL OR VariantPosition IS NOT NULL) AND UnitPrice IS NOT NULL AND LineTotal IS NOT NULL)), CONSTRAINT CK_SalesOrderItems_Version CHECK(Version>=0));
CREATE TABLE dbo.SalesOrderFiles (SalesOrderFileId uniqueidentifier NOT NULL CONSTRAINT PK_SalesOrderFiles PRIMARY KEY, SalesOrderId uniqueidentifier NOT NULL, FileId uniqueidentifier NULL, ExternalUrl nvarchar(2000) NULL, Label nvarchar(300) NULL, FileType nvarchar(50) NULL, SortOrder int NOT NULL CONSTRAINT DF_SalesOrderFiles_Sort DEFAULT 0, CONSTRAINT FK_SalesOrderFiles_Order FOREIGN KEY(SalesOrderId) REFERENCES dbo.SalesOrders(SalesOrderId), CONSTRAINT FK_SalesOrderFiles_File FOREIGN KEY(FileId) REFERENCES dbo.Files(FileId), CONSTRAINT CK_SalesOrderFiles_Reference CHECK((FileId IS NULL AND ExternalUrl IS NOT NULL) OR (FileId IS NOT NULL AND ExternalUrl IS NULL)));
CREATE TABLE dbo.SalesOrderStatusHistory (SalesOrderStatusHistoryId uniqueidentifier NOT NULL CONSTRAINT PK_SalesOrderStatusHistory PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, SalesOrderId uniqueidentifier NOT NULL, Status nvarchar(30) NOT NULL, OccurredAtUtc datetime2(7) NOT NULL, CONSTRAINT FK_SalesOrderStatusHistory_Order FOREIGN KEY(SalesOrderId) REFERENCES dbo.SalesOrders(SalesOrderId), CONSTRAINT UQ_SalesOrderStatusHistory_PublicId UNIQUE(PublicId), CONSTRAINT CK_SalesOrderStatusHistory_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24));
EXEC(N'CREATE TRIGGER dbo.TR_SalesOrderItems_Origin ON dbo.SalesOrderItems AFTER INSERT, UPDATE AS
BEGIN
 SET NOCOUNT ON;
 IF EXISTS(SELECT 1 FROM inserted i JOIN deleted d ON d.SalesOrderItemId=i.SalesOrderItemId WHERE i.RecordOrigin<>d.RecordOrigin)
 BEGIN ROLLBACK TRANSACTION; THROW 58693,N''Không được đổi nguồn gốc item đơn hàng.'',1; END;
 IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.SalesOrders h ON h.SalesOrderId=i.SalesOrderId WHERE i.RecordOrigin<>h.RecordOrigin OR (i.RecordOrigin=N''Sql'' AND i.DataStatus<>N''Valid''))
 BEGIN ROLLBACK TRANSACTION; THROW 58691,N''Nguồn gốc item đơn hàng không khớp header hoặc snapshot SQL.'',1; END;
 IF EXISTS(SELECT 1 FROM inserted WHERE RecordOrigin=N''Legacy'') AND IS_MEMBER(N''OperationalMigrationWriter'')<>1 AND USER_NAME()<>N''dbo''
 BEGIN ROLLBACK TRANSACTION; THROW 58692,N''Chỉ vai trò migration được ghi SalesOrder Legacy.'',1; END;
END;');
EXEC(N'CREATE TRIGGER dbo.TR_SalesOrders_Origin ON dbo.SalesOrders AFTER INSERT, UPDATE AS
BEGIN
 SET NOCOUNT ON;
 IF EXISTS(SELECT 1 FROM inserted i JOIN deleted d ON d.SalesOrderId=i.SalesOrderId WHERE i.RecordOrigin<>d.RecordOrigin)
 BEGIN ROLLBACK TRANSACTION; THROW 58694,N''Không được đổi nguồn gốc đơn hàng.'',1; END;
 IF EXISTS(SELECT 1 FROM inserted WHERE RecordOrigin=N''Legacy'') AND IS_MEMBER(N''OperationalMigrationWriter'')<>1 AND USER_NAME()<>N''dbo''
 BEGIN ROLLBACK TRANSACTION; THROW 58695,N''Chỉ vai trò migration được ghi SalesOrder Legacy.'',1; END;
END;');
INSERT dbo.SchemaVersions SELECT NEWID(),N'Operational',6,N'006_CreateSalesTables.sql','$(ScriptChecksum)',SYSUTCDATETIME(),ORIGINAL_LOGIN(); COMMIT;
GO
