SET NOCOUNT ON; SET XACT_ABORT ON;
IF DB_NAME() <> N'TTSmart_Operational_V1_Test' OR NOT EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=6) THROW 58700,N'Thiếu tiền điều kiện.',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=7 AND ScriptChecksum='$(ScriptChecksum)') RETURN;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=7) THROW 58701,N'Checksum không khớp.',1;
BEGIN TRANSACTION;
DECLARE @OperationalMigrationLockResult int;
EXEC @OperationalMigrationLockResult=sys.sp_getapplock @Resource=N'TTSmart.Operational.V1.Baseline',@LockMode=N'Exclusive',@LockOwner=N'Transaction',@LockTimeout=60000;
IF @OperationalMigrationLockResult<0 THROW 58790,N'Không lấy được application lock Operational v1.',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=7 AND ScriptChecksum='$(ScriptChecksum)') BEGIN COMMIT; RETURN; END;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Operational' AND MigrationNumber=7) THROW 58701,N'Checksum không khớp.',1;
CREATE TABLE dbo.Stocks (StockId uniqueidentifier NOT NULL CONSTRAINT PK_Stocks PRIMARY KEY, ProductVariantId uniqueidentifier NOT NULL, QuantityForSale decimal(19,6) NOT NULL CONSTRAINT DF_Stocks_ForSale DEFAULT 0, QuantityInStorage decimal(19,6) NOT NULL CONSTRAINT DF_Stocks_Storage DEFAULT 0, Version int NOT NULL CONSTRAINT DF_Stocks_Version DEFAULT 0, UpdatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_Stocks_Updated DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL, CONSTRAINT FK_Stocks_Variant FOREIGN KEY(ProductVariantId) REFERENCES dbo.ProductVariants(ProductVariantId), CONSTRAINT UQ_Stocks_Variant UNIQUE(ProductVariantId), CONSTRAINT CK_Stocks_Quantity CHECK(QuantityForSale>=0 AND QuantityInStorage>=0), CONSTRAINT CK_Stocks_Version CHECK(Version>=0));
CREATE TABLE dbo.StockOperations (StockOperationId uniqueidentifier NOT NULL CONSTRAINT PK_StockOperations PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, IdempotencyKey nvarchar(128) NOT NULL, OperationType nvarchar(30) NOT NULL, SourceType nvarchar(30) NULL, SourceId uniqueidentifier NULL, ReversalOfOperationId uniqueidentifier NULL, ActorUserId uniqueidentifier NULL, Note nvarchar(2000) NULL, OccurredAtUtc datetime2(7) NOT NULL, Version int NOT NULL CONSTRAINT DF_StockOperations_Version DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT FK_StockOperations_Reversal FOREIGN KEY(ReversalOfOperationId) REFERENCES dbo.StockOperations(StockOperationId), CONSTRAINT FK_StockOperations_Actor FOREIGN KEY(ActorUserId) REFERENCES dbo.Users(UserId), CONSTRAINT UQ_StockOperations_PublicId UNIQUE(PublicId), CONSTRAINT UQ_StockOperations_Idempotency UNIQUE(IdempotencyKey), CONSTRAINT CK_StockOperations_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_StockOperations_Type CHECK(OperationType IN(N'Import',N'Export',N'Adjustment',N'Sale',N'Return',N'Reversal')), CONSTRAINT CK_StockOperations_Reversal CHECK((OperationType=N'Reversal' AND ReversalOfOperationId IS NOT NULL AND ReversalOfOperationId<>StockOperationId) OR (OperationType<>N'Reversal' AND ReversalOfOperationId IS NULL)), CONSTRAINT CK_StockOperations_Version CHECK(Version>=0));
CREATE UNIQUE INDEX UX_StockOperations_OneReversal ON dbo.StockOperations(ReversalOfOperationId) WHERE ReversalOfOperationId IS NOT NULL;
CREATE TABLE dbo.StockMovementLines (StockMovementLineId uniqueidentifier NOT NULL CONSTRAINT PK_StockMovementLines PRIMARY KEY, StockOperationId uniqueidentifier NOT NULL, ProductVariantId uniqueidentifier NOT NULL, QuantityForSaleChange decimal(19,6) NOT NULL, QuantityInStorageChange decimal(19,6) NOT NULL, PurchaseCountChange decimal(19,6) NOT NULL CONSTRAINT DF_StockMovementLines_Purchase DEFAULT 0, CONSTRAINT FK_StockMovementLines_Operation FOREIGN KEY(StockOperationId) REFERENCES dbo.StockOperations(StockOperationId), CONSTRAINT FK_StockMovementLines_Variant FOREIGN KEY(ProductVariantId) REFERENCES dbo.ProductVariants(ProductVariantId), CONSTRAINT UQ_StockMovementLines_Operation_Variant UNIQUE(StockOperationId,ProductVariantId));
CREATE TABLE dbo.ImportOrders (ImportOrderId uniqueidentifier NOT NULL CONSTRAINT PK_ImportOrders PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, OrderCode nvarchar(50) NULL, OrderName nvarchar(300) NULL, ActorName nvarchar(200) NULL, Note nvarchar(2000) NULL, Total decimal(19,4) NULL, LegacyTotalRaw nvarchar(100) NULL, Status nvarchar(30) NOT NULL CONSTRAINT DF_ImportOrders_Status DEFAULT N'Pending', RecordOrigin nvarchar(20) NOT NULL CONSTRAINT DF_ImportOrders_Origin DEFAULT N'Sql', DataStatus nvarchar(20) NOT NULL CONSTRAINT DF_ImportOrders_DataStatus DEFAULT N'Valid', SourceCreatedAtUtc datetime2(7) NULL, SourceUpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, CompletedAtUtc datetime2(7) NULL, Version int NOT NULL CONSTRAINT DF_ImportOrders_Version DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT UQ_ImportOrders_PublicId UNIQUE(PublicId), CONSTRAINT CK_ImportOrders_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_ImportOrders_Status CHECK(Status IN(N'Pending',N'Completed',N'Cancelled')), CONSTRAINT CK_ImportOrders_Origin CHECK(RecordOrigin IN(N'Legacy',N'Sql')), CONSTRAINT CK_ImportOrders_DataStatus CHECK(DataStatus IN(N'Valid',N'Incomplete',N'Orphan',N'Archived')), CONSTRAINT CK_ImportOrders_Completed CHECK(Status<>N'Completed' OR CompletedAtUtc IS NOT NULL OR (RecordOrigin=N'Legacy' AND DataStatus=N'Incomplete')), CONSTRAINT CK_ImportOrders_Version CHECK(Version>=0));
CREATE TABLE dbo.ImportOrderItems (ImportOrderItemId uniqueidentifier NOT NULL CONSTRAINT PK_ImportOrderItems PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, ImportOrderId uniqueidentifier NOT NULL, ProductId uniqueidentifier NULL, ProductVariantId uniqueidentifier NULL, LegacyProductObjectId char(24) NULL, LegacyVariantIndex int NULL, UnitSnapshot nvarchar(100) NULL, QuantityRaw nvarchar(100) NULL, QuantityRe decimal(19,6) NULL, ReceivedQuantity decimal(19,6) NULL, AppliedQuantity decimal(19,6) NULL, StockAppliedQuantity decimal(19,6) NULL, UnitPrice decimal(19,4) NULL, UnitPriceRaw nvarchar(100) NULL, ImportPriceSnapshot decimal(19,4) NULL, ImportPriceSnapshotRaw nvarchar(100) NULL, VatRate decimal(19,4) NULL, VatRateRaw nvarchar(100) NULL, ProfitPercent decimal(19,4) NULL, Note nvarchar(2000) NULL, LineStatus nvarchar(30) NULL, SortOrder int NOT NULL CONSTRAINT DF_ImportOrderItems_Sort DEFAULT 0, StockUpdateSkipped bit NOT NULL CONSTRAINT DF_ImportOrderItems_SkipStock DEFAULT 0, RecordOrigin nvarchar(20) NOT NULL CONSTRAINT DF_ImportOrderItems_Origin DEFAULT N'Sql', LegacyStatus bit NULL, DataStatus nvarchar(20) NOT NULL CONSTRAINT DF_ImportOrderItems_Status DEFAULT N'Valid', CONSTRAINT FK_ImportOrderItems_Order FOREIGN KEY(ImportOrderId) REFERENCES dbo.ImportOrders(ImportOrderId), CONSTRAINT FK_ImportOrderItems_ProductVariant FOREIGN KEY(ProductId,ProductVariantId) REFERENCES dbo.ProductVariants(ProductId,ProductVariantId), CONSTRAINT UQ_ImportOrderItems_PublicId UNIQUE(PublicId), CONSTRAINT CK_ImportOrderItems_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_ImportOrderItems_Origin CHECK(RecordOrigin IN(N'Legacy',N'Sql')), CONSTRAINT CK_ImportOrderItems_Status CHECK(DataStatus IN(N'Valid',N'Orphan',N'Incomplete',N'Archived')), CONSTRAINT CK_ImportOrderItems_Reference CHECK(((ProductId IS NOT NULL AND ProductVariantId IS NOT NULL) OR (ProductId IS NULL AND ProductVariantId IS NULL AND LegacyProductObjectId IS NOT NULL)) AND NOT(ProductId IS NULL AND DataStatus=N'Valid')), CONSTRAINT CK_ImportOrderItems_Quantities CHECK((ReceivedQuantity IS NOT NULL AND AppliedQuantity IS NOT NULL AND StockAppliedQuantity IS NOT NULL AND ReceivedQuantity>=0 AND AppliedQuantity>=0 AND StockAppliedQuantity>=0 AND AppliedQuantity<=ReceivedQuantity AND StockAppliedQuantity<=ReceivedQuantity AND (QuantityRe IS NULL OR QuantityRe BETWEEN 0 AND ReceivedQuantity)) OR (RecordOrigin=N'Legacy' AND DataStatus=N'Incomplete' AND ReceivedQuantity IS NULL AND AppliedQuantity IS NULL AND StockAppliedQuantity IS NULL)));
CREATE TABLE dbo.ImportOrderFiles (ImportOrderFileId uniqueidentifier NOT NULL CONSTRAINT PK_ImportOrderFiles PRIMARY KEY, ImportOrderId uniqueidentifier NOT NULL, FileId uniqueidentifier NULL, ExternalUrl nvarchar(2000) NULL, SortOrder int NOT NULL CONSTRAINT DF_ImportOrderFiles_Sort DEFAULT 0, CONSTRAINT FK_ImportOrderFiles_Order FOREIGN KEY(ImportOrderId) REFERENCES dbo.ImportOrders(ImportOrderId), CONSTRAINT FK_ImportOrderFiles_File FOREIGN KEY(FileId) REFERENCES dbo.Files(FileId), CONSTRAINT CK_ImportOrderFiles_Reference CHECK((FileId IS NULL AND ExternalUrl IS NOT NULL) OR (FileId IS NOT NULL AND ExternalUrl IS NULL)));
CREATE TABLE dbo.ExportOrders (ExportOrderId uniqueidentifier NOT NULL CONSTRAINT PK_ExportOrders PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, OrderCode nvarchar(50) NULL, OrderName nvarchar(300) NULL, ActorName nvarchar(200) NULL, Note nvarchar(2000) NULL, Total decimal(19,4) NULL, LegacyTotalRaw nvarchar(100) NULL, Status nvarchar(30) NOT NULL CONSTRAINT DF_ExportOrders_Status DEFAULT N'Pending', RecordOrigin nvarchar(20) NOT NULL CONSTRAINT DF_ExportOrders_Origin DEFAULT N'Sql', DataStatus nvarchar(20) NOT NULL CONSTRAINT DF_ExportOrders_DataStatus DEFAULT N'Valid', SourceCreatedAtUtc datetime2(7) NULL, SourceUpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NULL, CreatedAtUtc datetime2(7) NULL, UpdatedAtUtc datetime2(7) NULL, CompletedAtUtc datetime2(7) NULL, Version int NOT NULL CONSTRAINT DF_ExportOrders_Version DEFAULT 0, RowVersion rowversion NOT NULL, CONSTRAINT UQ_ExportOrders_PublicId UNIQUE(PublicId), CONSTRAINT CK_ExportOrders_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_ExportOrders_Status CHECK(Status IN(N'Pending',N'Completed',N'Cancelled')), CONSTRAINT CK_ExportOrders_Origin CHECK(RecordOrigin IN(N'Legacy',N'Sql')), CONSTRAINT CK_ExportOrders_DataStatus CHECK(DataStatus IN(N'Valid',N'Incomplete',N'Orphan',N'Archived')), CONSTRAINT CK_ExportOrders_Completed CHECK(Status<>N'Completed' OR CompletedAtUtc IS NOT NULL OR (RecordOrigin=N'Legacy' AND DataStatus=N'Incomplete')), CONSTRAINT CK_ExportOrders_Version CHECK(Version>=0));
CREATE TABLE dbo.ExportOrderItems (ExportOrderItemId uniqueidentifier NOT NULL CONSTRAINT PK_ExportOrderItems PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, ExportOrderId uniqueidentifier NOT NULL, ProductId uniqueidentifier NULL, ProductVariantId uniqueidentifier NULL, LegacyProductObjectId char(24) NULL, LegacyVariantIndex int NULL, UnitSnapshot nvarchar(100) NULL, QuantityRaw nvarchar(100) NULL, QuantityEx decimal(19,6) NULL, ExportedQuantity decimal(19,6) NULL, AppliedQuantity decimal(19,6) NULL, StockAppliedQuantity decimal(19,6) NULL, UnitPrice decimal(19,4) NULL, UnitPriceRaw nvarchar(100) NULL, ImportPriceSnapshot decimal(19,4) NULL, ImportPriceSnapshotRaw nvarchar(100) NULL, VatRate decimal(19,4) NULL, VatRateRaw nvarchar(100) NULL, ProfitPercent decimal(19,4) NULL, Note nvarchar(2000) NULL, LineStatus nvarchar(30) NULL, SortOrder int NOT NULL CONSTRAINT DF_ExportOrderItems_Sort DEFAULT 0, StockUpdateSkipped bit NOT NULL CONSTRAINT DF_ExportOrderItems_SkipStock DEFAULT 0, RecordOrigin nvarchar(20) NOT NULL CONSTRAINT DF_ExportOrderItems_Origin DEFAULT N'Sql', LegacyStatus bit NULL, DataStatus nvarchar(20) NOT NULL CONSTRAINT DF_ExportOrderItems_Status DEFAULT N'Valid', CONSTRAINT FK_ExportOrderItems_Order FOREIGN KEY(ExportOrderId) REFERENCES dbo.ExportOrders(ExportOrderId), CONSTRAINT FK_ExportOrderItems_ProductVariant FOREIGN KEY(ProductId,ProductVariantId) REFERENCES dbo.ProductVariants(ProductId,ProductVariantId), CONSTRAINT UQ_ExportOrderItems_PublicId UNIQUE(PublicId), CONSTRAINT CK_ExportOrderItems_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_ExportOrderItems_Origin CHECK(RecordOrigin IN(N'Legacy',N'Sql')), CONSTRAINT CK_ExportOrderItems_Status CHECK(DataStatus IN(N'Valid',N'Orphan',N'Incomplete',N'Archived')), CONSTRAINT CK_ExportOrderItems_Reference CHECK(((ProductId IS NOT NULL AND ProductVariantId IS NOT NULL) OR (ProductId IS NULL AND ProductVariantId IS NULL AND LegacyProductObjectId IS NOT NULL)) AND NOT(ProductId IS NULL AND DataStatus=N'Valid')), CONSTRAINT CK_ExportOrderItems_Quantities CHECK((ExportedQuantity IS NOT NULL AND AppliedQuantity IS NOT NULL AND StockAppliedQuantity IS NOT NULL AND ExportedQuantity>=0 AND AppliedQuantity>=0 AND StockAppliedQuantity>=0 AND AppliedQuantity<=ExportedQuantity AND StockAppliedQuantity<=ExportedQuantity AND (QuantityEx IS NULL OR QuantityEx BETWEEN 0 AND ExportedQuantity)) OR (RecordOrigin=N'Legacy' AND DataStatus=N'Incomplete' AND ExportedQuantity IS NULL AND AppliedQuantity IS NULL AND StockAppliedQuantity IS NULL)));
CREATE TABLE dbo.ExportOrderFiles (ExportOrderFileId uniqueidentifier NOT NULL CONSTRAINT PK_ExportOrderFiles PRIMARY KEY, ExportOrderId uniqueidentifier NOT NULL, FileId uniqueidentifier NULL, ExternalUrl nvarchar(2000) NULL, SortOrder int NOT NULL CONSTRAINT DF_ExportOrderFiles_Sort DEFAULT 0, CONSTRAINT FK_ExportOrderFiles_Order FOREIGN KEY(ExportOrderId) REFERENCES dbo.ExportOrders(ExportOrderId), CONSTRAINT FK_ExportOrderFiles_File FOREIGN KEY(FileId) REFERENCES dbo.Files(FileId), CONSTRAINT CK_ExportOrderFiles_Reference CHECK((FileId IS NULL AND ExternalUrl IS NOT NULL) OR (FileId IS NOT NULL AND ExternalUrl IS NULL)));
CREATE TABLE dbo.LegacyStockHistories (LegacyStockHistoryId uniqueidentifier NOT NULL CONSTRAINT PK_LegacyStockHistories PRIMARY KEY, PublicId char(24) COLLATE Latin1_General_100_BIN2 NOT NULL, LegacyProductObjectId char(24) NULL, LegacyUserObjectId char(24) NULL, LegacyOrderObjectId char(24) NULL, ProductName nvarchar(300) NULL, UserName nvarchar(200) NULL, OrderName nvarchar(300) NULL, Note nvarchar(2000) NULL, SourceType nvarchar(100) NULL, IsAiScan bit NULL, AiReference nvarchar(300) NULL, Quantity decimal(19,6) NOT NULL, SourceVersion int NULL, IssueFlags int NOT NULL CONSTRAINT DF_LegacyStockHistories_Issues DEFAULT 0, DataStatus nvarchar(20) NOT NULL CONSTRAINT DF_LegacyStockHistories_Status DEFAULT N'Archived', SourceCreatedAtUtc datetime2(7) NULL, SourceUpdatedAtUtc datetime2(7) NULL, MigratedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_LegacyStockHistories_Migrated DEFAULT SYSUTCDATETIME(), CONSTRAINT UQ_LegacyStockHistories_PublicId UNIQUE(PublicId), CONSTRAINT CK_LegacyStockHistories_PublicId CHECK(PublicId NOT LIKE '%[^0-9a-f]%' AND LEN(PublicId)=24), CONSTRAINT CK_LegacyStockHistories_Status CHECK(DataStatus IN(N'Archived',N'Orphan',N'Incomplete')));
ALTER TABLE dbo.StockMovementLines DROP CONSTRAINT DF_StockMovementLines_Purchase;
ALTER TABLE dbo.StockMovementLines ALTER COLUMN PurchaseCountChange bigint NOT NULL;
ALTER TABLE dbo.StockMovementLines ADD CONSTRAINT DF_StockMovementLines_Purchase DEFAULT 0 FOR PurchaseCountChange;
ALTER TABLE dbo.LegacyStockHistories ADD LegacyOrderKey nvarchar(1000) NULL;
ALTER TABLE dbo.LegacyStockHistories DROP CONSTRAINT CK_LegacyStockHistories_Status;
ALTER TABLE dbo.LegacyStockHistories DROP CONSTRAINT DF_LegacyStockHistories_Status;
ALTER TABLE dbo.LegacyStockHistories ALTER COLUMN DataStatus nvarchar(20) COLLATE Latin1_General_100_BIN2 NOT NULL;
ALTER TABLE dbo.LegacyStockHistories ADD CONSTRAINT DF_LegacyStockHistories_Status DEFAULT N'Archived' FOR DataStatus;
ALTER TABLE dbo.LegacyStockHistories ADD CONSTRAINT CK_LegacyStockHistories_Status CHECK(DataStatus IN(N'Archived',N'Orphan',N'Incomplete'));
EXEC(N'CREATE TRIGGER dbo.TR_ImportOrderItems_Origin ON dbo.ImportOrderItems AFTER INSERT, UPDATE AS
BEGIN
 SET NOCOUNT ON;
 IF EXISTS(SELECT 1 FROM inserted i JOIN deleted d ON d.ImportOrderItemId=i.ImportOrderItemId WHERE i.RecordOrigin<>d.RecordOrigin)
 BEGIN ROLLBACK TRANSACTION; THROW 58800,N''Không được đổi nguồn gốc item nhập.'',1; END;
 IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.ImportOrders h ON h.ImportOrderId=i.ImportOrderId WHERE i.RecordOrigin<>h.RecordOrigin OR (i.RecordOrigin=N''Sql'' AND i.DataStatus<>N''Valid''))
 BEGIN ROLLBACK TRANSACTION; THROW 58791,N''Nguồn gốc item nhập không khớp header.'',1; END;
 IF EXISTS(SELECT 1 FROM inserted WHERE RecordOrigin=N''Legacy'') AND IS_MEMBER(N''OperationalMigrationWriter'')<>1 AND USER_NAME()<>N''dbo''
 BEGIN ROLLBACK TRANSACTION; THROW 58792,N''Chỉ vai trò migration được ghi Import Legacy.'',1; END;
END;');
EXEC(N'CREATE TRIGGER dbo.TR_ImportOrders_Origin ON dbo.ImportOrders AFTER INSERT, UPDATE AS
BEGIN
 SET NOCOUNT ON;
 IF EXISTS(SELECT 1 FROM inserted i JOIN deleted d ON d.ImportOrderId=i.ImportOrderId WHERE i.RecordOrigin<>d.RecordOrigin)
 BEGIN ROLLBACK TRANSACTION; THROW 58801,N''Không được đổi nguồn gốc chứng từ nhập.'',1; END;
 IF EXISTS(SELECT 1 FROM inserted WHERE RecordOrigin=N''Legacy'') AND IS_MEMBER(N''OperationalMigrationWriter'')<>1 AND USER_NAME()<>N''dbo''
 BEGIN ROLLBACK TRANSACTION; THROW 58802,N''Chỉ vai trò migration được ghi Import Legacy.'',1; END;
END;');
EXEC(N'CREATE TRIGGER dbo.TR_ExportOrderItems_Origin ON dbo.ExportOrderItems AFTER INSERT, UPDATE AS
BEGIN
 SET NOCOUNT ON;
 IF EXISTS(SELECT 1 FROM inserted i JOIN deleted d ON d.ExportOrderItemId=i.ExportOrderItemId WHERE i.RecordOrigin<>d.RecordOrigin)
 BEGIN ROLLBACK TRANSACTION; THROW 58803,N''Không được đổi nguồn gốc item xuất.'',1; END;
 IF EXISTS(SELECT 1 FROM inserted i JOIN dbo.ExportOrders h ON h.ExportOrderId=i.ExportOrderId WHERE i.RecordOrigin<>h.RecordOrigin OR (i.RecordOrigin=N''Sql'' AND i.DataStatus<>N''Valid''))
 BEGIN ROLLBACK TRANSACTION; THROW 58793,N''Nguồn gốc item xuất không khớp header.'',1; END;
 IF EXISTS(SELECT 1 FROM inserted WHERE RecordOrigin=N''Legacy'') AND IS_MEMBER(N''OperationalMigrationWriter'')<>1 AND USER_NAME()<>N''dbo''
 BEGIN ROLLBACK TRANSACTION; THROW 58794,N''Chỉ vai trò migration được ghi Export Legacy.'',1; END;
END;');
EXEC(N'CREATE TRIGGER dbo.TR_ExportOrders_Origin ON dbo.ExportOrders AFTER INSERT, UPDATE AS
BEGIN
 SET NOCOUNT ON;
 IF EXISTS(SELECT 1 FROM inserted i JOIN deleted d ON d.ExportOrderId=i.ExportOrderId WHERE i.RecordOrigin<>d.RecordOrigin)
 BEGIN ROLLBACK TRANSACTION; THROW 58804,N''Không được đổi nguồn gốc chứng từ xuất.'',1; END;
 IF EXISTS(SELECT 1 FROM inserted WHERE RecordOrigin=N''Legacy'') AND IS_MEMBER(N''OperationalMigrationWriter'')<>1 AND USER_NAME()<>N''dbo''
 BEGIN ROLLBACK TRANSACTION; THROW 58805,N''Chỉ vai trò migration được ghi Export Legacy.'',1; END;
END;');
EXEC(N'CREATE PROCEDURE dbo.ReverseStockOperation
 @SourceOperationId uniqueidentifier, @ReversalOperationId uniqueidentifier, @PublicId char(24), @IdempotencyKey nvarchar(128), @OccurredAtUtc datetime2(7)
WITH EXECUTE AS OWNER
AS
BEGIN
 SET NOCOUNT ON; SET XACT_ABORT ON;
 IF @SourceOperationId IS NULL OR @ReversalOperationId IS NULL OR @SourceOperationId=@ReversalOperationId OR @IdempotencyKey IS NULL OR DATALENGTH(@IdempotencyKey)=0 OR DATALENGTH(@IdempotencyKey)>256 OR @PublicId LIKE ''%[^0-9a-f]%'' OR LEN(@PublicId)<>24 THROW 58795,N''Tham số hoàn tác không hợp lệ.'',1;
 BEGIN TRY
  BEGIN TRANSACTION;
  IF NOT EXISTS(SELECT 1 FROM dbo.StockOperations WITH(UPDLOCK,HOLDLOCK) WHERE StockOperationId=@SourceOperationId AND OperationType<>N''Reversal'') THROW 58796,N''Operation nguồn không tồn tại hoặc không thể hoàn tác.'',1;
  IF EXISTS(SELECT 1 FROM dbo.StockOperations WITH(UPDLOCK,HOLDLOCK) WHERE ReversalOfOperationId=@SourceOperationId) THROW 58797,N''Operation nguồn đã được hoàn tác.'',1;
  IF NOT EXISTS(SELECT 1 FROM dbo.StockMovementLines WHERE StockOperationId=@SourceOperationId) THROW 58798,N''Operation nguồn không có dòng tồn kho.'',1;
  IF EXISTS(SELECT 1 FROM dbo.StockMovementLines l JOIN dbo.Stocks s WITH(UPDLOCK,HOLDLOCK) ON s.ProductVariantId=l.ProductVariantId JOIN dbo.ProductVariants v ON v.ProductVariantId=l.ProductVariantId JOIN dbo.Products p WITH(UPDLOCK,HOLDLOCK) ON p.ProductId=v.ProductId WHERE l.StockOperationId=@SourceOperationId AND (s.QuantityForSale-l.QuantityForSaleChange<0 OR s.QuantityInStorage-l.QuantityInStorageChange<0 OR (p.PurchaseCount IS NOT NULL AND p.PurchaseCount-l.PurchaseCountChange<0))) THROW 58799,N''Không đủ tồn kho hoặc lượt mua để hoàn tác.'',1;
  INSERT dbo.StockOperations(StockOperationId,PublicId,IdempotencyKey,OperationType,ReversalOfOperationId,OccurredAtUtc,Version) VALUES(@ReversalOperationId,@PublicId,@IdempotencyKey,N''Reversal'',@SourceOperationId,@OccurredAtUtc,0);
  INSERT dbo.StockMovementLines(StockMovementLineId,StockOperationId,ProductVariantId,QuantityForSaleChange,QuantityInStorageChange,PurchaseCountChange) SELECT NEWID(),@ReversalOperationId,ProductVariantId,-QuantityForSaleChange,-QuantityInStorageChange,-PurchaseCountChange FROM dbo.StockMovementLines WHERE StockOperationId=@SourceOperationId;
  UPDATE s SET QuantityForSale=s.QuantityForSale-l.QuantityForSaleChange, QuantityInStorage=s.QuantityInStorage-l.QuantityInStorageChange, UpdatedAtUtc=SYSUTCDATETIME() FROM dbo.Stocks s JOIN dbo.StockMovementLines l ON l.ProductVariantId=s.ProductVariantId WHERE l.StockOperationId=@SourceOperationId;
  UPDATE p SET PurchaseCount=CASE WHEN p.PurchaseCount IS NULL THEN NULL ELSE p.PurchaseCount-l.PurchaseCountChange END FROM dbo.Products p JOIN dbo.ProductVariants v ON v.ProductId=p.ProductId JOIN dbo.StockMovementLines l ON l.ProductVariantId=v.ProductVariantId WHERE l.StockOperationId=@SourceOperationId;
  COMMIT;
 END TRY
 BEGIN CATCH
  IF XACT_STATE()<>0 ROLLBACK;
  THROW;
 END CATCH;
END;');
GRANT EXECUTE ON dbo.ReverseStockOperation TO OperationalRuntime;
INSERT dbo.SchemaVersions SELECT NEWID(),N'Operational',7,N'007_CreateInventoryTables.sql','$(ScriptChecksum)',SYSUTCDATETIME(),ORIGINAL_LOGIN(); COMMIT;
GO
