using System.Text.Json;
using Microsoft.Data.SqlClient;
using TTSmartEcom.Application.Abstractions.Catalog;
using TTSmartEcom.Domain.Catalog;

namespace TTSmartEcom.Infrastructure.SqlServer.Catalog;

#pragma warning disable CA1725

public sealed class SqlCatalogRepository(ICompanyDbConnectionFactory factory, IOperationalDbConnectionFactory operationalFactory) : ICatalogRepository, ICatalogWriteRepository, ICatalogMediaRepository
{
    public async Task<IReadOnlyList<BrandRecord>> ListBrandsAsync(CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT PublicId,Name FROM dbo.Brands ORDER BY Name;",c);List<BrandRecord> result=[];await using SqlDataReader r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))result.Add(new(r.GetString(0),r.IsDBNull(1)?null:r.GetString(1)));return result;}
    public async Task<IReadOnlyList<string>> ListSectionNamesAsync(CancellationToken ct)=>(await SectionsAsync(ct)).Select(x=>x.Name??string.Empty).Where(x=>x.Length>0).ToArray();
    public async Task<SectionDocumentRecord?> GetSectionDocumentAsync(CancellationToken ct){SectionItemRecord[] x=await SectionsAsync(ct);return x.Length==0?null:new SectionDocumentRecord("categories",x);}
    public async Task<IReadOnlyList<string>?> GetSectionValuesAsync(string name,CancellationToken ct)=>(await SectionsAsync(ct)).FirstOrDefault(x=>x.Name==name)?.Values;
    public async Task<IReadOnlyDictionary<string,string?>> GetSectionImagesAsync(IReadOnlyCollection<string> names,CancellationToken ct){var source=await SectionsAsync(ct);return names.ToDictionary(x=>x,x=>source.FirstOrDefault(y=>y.Name==x)?.ImageUrl,StringComparer.Ordinal);}
    public async Task<ManageRecord?> GetManageAsync(CancellationToken ct){await using SqlConnection c=operationalFactory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT TOP(1) PublicId,ConfigurationJson FROM dbo.StorefrontSettings;",c);await using SqlDataReader r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;using JsonDocument d=JsonDocument.Parse(r.GetString(1));JsonElement x=d.RootElement;return new ManageRecord(r.GetString(0),Strings(x,"overViewImg"),Strings(x,"partners"),Bool(x,"displayPartners"),null,Text(x,"newProductUrl"),Text(x,"topPurchaseUrl"),Text(x,"highestRatingUrl"),Text(x,"introduction"),null,Text(x,"mainPolicy"),Policies(x),null,new Dictionary<string,ManageSectionRecord>(),null,null);}
    public async Task<IReadOnlyList<ManagePolicyRecord>> GetPoliciesAsync(CancellationToken ct)=>(await GetManageAsync(ct))?.Policies??[];
    public async Task<CatalogMutationResult<BrandRecord>> CreateBrandAsync(string name,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand existing=new("SELECT PublicId,Name FROM dbo.Brands WHERE LOWER(Name)=LOWER(@name);",c);existing.Parameters.AddWithValue("@name",name);await using SqlDataReader r=await existing.ExecuteReaderAsync(ct);if(await r.ReadAsync(ct))return Ok(new BrandRecord(r.GetString(0),r.IsDBNull(1)?null:r.GetString(1)));await r.CloseAsync();string id=SqlPublicIds.New();await using SqlCommand add=new("INSERT dbo.Brands(BrandId,PublicId,Name,Version) VALUES(NEWID(),@id,@name,0);",c);add.Parameters.AddWithValue("@id",id);add.Parameters.AddWithValue("@name",name);await add.ExecuteNonQueryAsync(ct);return Ok(new BrandRecord(id,name));}
    public async Task<CatalogMutationResult<BrandRecord>> DeleteBrandAsync(string id,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("DELETE FROM dbo.Brands OUTPUT deleted.PublicId,deleted.Name WHERE PublicId=@id;",c);q.Parameters.AddWithValue("@id",id);await using SqlDataReader r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?Ok(new BrandRecord(r.GetString(0),r.IsDBNull(1)?null:r.GetString(1))):Not<BrandRecord>("Brand not found");}
    public async Task<ChipValuesRecord?> GetChipValuesAsync(CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT OptionType,Value FROM dbo.ProductOptions ORDER BY SortOrder;",c);Dictionary<string,List<string>> x=new(StringComparer.Ordinal){{"Color",[]},{"Shapes",[]},{"Frames",[]},{"ButtonCount",[]}};await using SqlDataReader r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){string key=r.IsDBNull(0)?string.Empty:r.GetString(0);if(x.TryGetValue(key,out var list)&&!r.IsDBNull(1))list.Add(r.GetString(1));}return new ChipValuesRecord(x["Color"],x["Shapes"],x["Frames"],x["ButtonCount"]);}
    public async Task<CatalogMutationResult<ChipValuesRecord>> AddChipValueAsync(string type,string value,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("IF NOT EXISTS(SELECT 1 FROM dbo.ProductOptions WHERE OptionType=@type AND Value=@value) INSERT dbo.ProductOptions(ProductOptionId,PublicId,OptionType,Value,SortOrder,Version) VALUES(NEWID(),@id,@type,@value,(SELECT COALESCE(MAX(SortOrder),-1)+1 FROM dbo.ProductOptions WHERE OptionType=@type),0);",c);q.Parameters.AddWithValue("@id",SqlPublicIds.New());q.Parameters.AddWithValue("@type",type);q.Parameters.AddWithValue("@value",value);await q.ExecuteNonQueryAsync(ct);return Ok((await GetChipValuesAsync(ct))!);}
    public async Task<CatalogMutationResult<ChipValuesRecord>> RemoveChipValueAsync(string type,string value,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("DELETE FROM dbo.ProductOptions WHERE OptionType=@type AND Value=@value;",c);q.Parameters.AddWithValue("@type",type);q.Parameters.AddWithValue("@value",value);return await q.ExecuteNonQueryAsync(ct)==0?Not<ChipValuesRecord>("Không tìm thấy chip phù hợp để xóa"):Ok((await GetChipValuesAsync(ct))!);}
    public async Task<CatalogMutationResult<SectionDocumentRecord>> CreateSectionAsync(string name,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("IF NOT EXISTS(SELECT 1 FROM dbo.Categories WHERE Name=@name) INSERT dbo.Categories(CategoryId,PublicId,Name,ValuesJson,Version) VALUES(NEWID(),@id,@name,N'[]',0);",c);q.Parameters.AddWithValue("@id",SqlPublicIds.New());q.Parameters.AddWithValue("@name",name);await q.ExecuteNonQueryAsync(ct);return Ok((await GetSectionDocumentAsync(ct))!);}
    public async Task<CatalogMutationResult<SectionDocumentRecord>> RenameSectionAsync(string oldName,string newName,CancellationToken ct)=>await UpdateCategoryAsync(oldName,"UPDATE dbo.Categories SET Name=@new,Version=Version+1 WHERE Name=@old;",newName,null,ct);
    public async Task<CatalogMutationResult<SectionDocumentRecord>> DeleteSectionAsync(string name,CancellationToken ct)=>await UpdateCategoryAsync(name,"DELETE FROM dbo.Categories WHERE Name=@old;",null,null,ct);
    public async Task<CatalogMutationResult<SectionDocumentRecord>> AddSectionValueAsync(string name,string value,CancellationToken ct){SectionItemRecord? s=(await SectionsAsync(ct)).FirstOrDefault(x=>x.Name==name);if(s is null)return Not<SectionDocumentRecord>("Không tìm thấy section");if(s.Values.Contains(value,StringComparer.Ordinal))return Conflict<SectionDocumentRecord>("Value already exists");return await UpdateCategoryAsync(name,"UPDATE dbo.Categories SET ValuesJson=@values,Version=Version+1 WHERE Name=@old;",null,JsonSerializer.Serialize(s.Values.Append(value)),ct);}
    public async Task<CatalogMutationResult<SectionDocumentRecord>> UpdateSectionValueAsync(string name,string oldValue,string newValue,string? imageUrl,CancellationToken ct){SectionItemRecord? s=(await SectionsAsync(ct)).FirstOrDefault(x=>x.Name==name);if(s is null||!s.Values.Contains(oldValue,StringComparer.Ordinal))return Not<SectionDocumentRecord>("Không tìm thấy value");string values=JsonSerializer.Serialize(s.Values.Select(x=>x==oldValue?newValue:x));await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE dbo.Categories SET ValuesJson=@values,ImageUrl=COALESCE(@image,ImageUrl),Version=Version+1 WHERE Name=@name;",c);q.Parameters.AddWithValue("@values",values);q.Parameters.AddWithValue("@image",(object?)imageUrl??DBNull.Value);q.Parameters.AddWithValue("@name",name);await q.ExecuteNonQueryAsync(ct);return Ok((await GetSectionDocumentAsync(ct))!);}
    public async Task<CatalogMutationResult<SectionDocumentRecord>> DeleteSectionValueAsync(string name,string value,CancellationToken ct){SectionItemRecord? s=(await SectionsAsync(ct)).FirstOrDefault(x=>x.Name==name);if(s is null||!s.Values.Contains(value,StringComparer.Ordinal))return Not<SectionDocumentRecord>("Không tìm thấy value");return await UpdateCategoryAsync(name,"UPDATE dbo.Categories SET ValuesJson=@values,Version=Version+1 WHERE Name=@old;",null,JsonSerializer.Serialize(s.Values.Where(x=>x!=value)),ct);}
    public async Task<bool> IsSectionImageReferencedAsync(string filename,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT COUNT(*) FROM dbo.Categories WHERE ImageUrl LIKE @name;",c);q.Parameters.AddWithValue("@name","%"+filename+"%");return Convert.ToInt64(await q.ExecuteScalarAsync(ct),System.Globalization.CultureInfo.InvariantCulture)>0;}
    private async Task<CatalogMutationResult<SectionDocumentRecord>> UpdateCategoryAsync(string name,string sql,string? replacement,string? values,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new(sql,c);q.Parameters.AddWithValue("@old",name);if(replacement is not null)q.Parameters.AddWithValue("@new",replacement);if(values is not null)q.Parameters.AddWithValue("@values",values);return await q.ExecuteNonQueryAsync(ct)==0?Not<SectionDocumentRecord>("Không tìm thấy section"):Ok((await GetSectionDocumentAsync(ct))!);}
    private async Task<SectionItemRecord[]> SectionsAsync(CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT PublicId,Name,ValuesJson,ImageUrl FROM dbo.Categories ORDER BY Name;",c);List<SectionItemRecord> result=[];await using SqlDataReader r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){string[] values=[];try{values=r.IsDBNull(2)?[]:JsonSerializer.Deserialize<string[]>(r.GetString(2))??[];}catch{}result.Add(new(r.GetString(0),r.IsDBNull(1)?null:r.GetString(1),values,r.IsDBNull(3)?null:r.GetString(3)));}return result.ToArray();}
    private static string? Text(JsonElement x,string p)=>x.TryGetProperty(p,out var y)&&y.ValueKind==JsonValueKind.String?y.GetString():null;private static bool? Bool(JsonElement x,string p)=>x.TryGetProperty(p,out var y)&&y.ValueKind is JsonValueKind.True or JsonValueKind.False?y.GetBoolean():null;private static string[] Strings(JsonElement x,string p)=>x.TryGetProperty(p,out var y)&&y.ValueKind==JsonValueKind.Array?y.EnumerateArray().Where(z=>z.ValueKind==JsonValueKind.String).Select(z=>z.GetString()??string.Empty).ToArray():[];private static ManagePolicyRecord[] Policies(JsonElement x)=>[];private static CatalogMutationResult<T> Ok<T>(T x)=>new(CatalogMutationStatus.Success,x);private static CatalogMutationResult<T> Not<T>(string x)=>new(CatalogMutationStatus.NotFound,Message:x);private static CatalogMutationResult<T> Conflict<T>(string x)=>new(CatalogMutationStatus.Conflict,Message:x);
}
