<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>
</Project>
