<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\TTSmartEcom.Application\TTSmartEcom.Application.csproj" />
    <ProjectReference Include="..\TTSmartEcom.Domain\TTSmartEcom.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="BCrypt.Net-Next" />
  </ItemGroup>
</Project>
