SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;
DECLARE @LockResult int;
EXEC @LockResult=sys.sp_getapplock @Resource=N'TTSmart.ControlPlane.V1.Schema',@LockMode=N'Exclusive',@LockOwner=N'Transaction',@LockTimeout=60000;
IF @LockResult<0 THROW 51303,N'Khong lay duoc khoa baseline ControlPlane.',1;
IF NOT EXISTS (SELECT 1 FROM dbo.DatabaseInfo WHERE DatabaseKind=N'ControlPlane') THROW 51300,N'DatabaseInfo khong phai ControlPlane.',1;
IF EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'ControlPlane' AND MigrationNumber=3 AND ScriptChecksum<>'$(ScriptChecksum)') THROW 51301,N'Checksum migration ControlPlane/003 khong khop.',1;
IF EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'ControlPlane' AND MigrationNumber=3) BEGIN COMMIT TRANSACTION; RETURN; END;
IF NOT EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'ControlPlane' AND MigrationNumber=2) THROW 51302,N'Thieu migration ControlPlane/002.',1;

CREATE TABLE dbo.Features
(
 FeatureId uniqueidentifier NOT NULL, FeatureCode nvarchar(100) NOT NULL, NormalizedFeatureCode nvarchar(100) NOT NULL, Name nvarchar(200) NOT NULL, Status tinyint NOT NULL CONSTRAINT DF_Features_Status DEFAULT(1), CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_Features_CreatedAtUtc DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL,
 CONSTRAINT PK_Features PRIMARY KEY CLUSTERED(FeatureId), CONSTRAINT UQ_Features_Code UNIQUE(NormalizedFeatureCode), CONSTRAINT CK_Features_Code CHECK(NormalizedFeatureCode=UPPER(LTRIM(RTRIM(FeatureCode))) AND LEN(LTRIM(RTRIM(FeatureCode)))>0), CONSTRAINT CK_Features_Status CHECK(Status IN(0,1,2))
);
CREATE TABLE dbo.CompanyFeatures
(
 CompanyFeatureId uniqueidentifier NOT NULL, CompanyId uniqueidentifier NOT NULL, FeatureId uniqueidentifier NOT NULL, IsEnabled bit NOT NULL CONSTRAINT DF_CompanyFeatures_IsEnabled DEFAULT(1), SettingsJson nvarchar(max) NULL, CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_CompanyFeatures_CreatedAtUtc DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_CompanyFeatures_UpdatedAtUtc DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL,
 CONSTRAINT PK_CompanyFeatures PRIMARY KEY CLUSTERED(CompanyFeatureId), CONSTRAINT FK_CompanyFeatures_Companies FOREIGN KEY(CompanyId) REFERENCES dbo.Companies(CompanyId), CONSTRAINT FK_CompanyFeatures_Features FOREIGN KEY(FeatureId) REFERENCES dbo.Features(FeatureId), CONSTRAINT UQ_CompanyFeatures_Company_Feature UNIQUE(CompanyId,FeatureId), CONSTRAINT CK_CompanyFeatures_Json CHECK(SettingsJson IS NULL OR ISJSON(SettingsJson)=1)
);
CREATE TABLE dbo.BranchFeatures
(
 BranchFeatureId uniqueidentifier NOT NULL, CompanyId uniqueidentifier NOT NULL, BranchId uniqueidentifier NOT NULL, FeatureId uniqueidentifier NOT NULL, IsEnabled bit NOT NULL CONSTRAINT DF_BranchFeatures_IsEnabled DEFAULT(1), SettingsJson nvarchar(max) NULL, CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_BranchFeatures_CreatedAtUtc DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_BranchFeatures_UpdatedAtUtc DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL,
 CONSTRAINT PK_BranchFeatures PRIMARY KEY CLUSTERED(BranchFeatureId), CONSTRAINT FK_BranchFeatures_Company_Branch FOREIGN KEY(CompanyId,BranchId) REFERENCES dbo.Branches(CompanyId,BranchId), CONSTRAINT FK_BranchFeatures_Company_Feature FOREIGN KEY(CompanyId,FeatureId) REFERENCES dbo.CompanyFeatures(CompanyId,FeatureId), CONSTRAINT UQ_BranchFeatures_Branch_Feature UNIQUE(BranchId,FeatureId), CONSTRAINT CK_BranchFeatures_Json CHECK(SettingsJson IS NULL OR ISJSON(SettingsJson)=1)
);
EXEC(N'CREATE TRIGGER dbo.TR_BranchFeatures_RequireEnabledCompanyFeature ON dbo.BranchFeatures AFTER INSERT, UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted AS i JOIN dbo.CompanyFeatures AS cf ON cf.CompanyId=i.CompanyId AND cf.FeatureId=i.FeatureId WHERE i.IsEnabled=1 AND cf.IsEnabled=0) BEGIN ROLLBACK TRANSACTION; THROW 51310,N''Branch feature can bat khi Company feature dang bat.'',1; END; END;');
EXEC(N'CREATE TRIGGER dbo.TR_CompanyFeatures_PreventDisableEntitledBranch ON dbo.CompanyFeatures AFTER UPDATE AS BEGIN SET NOCOUNT ON; IF UPDATE(IsEnabled) AND EXISTS(SELECT 1 FROM inserted AS i JOIN dbo.BranchFeatures AS bf ON bf.CompanyId=i.CompanyId AND bf.FeatureId=i.FeatureId WHERE i.IsEnabled=0 AND bf.IsEnabled=1) BEGIN ROLLBACK TRANSACTION; THROW 51311,N''Khong the tat Company feature khi Branch van dang bat.'',1; END; END;');
CREATE TABLE dbo.AiBalances
(
 AiBalanceId uniqueidentifier NOT NULL, CompanyId uniqueidentifier NOT NULL, AiType nvarchar(80) NOT NULL, AvailableAmount decimal(19,4) NOT NULL CONSTRAINT DF_AiBalances_AvailableAmount DEFAULT(0), ReservedAmount decimal(19,4) NOT NULL CONSTRAINT DF_AiBalances_ReservedAmount DEFAULT(0), Version int NOT NULL CONSTRAINT DF_AiBalances_Version DEFAULT(0), UpdatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_AiBalances_UpdatedAtUtc DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL,
 CONSTRAINT PK_AiBalances PRIMARY KEY CLUSTERED(AiBalanceId), CONSTRAINT FK_AiBalances_Companies FOREIGN KEY(CompanyId) REFERENCES dbo.Companies(CompanyId), CONSTRAINT UQ_AiBalances_Company_AiType UNIQUE(CompanyId,AiType), CONSTRAINT UQ_AiBalances_Balance_Company UNIQUE(AiBalanceId,CompanyId), CONSTRAINT CK_AiBalances_AiType CHECK(LEN(LTRIM(RTRIM(AiType)))>0), CONSTRAINT CK_AiBalances_Available CHECK(AvailableAmount>=0), CONSTRAINT CK_AiBalances_Reserved CHECK(ReservedAmount>=0), CONSTRAINT CK_AiBalances_Version CHECK(Version>=0)
);
CREATE TABLE dbo.AiReservations
(
 AiReservationId uniqueidentifier NOT NULL, AiBalanceId uniqueidentifier NOT NULL, CompanyId uniqueidentifier NOT NULL, IdempotencyKey nvarchar(128) NOT NULL, ReservedAmount decimal(19,4) NOT NULL, Status tinyint NOT NULL CONSTRAINT DF_AiReservations_Status DEFAULT(0), ExpiresAtUtc datetime2(7) NOT NULL, CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_AiReservations_CreatedAtUtc DEFAULT SYSUTCDATETIME(), ReleasedAtUtc datetime2(7) NULL, RowVersion rowversion NOT NULL,
 CONSTRAINT PK_AiReservations PRIMARY KEY CLUSTERED(AiReservationId), CONSTRAINT FK_AiReservations_Balance_Company FOREIGN KEY(AiBalanceId,CompanyId) REFERENCES dbo.AiBalances(AiBalanceId,CompanyId), CONSTRAINT UQ_AiReservations_Idempotency UNIQUE(IdempotencyKey), CONSTRAINT UQ_AiReservations_Reservation_Balance_Company UNIQUE(AiReservationId,AiBalanceId,CompanyId), CONSTRAINT CK_AiReservations_IdempotencyKey CHECK(DATALENGTH(IdempotencyKey) BETWEEN 2 AND 240 AND IdempotencyKey=LTRIM(RTRIM(IdempotencyKey))), CONSTRAINT CK_AiReservations_Amount CHECK(ReservedAmount>0), CONSTRAINT CK_AiReservations_Status CHECK(Status IN(0,1,2,3)), CONSTRAINT CK_AiReservations_Expiry CHECK(ExpiresAtUtc>CreatedAtUtc)
);
CREATE TABLE dbo.AiTransactions
(
 AiTransactionId uniqueidentifier NOT NULL, AiBalanceId uniqueidentifier NOT NULL, CompanyId uniqueidentifier NOT NULL, AiReservationId uniqueidentifier NULL, TransactionType tinyint NOT NULL, Amount decimal(19,4) NOT NULL, IdempotencyKey nvarchar(128) NOT NULL, OccurredAtUtc datetime2(7) NOT NULL CONSTRAINT DF_AiTransactions_OccurredAtUtc DEFAULT SYSUTCDATETIME(), SafeDetailJson nvarchar(max) NULL,
 CONSTRAINT PK_AiTransactions PRIMARY KEY CLUSTERED(AiTransactionId), CONSTRAINT UQ_AiTransactions_Transaction_Company UNIQUE(AiTransactionId,CompanyId), CONSTRAINT FK_AiTransactions_Balance_Company FOREIGN KEY(AiBalanceId,CompanyId) REFERENCES dbo.AiBalances(AiBalanceId,CompanyId), CONSTRAINT FK_AiTransactions_Reservation_Balance_Company FOREIGN KEY(AiReservationId,AiBalanceId,CompanyId) REFERENCES dbo.AiReservations(AiReservationId,AiBalanceId,CompanyId), CONSTRAINT UQ_AiTransactions_Idempotency UNIQUE(IdempotencyKey), CONSTRAINT CK_AiTransactions_IdempotencyKey CHECK(DATALENGTH(IdempotencyKey) BETWEEN 2 AND 256 AND IdempotencyKey=LTRIM(RTRIM(IdempotencyKey))), CONSTRAINT CK_AiTransactions_Type CHECK(TransactionType IN(1,2,3,4)), CONSTRAINT CK_AiTransactions_Amount CHECK(Amount<>0), CONSTRAINT CK_AiTransactions_Reservation CHECK((TransactionType=1 AND AiReservationId IS NULL) OR (TransactionType IN(2,3,4) AND AiReservationId IS NOT NULL)), CONSTRAINT CK_AiTransactions_Json CHECK(SafeDetailJson IS NULL OR ISJSON(SafeDetailJson)=1)
);
CREATE UNIQUE INDEX UX_AiTransactions_FinalReservation ON dbo.AiTransactions(AiReservationId) WHERE AiReservationId IS NOT NULL;
CREATE TABLE dbo.AiUsageLogs
(
 AiUsageLogId uniqueidentifier NOT NULL, CompanyId uniqueidentifier NOT NULL, BranchId uniqueidentifier NULL, AiTransactionId uniqueidentifier NULL, ProviderCode nvarchar(80) NOT NULL, OperationCode nvarchar(100) NOT NULL, InputUnits bigint NOT NULL CONSTRAINT DF_AiUsageLogs_InputUnits DEFAULT(0), OutputUnits bigint NOT NULL CONSTRAINT DF_AiUsageLogs_OutputUnits DEFAULT(0), ChargedAmount decimal(19,4) NOT NULL CONSTRAINT DF_AiUsageLogs_ChargedAmount DEFAULT(0), OccurredAtUtc datetime2(7) NOT NULL CONSTRAINT DF_AiUsageLogs_OccurredAtUtc DEFAULT SYSUTCDATETIME(),
 CONSTRAINT PK_AiUsageLogs PRIMARY KEY CLUSTERED(AiUsageLogId), CONSTRAINT FK_AiUsageLogs_Company FOREIGN KEY(CompanyId) REFERENCES dbo.Companies(CompanyId), CONSTRAINT FK_AiUsageLogs_Company_Branch FOREIGN KEY(CompanyId,BranchId) REFERENCES dbo.Branches(CompanyId,BranchId), CONSTRAINT FK_AiUsageLogs_AiTransaction_Company FOREIGN KEY(AiTransactionId,CompanyId) REFERENCES dbo.AiTransactions(AiTransactionId,CompanyId), CONSTRAINT CK_AiUsageLogs_Provider CHECK(LEN(LTRIM(RTRIM(ProviderCode)))>0), CONSTRAINT CK_AiUsageLogs_Operation CHECK(LEN(LTRIM(RTRIM(OperationCode)))>0), CONSTRAINT CK_AiUsageLogs_Input CHECK(InputUnits>=0), CONSTRAINT CK_AiUsageLogs_Output CHECK(OutputUnits>=0), CONSTRAINT CK_AiUsageLogs_Charged CHECK(ChargedAmount>=0)
);
CREATE ROLE ControlPlaneRuntime AUTHORIZATION dbo;
CREATE USER ControlPlaneRuntimeUser WITHOUT LOGIN;
ALTER ROLE ControlPlaneRuntime ADD MEMBER ControlPlaneRuntimeUser;
DENY INSERT, UPDATE, DELETE ON dbo.AiBalances TO ControlPlaneRuntime;
DENY INSERT, UPDATE, DELETE ON dbo.AiReservations TO ControlPlaneRuntime;
DENY INSERT, UPDATE, DELETE ON dbo.AiTransactions TO ControlPlaneRuntime;
GRANT SELECT ON dbo.AiBalances TO ControlPlaneRuntime;
GRANT SELECT ON dbo.AiReservations TO ControlPlaneRuntime;
GRANT SELECT ON dbo.AiTransactions TO ControlPlaneRuntime;
EXEC(N'CREATE PROCEDURE dbo.ReserveAiAmount @AiBalanceId uniqueidentifier,@CompanyId uniqueidentifier,@Amount decimal(19,4),@IdempotencyKey nvarchar(128),@ExpiresAtUtc datetime2(7) WITH EXECUTE AS OWNER AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @Amount<=0 OR LEN(LTRIM(RTRIM(@IdempotencyKey)))=0 OR @ExpiresAtUtc<=SYSUTCDATETIME() THROW 51322,N''Reservation AI khong hop le.'',1; BEGIN TRY BEGIN TRANSACTION; DECLARE @Existing uniqueidentifier,@ExistingBalance uniqueidentifier,@ExistingCompany uniqueidentifier,@ExistingAmount decimal(19,4),@ExistingExpiry datetime2(7); SELECT @Existing=AiReservationId,@ExistingBalance=AiBalanceId,@ExistingCompany=CompanyId,@ExistingAmount=ReservedAmount,@ExistingExpiry=ExpiresAtUtc FROM dbo.AiReservations WITH(UPDLOCK,HOLDLOCK) WHERE IdempotencyKey=@IdempotencyKey; IF @Existing IS NOT NULL BEGIN IF @ExistingBalance<>@AiBalanceId OR @ExistingCompany<>@CompanyId OR @ExistingAmount<>@Amount OR @ExistingExpiry<>@ExpiresAtUtc THROW 51326,N''Idempotency key reservation khac tham so.'',1; COMMIT; SELECT @Existing AS AiReservationId; RETURN; END; IF EXISTS(SELECT 1 FROM dbo.AiTransactions WITH(UPDLOCK,HOLDLOCK) WHERE IdempotencyKey=@IdempotencyKey) THROW 51327,N''Idempotency key da thuoc thao tac AI khac.'',1; IF NOT EXISTS(SELECT 1 FROM dbo.AiBalances WITH(UPDLOCK,HOLDLOCK) WHERE AiBalanceId=@AiBalanceId AND CompanyId=@CompanyId AND AvailableAmount>=@Amount) THROW 51323,N''So du AI khong du hoac khac Company.'',1; DECLARE @ReservationId uniqueidentifier=NEWID(); UPDATE dbo.AiBalances SET AvailableAmount=AvailableAmount-@Amount,ReservedAmount=ReservedAmount+@Amount,Version=Version+1,UpdatedAtUtc=SYSUTCDATETIME() WHERE AiBalanceId=@AiBalanceId AND CompanyId=@CompanyId; INSERT dbo.AiReservations(AiReservationId,AiBalanceId,CompanyId,IdempotencyKey,ReservedAmount,ExpiresAtUtc) VALUES(@ReservationId,@AiBalanceId,@CompanyId,@IdempotencyKey,@Amount,@ExpiresAtUtc); INSERT dbo.AiTransactions(AiTransactionId,AiBalanceId,CompanyId,TransactionType,Amount,IdempotencyKey) VALUES(NEWID(),@AiBalanceId,@CompanyId,1,-@Amount,N''reserve:''+@IdempotencyKey); COMMIT; SELECT @ReservationId AS AiReservationId; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH END;');
EXEC(N'CREATE PROCEDURE dbo.FinalizeAiReservation @AiReservationId uniqueidentifier,@CompanyId uniqueidentifier,@TransactionType tinyint,@IdempotencyKey nvarchar(128) WITH EXECUTE AS OWNER AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @TransactionType NOT IN(2,3,4) OR LEN(LTRIM(RTRIM(@IdempotencyKey)))=0 THROW 51324,N''Finalize reservation AI khong hop le.'',1; BEGIN TRY BEGIN TRANSACTION; DECLARE @BalanceId uniqueidentifier,@Amount decimal(19,4),@Status tinyint,@ExistingTransaction uniqueidentifier,@ExistingReservation uniqueidentifier,@ExistingType tinyint,@ExistingCompany uniqueidentifier; SELECT @ExistingTransaction=AiTransactionId,@ExistingReservation=AiReservationId,@ExistingType=TransactionType,@ExistingCompany=CompanyId FROM dbo.AiTransactions WITH(UPDLOCK,HOLDLOCK) WHERE IdempotencyKey=@IdempotencyKey; IF @ExistingTransaction IS NOT NULL BEGIN IF @ExistingReservation<>@AiReservationId OR @ExistingCompany<>@CompanyId OR @ExistingType<>@TransactionType THROW 51328,N''Idempotency key finalize khac tham so.'',1; COMMIT; SELECT @ExistingTransaction AS AiTransactionId; RETURN; END; IF EXISTS(SELECT 1 FROM dbo.AiReservations WITH(UPDLOCK,HOLDLOCK) WHERE IdempotencyKey=@IdempotencyKey) THROW 51329,N''Idempotency key da thuoc thao tac AI khac.'',1; SELECT @BalanceId=AiBalanceId,@Amount=ReservedAmount,@Status=Status FROM dbo.AiReservations WITH(UPDLOCK,HOLDLOCK) WHERE AiReservationId=@AiReservationId AND CompanyId=@CompanyId; IF @BalanceId IS NULL THROW 51325,N''Reservation AI khong ton tai hoac khac Company.'',1; IF @Status<>0 THROW 51330,N''Reservation AI da ket thuc voi idempotency key khac.'',1; DECLARE @TransactionId uniqueidentifier=NEWID(); UPDATE dbo.AiBalances SET ReservedAmount=ReservedAmount-@Amount,AvailableAmount=AvailableAmount+CASE WHEN @TransactionType IN(3,4) THEN @Amount ELSE 0 END,Version=Version+1,UpdatedAtUtc=SYSUTCDATETIME() WHERE AiBalanceId=@BalanceId AND CompanyId=@CompanyId; UPDATE dbo.AiReservations SET Status=@TransactionType-1,ReleasedAtUtc=SYSUTCDATETIME() WHERE AiReservationId=@AiReservationId; INSERT dbo.AiTransactions(AiTransactionId,AiBalanceId,CompanyId,AiReservationId,TransactionType,Amount,IdempotencyKey) VALUES(@TransactionId,@BalanceId,@CompanyId,@AiReservationId,@TransactionType,CASE WHEN @TransactionType=2 THEN -@Amount ELSE @Amount END,@IdempotencyKey); COMMIT; SELECT @TransactionId AS AiTransactionId; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH END;');
/* 120 ky tu giu cho tien to reserve: (8 ky tu) trong cot 128; validate o bien, khong cat chuoi ngam. */
EXEC(N'CREATE OR ALTER PROCEDURE dbo.ReserveAiAmount @AiBalanceId uniqueidentifier,@CompanyId uniqueidentifier,@Amount decimal(19,4),@IdempotencyKey nvarchar(128),@ExpiresAtUtc datetime2(7) WITH EXECUTE AS OWNER AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @Amount<=0 OR @IdempotencyKey IS NULL OR DATALENGTH(@IdempotencyKey) NOT BETWEEN 2 AND 240 OR @IdempotencyKey<>LTRIM(RTRIM(@IdempotencyKey)) OR @ExpiresAtUtc<=SYSUTCDATETIME() THROW 51322,N''Reservation AI khong hop le.'',1; BEGIN TRY BEGIN TRANSACTION; DECLARE @Existing uniqueidentifier,@ExistingBalance uniqueidentifier,@ExistingCompany uniqueidentifier,@ExistingAmount decimal(19,4),@ExistingExpiry datetime2(7); SELECT @Existing=AiReservationId,@ExistingBalance=AiBalanceId,@ExistingCompany=CompanyId,@ExistingAmount=ReservedAmount,@ExistingExpiry=ExpiresAtUtc FROM dbo.AiReservations WITH(UPDLOCK,HOLDLOCK) WHERE IdempotencyKey=@IdempotencyKey; IF @Existing IS NOT NULL BEGIN IF @ExistingBalance<>@AiBalanceId OR @ExistingCompany<>@CompanyId OR @ExistingAmount<>@Amount OR @ExistingExpiry<>@ExpiresAtUtc THROW 51326,N''Idempotency key reservation khac tham so.'',1; COMMIT; SELECT @Existing AS AiReservationId; RETURN; END; IF EXISTS(SELECT 1 FROM dbo.AiTransactions WITH(UPDLOCK,HOLDLOCK) WHERE IdempotencyKey=@IdempotencyKey) THROW 51327,N''Idempotency key da thuoc thao tac AI khac.'',1; IF NOT EXISTS(SELECT 1 FROM dbo.AiBalances WITH(UPDLOCK,HOLDLOCK) WHERE AiBalanceId=@AiBalanceId AND CompanyId=@CompanyId AND AvailableAmount>=@Amount) THROW 51323,N''So du AI khong du hoac khac Company.'',1; DECLARE @ReservationId uniqueidentifier=NEWID(); UPDATE dbo.AiBalances SET AvailableAmount=AvailableAmount-@Amount,ReservedAmount=ReservedAmount+@Amount,Version=Version+1,UpdatedAtUtc=SYSUTCDATETIME() WHERE AiBalanceId=@AiBalanceId AND CompanyId=@CompanyId; INSERT dbo.AiReservations(AiReservationId,AiBalanceId,CompanyId,IdempotencyKey,ReservedAmount,ExpiresAtUtc) VALUES(@ReservationId,@AiBalanceId,@CompanyId,@IdempotencyKey,@Amount,@ExpiresAtUtc); INSERT dbo.AiTransactions(AiTransactionId,AiBalanceId,CompanyId,TransactionType,Amount,IdempotencyKey) VALUES(NEWID(),@AiBalanceId,@CompanyId,1,-@Amount,N''reserve:''+@IdempotencyKey); COMMIT; SELECT @ReservationId AS AiReservationId; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH END;');
EXEC(N'CREATE OR ALTER PROCEDURE dbo.FinalizeAiReservation @AiReservationId uniqueidentifier,@CompanyId uniqueidentifier,@TransactionType tinyint,@IdempotencyKey nvarchar(128) WITH EXECUTE AS OWNER AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @TransactionType NOT IN(2,3,4) OR @IdempotencyKey IS NULL OR DATALENGTH(@IdempotencyKey) NOT BETWEEN 2 AND 240 OR @IdempotencyKey<>LTRIM(RTRIM(@IdempotencyKey)) THROW 51324,N''Finalize reservation AI khong hop le.'',1; BEGIN TRY BEGIN TRANSACTION; DECLARE @BalanceId uniqueidentifier,@Amount decimal(19,4),@Status tinyint,@ExistingTransaction uniqueidentifier,@ExistingReservation uniqueidentifier,@ExistingType tinyint,@ExistingCompany uniqueidentifier; SELECT @ExistingTransaction=AiTransactionId,@ExistingReservation=AiReservationId,@ExistingType=TransactionType,@ExistingCompany=CompanyId FROM dbo.AiTransactions WITH(UPDLOCK,HOLDLOCK) WHERE IdempotencyKey=@IdempotencyKey; IF @ExistingTransaction IS NOT NULL BEGIN IF @ExistingReservation<>@AiReservationId OR @ExistingCompany<>@CompanyId OR @ExistingType<>@TransactionType THROW 51328,N''Idempotency key finalize khac tham so.'',1; COMMIT; SELECT @ExistingTransaction AS AiTransactionId; RETURN; END; IF EXISTS(SELECT 1 FROM dbo.AiReservations WITH(UPDLOCK,HOLDLOCK) WHERE IdempotencyKey=@IdempotencyKey) THROW 51329,N''Idempotency key da thuoc thao tac AI khac.'',1; SELECT @BalanceId=AiBalanceId,@Amount=ReservedAmount,@Status=Status FROM dbo.AiReservations WITH(UPDLOCK,HOLDLOCK) WHERE AiReservationId=@AiReservationId AND CompanyId=@CompanyId; IF @BalanceId IS NULL THROW 51325,N''Reservation AI khong ton tai hoac khac Company.'',1; IF @Status<>0 THROW 51330,N''Reservation AI da ket thuc voi idempotency key khac.'',1; DECLARE @TransactionId uniqueidentifier=NEWID(); UPDATE dbo.AiBalances SET ReservedAmount=ReservedAmount-@Amount,AvailableAmount=AvailableAmount+CASE WHEN @TransactionType IN(3,4) THEN @Amount ELSE 0 END,Version=Version+1,UpdatedAtUtc=SYSUTCDATETIME() WHERE AiBalanceId=@BalanceId AND CompanyId=@CompanyId; UPDATE dbo.AiReservations SET Status=@TransactionType-1,ReleasedAtUtc=SYSUTCDATETIME() WHERE AiReservationId=@AiReservationId; INSERT dbo.AiTransactions(AiTransactionId,AiBalanceId,CompanyId,AiReservationId,TransactionType,Amount,IdempotencyKey) VALUES(@TransactionId,@BalanceId,@CompanyId,@AiReservationId,@TransactionType,CASE WHEN @TransactionType=2 THEN -@Amount ELSE @Amount END,@IdempotencyKey); COMMIT; SELECT @TransactionId AS AiTransactionId; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH END;');
GRANT EXECUTE ON dbo.ReserveAiAmount TO ControlPlaneRuntime;
GRANT EXECUTE ON dbo.FinalizeAiReservation TO ControlPlaneRuntime;
INSERT dbo.SchemaVersions(SchemaVersionId,ModuleCode,MigrationNumber,MigrationName,ScriptChecksum) VALUES(NEWID(),N'ControlPlane',3,N'003_CreateFeatureAndAiTables.sql','$(ScriptChecksum)');
COMMIT TRANSACTION;
