SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;
DECLARE @LockResult int;
EXEC @LockResult=sys.sp_getapplock @Resource=N'TTSmart.ControlPlane.V1.Schema',@LockMode=N'Exclusive',@LockOwner=N'Transaction',@LockTimeout=60000;
IF @LockResult<0 THROW 51403,N'Khong lay duoc khoa baseline ControlPlane.',1;
IF NOT EXISTS (SELECT 1 FROM dbo.DatabaseInfo WHERE DatabaseKind=N'ControlPlane') THROW 51400,N'DatabaseInfo khong phai ControlPlane.',1;
IF EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'ControlPlane' AND MigrationNumber=4 AND ScriptChecksum<>'$(ScriptChecksum)') THROW 51401,N'Checksum migration ControlPlane/004 khong khop.',1;
IF EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'ControlPlane' AND MigrationNumber=4) BEGIN COMMIT TRANSACTION; RETURN; END;
IF NOT EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'ControlPlane' AND MigrationNumber=3) THROW 51402,N'Thieu migration ControlPlane/003.',1;

EXEC(N'CREATE FUNCTION dbo.IsSafeStorageNamespace(@Value nvarchar(200)) RETURNS bit WITH SCHEMABINDING AS BEGIN DECLARE @Start int=1,@Slash int,@Segment nvarchar(200),@Device nvarchar(200); IF @Value IS NULL OR DATALENGTH(@Value) NOT BETWEEN 2 AND 400 OR DATALENGTH(@Value)<>DATALENGTH(RTRIM(@Value)) OR LEFT(@Value,1)=NCHAR(47) OR RIGHT(@Value,1)=NCHAR(47) OR CHARINDEX(NCHAR(58),@Value)>0 OR CHARINDEX(NCHAR(92),@Value)>0 OR CHARINDEX(NCHAR(47)+NCHAR(47),@Value)>0 RETURN 0; WHILE @Start<=LEN(@Value) BEGIN SET @Slash=CHARINDEX(NCHAR(47),@Value,@Start); IF @Slash=0 SET @Slash=LEN(@Value)+1; SET @Segment=SUBSTRING(@Value,@Start,@Slash-@Start); SET @Device=UPPER(LEFT(@Segment,CHARINDEX(NCHAR(46),@Segment+NCHAR(46))-1)); IF DATALENGTH(@Segment)=0 OR DATALENGTH(@Segment)<>DATALENGTH(LTRIM(RTRIM(@Segment))) OR RIGHT(@Segment,1)=NCHAR(46) OR @Segment IN(NCHAR(46),NCHAR(46)+NCHAR(46)) OR @Device IN(N''CON'',N''PRN'',N''AUX'',N''NUL'',N''COM1'',N''COM2'',N''COM3'',N''COM4'',N''COM5'',N''COM6'',N''COM7'',N''COM8'',N''COM9'',N''LPT1'',N''LPT2'',N''LPT3'',N''LPT4'',N''LPT5'',N''LPT6'',N''LPT7'',N''LPT8'',N''LPT9'') RETURN 0; SET @Start=@Slash+1; END; RETURN 1; END;');

CREATE TABLE dbo.DatabaseServers
(
 DatabaseServerId uniqueidentifier NOT NULL, ServerCode nvarchar(80) NOT NULL, NormalizedServerCode nvarchar(80) NOT NULL, HostAlias nvarchar(255) NOT NULL, DeploymentMode tinyint NOT NULL, Status tinyint NOT NULL CONSTRAINT DF_DatabaseServers_Status DEFAULT(1), CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_DatabaseServers_CreatedAtUtc DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_DatabaseServers_UpdatedAtUtc DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL,
 CONSTRAINT PK_DatabaseServers PRIMARY KEY CLUSTERED(DatabaseServerId), CONSTRAINT UQ_DatabaseServers_Code UNIQUE(NormalizedServerCode), CONSTRAINT CK_DatabaseServers_Code CHECK(NormalizedServerCode=UPPER(LTRIM(RTRIM(ServerCode))) AND LEN(LTRIM(RTRIM(ServerCode)))>0), CONSTRAINT CK_DatabaseServers_HostAlias CHECK(LEN(LTRIM(RTRIM(HostAlias)))>0), CONSTRAINT CK_DatabaseServers_DeploymentMode CHECK(DeploymentMode IN(1,2,3,4)), CONSTRAINT CK_DatabaseServers_Status CHECK(Status IN(0,1,2))
);
CREATE TABLE dbo.DatabaseTemplates
(
 TemplateId uniqueidentifier NOT NULL, TemplateCode nvarchar(100) NOT NULL, NormalizedTemplateCode nvarchar(100) NOT NULL, DatabaseKind nvarchar(40) NOT NULL, Description nvarchar(500) NULL, Status tinyint NOT NULL CONSTRAINT DF_DatabaseTemplates_Status DEFAULT(1), CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_DatabaseTemplates_CreatedAtUtc DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL,
 CONSTRAINT PK_DatabaseTemplates PRIMARY KEY CLUSTERED(TemplateId), CONSTRAINT UQ_DatabaseTemplates_Code UNIQUE(NormalizedTemplateCode), CONSTRAINT CK_DatabaseTemplates_Code CHECK(NormalizedTemplateCode=UPPER(LTRIM(RTRIM(TemplateCode))) AND LEN(LTRIM(RTRIM(TemplateCode)))>0), CONSTRAINT CK_DatabaseTemplates_Kind CHECK(DatabaseKind IN(N'Operational',N'ControlPlane')), CONSTRAINT CK_DatabaseTemplates_Status CHECK(Status IN(0,1,2))
);
CREATE TABLE dbo.DatabaseReleases
(
 DatabaseReleaseId uniqueidentifier NOT NULL, TemplateId uniqueidentifier NOT NULL, ReleaseCode nvarchar(100) NOT NULL, ScriptChecksum char(64) NOT NULL, Status tinyint NOT NULL CONSTRAINT DF_DatabaseReleases_Status DEFAULT(1), ReleasedAtUtc datetime2(7) NULL, CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_DatabaseReleases_CreatedAtUtc DEFAULT SYSUTCDATETIME(),
 CONSTRAINT PK_DatabaseReleases PRIMARY KEY CLUSTERED(DatabaseReleaseId), CONSTRAINT FK_DatabaseReleases_Templates FOREIGN KEY(TemplateId) REFERENCES dbo.DatabaseTemplates(TemplateId), CONSTRAINT UQ_DatabaseReleases_Template_Code UNIQUE(TemplateId,ReleaseCode), CONSTRAINT UQ_DatabaseReleases_Release_Template UNIQUE(DatabaseReleaseId,TemplateId), CONSTRAINT CK_DatabaseReleases_Code CHECK(LEN(LTRIM(RTRIM(ReleaseCode)))>0), CONSTRAINT CK_DatabaseReleases_Checksum CHECK(ScriptChecksum COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9A-Fa-f]%' AND LEN(ScriptChecksum)=64), CONSTRAINT CK_DatabaseReleases_Status CHECK(Status IN(0,1,2))
);
CREATE TABLE dbo.ManagedDatabases
(
 ManagedDatabaseId uniqueidentifier NOT NULL, DatabaseType tinyint NOT NULL, DatabaseServerId uniqueidentifier NOT NULL, CompanyId uniqueidentifier NULL, BranchId uniqueidentifier NULL, DatabaseName nvarchar(128) NOT NULL, NormalizedDatabaseName nvarchar(128) NOT NULL, AuthenticationType tinyint NOT NULL, SqlLoginName nvarchar(128) NULL, NormalizedSqlLoginName nvarchar(128) NULL, SecretReferenceId uniqueidentifier NULL, DeploymentMode tinyint NOT NULL, StorageNamespace nvarchar(200) NOT NULL, TemplateId uniqueidentifier NOT NULL, CurrentReleaseId uniqueidentifier NULL, Status tinyint NOT NULL CONSTRAINT DF_ManagedDatabases_Status DEFAULT(0), HealthStatus tinyint NOT NULL CONSTRAINT DF_ManagedDatabases_HealthStatus DEFAULT(0), Version int NOT NULL CONSTRAINT DF_ManagedDatabases_Version DEFAULT(0), LastHealthCheckAtUtc datetime2(7) NULL, CreatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_ManagedDatabases_CreatedAtUtc DEFAULT SYSUTCDATETIME(), UpdatedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_ManagedDatabases_UpdatedAtUtc DEFAULT SYSUTCDATETIME(), RowVersion rowversion NOT NULL,
 CONSTRAINT PK_ManagedDatabases PRIMARY KEY CLUSTERED(ManagedDatabaseId), CONSTRAINT FK_ManagedDatabases_Servers FOREIGN KEY(DatabaseServerId) REFERENCES dbo.DatabaseServers(DatabaseServerId), CONSTRAINT FK_ManagedDatabases_Companies FOREIGN KEY(CompanyId) REFERENCES dbo.Companies(CompanyId), CONSTRAINT FK_ManagedDatabases_Company_Branches FOREIGN KEY(CompanyId,BranchId) REFERENCES dbo.Branches(CompanyId,BranchId), CONSTRAINT FK_ManagedDatabases_SecretReferences FOREIGN KEY(SecretReferenceId) REFERENCES dbo.SecretReferences(SecretReferenceId), CONSTRAINT FK_ManagedDatabases_Templates FOREIGN KEY(TemplateId) REFERENCES dbo.DatabaseTemplates(TemplateId), CONSTRAINT FK_ManagedDatabases_CurrentRelease_Template FOREIGN KEY(CurrentReleaseId,TemplateId) REFERENCES dbo.DatabaseReleases(DatabaseReleaseId,TemplateId), CONSTRAINT UQ_ManagedDatabases_Server_Name UNIQUE(DatabaseServerId,NormalizedDatabaseName), CONSTRAINT UQ_ManagedDatabases_Server_Namespace UNIQUE(DatabaseServerId,StorageNamespace), CONSTRAINT CK_ManagedDatabases_Type CHECK(DatabaseType IN(1,2,3)), CONSTRAINT CK_ManagedDatabases_DatabaseName CHECK((DatabaseType=1 AND DatabaseName=N'ttsmart.com.vn' AND NormalizedDatabaseName=N'TTSMART.COM.VN') OR (DatabaseType<>1 AND LEN(DatabaseName) BETWEEN 1 AND 128 AND DatabaseName COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^A-Za-z0-9_]%' AND NormalizedDatabaseName=UPPER(DatabaseName))), CONSTRAINT CK_ManagedDatabases_BranchType CHECK((DatabaseType=1 AND CompanyId IS NULL AND BranchId IS NULL) OR (DatabaseType=2 AND CompanyId IS NOT NULL AND BranchId IS NOT NULL AND LEN(DatabaseName)>7 AND DatabaseName COLLATE Latin1_General_100_BIN2 LIKE N'%[_]online') OR (DatabaseType=3 AND CompanyId IS NOT NULL AND BranchId IS NULL)), CONSTRAINT CK_ManagedDatabases_Authentication CHECK((AuthenticationType=1 AND SqlLoginName IS NULL AND NormalizedSqlLoginName IS NULL AND SecretReferenceId IS NULL) OR (AuthenticationType=2 AND SqlLoginName IS NOT NULL AND NormalizedSqlLoginName=UPPER(SqlLoginName) AND SecretReferenceId IS NOT NULL)), CONSTRAINT CK_ManagedDatabases_LoginName CHECK(SqlLoginName IS NULL OR (LEN(SqlLoginName) BETWEEN 1 AND 128 AND SqlLoginName COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^A-Za-z0-9_]%')), CONSTRAINT CK_ManagedDatabases_DeploymentMode CHECK(DeploymentMode IN(1,2,3,4)), CONSTRAINT CK_ManagedDatabases_StorageNamespace CHECK(dbo.IsSafeStorageNamespace(StorageNamespace)=1), CONSTRAINT CK_ManagedDatabases_Status CHECK(Status IN(0,1,2,3,4)), CONSTRAINT CK_ManagedDatabases_Health CHECK(HealthStatus IN(0,1,2,3)), CONSTRAINT CK_ManagedDatabases_Version CHECK(Version>=0)
);
CREATE UNIQUE INDEX UX_ManagedDatabases_Server_Login ON dbo.ManagedDatabases(DatabaseServerId,NormalizedSqlLoginName) WHERE NormalizedSqlLoginName IS NOT NULL;
CREATE UNIQUE INDEX UX_ManagedDatabases_ActiveOperationalBranch ON dbo.ManagedDatabases(BranchId) WHERE DatabaseType=2 AND Status=2;
CREATE UNIQUE INDEX UX_ManagedDatabases_ActiveTTSmartCompany ON dbo.ManagedDatabases(CompanyId) WHERE DatabaseType=3 AND Status=2;
EXEC(N'CREATE TRIGGER dbo.TR_ManagedDatabases_ValidateTemplateKind ON dbo.ManagedDatabases AFTER INSERT, UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted AS i JOIN dbo.DatabaseTemplates AS t ON t.TemplateId=i.TemplateId WHERE (i.DatabaseType=1 AND t.DatabaseKind<>N''ControlPlane'') OR (i.DatabaseType IN(2,3) AND t.DatabaseKind<>N''Operational'')) BEGIN ROLLBACK TRANSACTION; THROW 51409,N''DatabaseType phai dung DatabaseKind cua template.'',1; END; IF EXISTS(SELECT 1 FROM inserted AS i JOIN dbo.DatabaseReleases AS r ON r.DatabaseReleaseId=i.CurrentReleaseId WHERE r.Status<>2 OR r.ReleasedAtUtc IS NULL) BEGIN ROLLBACK TRANSACTION; THROW 51413,N''CurrentRelease phai la release da phat hanh.'',1; END; IF EXISTS(SELECT 1 FROM inserted AS i JOIN deleted AS d ON d.ManagedDatabaseId=i.ManagedDatabaseId JOIN dbo.ProvisioningJobs AS j ON j.ManagedDatabaseId=i.ManagedDatabaseId AND j.Status IN(0,1) WHERE i.DatabaseServerId<>d.DatabaseServerId OR i.DatabaseName<>d.DatabaseName OR i.NormalizedDatabaseName<>d.NormalizedDatabaseName OR ISNULL(i.SqlLoginName,N'''')<>ISNULL(d.SqlLoginName,N'''') OR ISNULL(i.NormalizedSqlLoginName,N'''')<>ISNULL(d.NormalizedSqlLoginName,N'''') OR ISNULL(i.SecretReferenceId,CONVERT(uniqueidentifier,0x0))<>ISNULL(d.SecretReferenceId,CONVERT(uniqueidentifier,0x0)) OR i.StorageNamespace<>d.StorageNamespace OR i.TemplateId<>d.TemplateId OR ISNULL(i.CurrentReleaseId,CONVERT(uniqueidentifier,0x0))<>ISNULL(d.CurrentReleaseId,CONVERT(uniqueidentifier,0x0)) OR i.DeploymentMode<>d.DeploymentMode) BEGIN ROLLBACK TRANSACTION; THROW 51414,N''Khong duoc doi dich database khi job dang Pending/Running.'',1; END; END;');
EXEC(N'CREATE TRIGGER dbo.TR_DatabaseReleases_ProtectIssuedRelease ON dbo.DatabaseReleases AFTER UPDATE, DELETE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM deleted AS d LEFT JOIN inserted AS i ON i.DatabaseReleaseId=d.DatabaseReleaseId WHERE d.ReleasedAtUtc IS NOT NULL AND (i.DatabaseReleaseId IS NULL OR i.TemplateId<>d.TemplateId OR i.ReleaseCode<>d.ReleaseCode OR i.ScriptChecksum<>d.ScriptChecksum OR i.ReleasedAtUtc<>d.ReleasedAtUtc)) BEGIN ROLLBACK TRANSACTION; THROW 51410,N''Release da phat hanh la bat bien.'',1; END; IF EXISTS(SELECT 1 FROM deleted AS d JOIN dbo.ProvisioningJobs AS j ON j.TargetReleaseId=d.DatabaseReleaseId AND j.Status IN(0,1) LEFT JOIN inserted AS i ON i.DatabaseReleaseId=d.DatabaseReleaseId WHERE i.DatabaseReleaseId IS NULL OR i.TemplateId<>d.TemplateId OR i.ReleaseCode<>d.ReleaseCode OR i.ScriptChecksum<>d.ScriptChecksum) BEGIN ROLLBACK TRANSACTION; THROW 51411,N''Release cua job dang cho/chay khong duoc sua hoac xoa.'',1; END; END;');
EXEC(N'CREATE TRIGGER dbo.TR_DatabaseTemplates_ProtectReferencedTemplate ON dbo.DatabaseTemplates AFTER UPDATE, DELETE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM deleted AS d JOIN dbo.DatabaseReleases AS r ON r.TemplateId=d.TemplateId LEFT JOIN inserted AS i ON i.TemplateId=d.TemplateId WHERE r.ReleasedAtUtc IS NOT NULL AND (i.TemplateId IS NULL OR i.DatabaseKind<>d.DatabaseKind OR i.NormalizedTemplateCode<>d.NormalizedTemplateCode)) BEGIN ROLLBACK TRANSACTION; THROW 51412,N''Template cua release da phat hanh khong duoc doi loai hoac ma.'',1; END; END;');
CREATE TABLE dbo.DatabaseHealthChecks
(
 DatabaseHealthCheckId uniqueidentifier NOT NULL, ManagedDatabaseId uniqueidentifier NOT NULL, HealthStatus tinyint NOT NULL, CheckedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_DatabaseHealthChecks_CheckedAtUtc DEFAULT SYSUTCDATETIME(), ObservedReleaseCode nvarchar(100) NULL, SafeDetail nvarchar(1000) NULL,
 CONSTRAINT PK_DatabaseHealthChecks PRIMARY KEY CLUSTERED(DatabaseHealthCheckId), CONSTRAINT FK_DatabaseHealthChecks_ManagedDatabases FOREIGN KEY(ManagedDatabaseId) REFERENCES dbo.ManagedDatabases(ManagedDatabaseId), CONSTRAINT CK_DatabaseHealthChecks_Status CHECK(HealthStatus IN(0,1,2,3))
);
INSERT dbo.SchemaVersions(SchemaVersionId,ModuleCode,MigrationNumber,MigrationName,ScriptChecksum) VALUES(NEWID(),N'ControlPlane',4,N'004_CreateDatabaseManagementTables.sql','$(ScriptChecksum)');
COMMIT TRANSACTION;
