SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRANSACTION;
DECLARE @LockResult int;
EXEC @LockResult=sys.sp_getapplock @Resource=N'TTSmart.ControlPlane.V1.Schema',@LockMode=N'Exclusive',@LockOwner=N'Transaction',@LockTimeout=60000;
IF @LockResult<0 THROW 51503,N'Khong lay duoc khoa baseline ControlPlane.',1;
IF NOT EXISTS (SELECT 1 FROM dbo.DatabaseInfo WHERE DatabaseKind=N'ControlPlane') THROW 51500,N'DatabaseInfo khong phai ControlPlane.',1;
IF EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'ControlPlane' AND MigrationNumber=5 AND ScriptChecksum<>'$(ScriptChecksum)') THROW 51501,N'Checksum migration ControlPlane/005 khong khop.',1;
IF EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'ControlPlane' AND MigrationNumber=5) BEGIN COMMIT TRANSACTION; RETURN; END;
IF NOT EXISTS (SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'ControlPlane' AND MigrationNumber=4) THROW 51502,N'Thieu migration ControlPlane/004.',1;

CREATE TABLE dbo.ProvisioningJobs
(
 ProvisioningJobId uniqueidentifier NOT NULL, ManagedDatabaseId uniqueidentifier NOT NULL, OperationType tinyint NOT NULL, IdempotencyKey nvarchar(128) NOT NULL, Status tinyint NOT NULL CONSTRAINT DF_ProvisioningJobs_Status DEFAULT(0), LeaseOwner nvarchar(128) NULL, LeaseToken uniqueidentifier NULL, LeaseUntilUtc datetime2(7) NULL, NextAttemptAtUtc datetime2(7) NOT NULL CONSTRAINT DF_ProvisioningJobs_NextAttemptAtUtc DEFAULT SYSUTCDATETIME(), RetryCount int NOT NULL CONSTRAINT DF_ProvisioningJobs_RetryCount DEFAULT(0), TargetReleaseId uniqueidentifier NULL, TargetChecksum char(64) NULL, RequestedAtUtc datetime2(7) NOT NULL CONSTRAINT DF_ProvisioningJobs_RequestedAtUtc DEFAULT SYSUTCDATETIME(), StartedAtUtc datetime2(7) NULL, FinishedAtUtc datetime2(7) NULL, FailureCode nvarchar(100) NULL, SafeFailureDetail nvarchar(1000) NULL, RowVersion rowversion NOT NULL,
 CONSTRAINT PK_ProvisioningJobs PRIMARY KEY CLUSTERED(ProvisioningJobId), CONSTRAINT FK_ProvisioningJobs_ManagedDatabases FOREIGN KEY(ManagedDatabaseId) REFERENCES dbo.ManagedDatabases(ManagedDatabaseId), CONSTRAINT FK_ProvisioningJobs_TargetRelease FOREIGN KEY(TargetReleaseId) REFERENCES dbo.DatabaseReleases(DatabaseReleaseId), CONSTRAINT UQ_ProvisioningJobs_Idempotency UNIQUE(IdempotencyKey), CONSTRAINT CK_ProvisioningJobs_OperationType CHECK(OperationType IN(1,2,3,4,5)), CONSTRAINT CK_ProvisioningJobs_Status CHECK(Status IN(0,1,2,3,4)), CONSTRAINT CK_ProvisioningJobs_RetryCount CHECK(RetryCount>=0), CONSTRAINT CK_ProvisioningJobs_TargetChecksum CHECK(TargetChecksum IS NULL OR (TargetChecksum COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9A-Fa-f]%' AND LEN(TargetChecksum)=64)), CONSTRAINT CK_ProvisioningJobs_TargetRelease CHECK((TargetReleaseId IS NULL AND TargetChecksum IS NULL) OR (TargetReleaseId IS NOT NULL AND TargetChecksum IS NOT NULL)), CONSTRAINT CK_ProvisioningJobs_Lease CHECK((Status=1 AND LeaseOwner IS NOT NULL AND LeaseToken IS NOT NULL AND LeaseUntilUtc IS NOT NULL) OR (Status<>1 AND LeaseOwner IS NULL AND LeaseToken IS NULL AND LeaseUntilUtc IS NULL)), CONSTRAINT CK_ProvisioningJobs_Times CHECK((StartedAtUtc IS NULL OR StartedAtUtc>=RequestedAtUtc) AND (FinishedAtUtc IS NULL OR (StartedAtUtc IS NOT NULL AND FinishedAtUtc>=StartedAtUtc)))
);
CREATE UNIQUE INDEX UX_ProvisioningJobs_ActiveTarget ON dbo.ProvisioningJobs(ManagedDatabaseId) WHERE Status IN(0,1);
CREATE INDEX IX_ProvisioningJobs_Claim ON dbo.ProvisioningJobs(Status,NextAttemptAtUtc,RequestedAtUtc);
CREATE TABLE dbo.ProvisioningSteps
(
 ProvisioningStepId uniqueidentifier NOT NULL, ProvisioningJobId uniqueidentifier NOT NULL, StepCode nvarchar(100) NOT NULL, StepNumber int NOT NULL, Status tinyint NOT NULL CONSTRAINT DF_ProvisioningSteps_Status DEFAULT(0), StartedAtUtc datetime2(7) NULL, FinishedAtUtc datetime2(7) NULL, RetryCount int NOT NULL CONSTRAINT DF_ProvisioningSteps_RetryCount DEFAULT(0), SafeFailureDetail nvarchar(1000) NULL,
 CONSTRAINT PK_ProvisioningSteps PRIMARY KEY CLUSTERED(ProvisioningStepId), CONSTRAINT FK_ProvisioningSteps_Jobs FOREIGN KEY(ProvisioningJobId) REFERENCES dbo.ProvisioningJobs(ProvisioningJobId), CONSTRAINT UQ_ProvisioningSteps_Job_Number UNIQUE(ProvisioningJobId,StepNumber), CONSTRAINT CK_ProvisioningSteps_Code CHECK(LEN(LTRIM(RTRIM(StepCode)))>0), CONSTRAINT CK_ProvisioningSteps_Number CHECK(StepNumber>0), CONSTRAINT CK_ProvisioningSteps_Status CHECK(Status IN(0,1,2,3,4)), CONSTRAINT CK_ProvisioningSteps_Retry CHECK(RetryCount>=0), CONSTRAINT CK_ProvisioningSteps_Times CHECK(FinishedAtUtc IS NULL OR (StartedAtUtc IS NOT NULL AND FinishedAtUtc>=StartedAtUtc))
);
CREATE TABLE dbo.AuditLogs
(
 AuditLogId uniqueidentifier NOT NULL, OccurredAtUtc datetime2(7) NOT NULL CONSTRAINT DF_AuditLogs_OccurredAtUtc DEFAULT SYSUTCDATETIME(), ActorUserId uniqueidentifier NULL, CompanyId uniqueidentifier NULL, BranchId uniqueidentifier NULL, ActionCode nvarchar(150) NOT NULL, EntityType nvarchar(100) NOT NULL, EntityId uniqueidentifier NULL, Outcome tinyint NOT NULL, CorrelationId uniqueidentifier NOT NULL, SafeDetailJson nvarchar(max) NULL,
 CONSTRAINT PK_AuditLogs PRIMARY KEY CLUSTERED(AuditLogId), CONSTRAINT FK_AuditLogs_Users FOREIGN KEY(ActorUserId) REFERENCES dbo.Users(UserId), CONSTRAINT FK_AuditLogs_Companies FOREIGN KEY(CompanyId) REFERENCES dbo.Companies(CompanyId), CONSTRAINT FK_AuditLogs_Company_Branch FOREIGN KEY(CompanyId,BranchId) REFERENCES dbo.Branches(CompanyId,BranchId), CONSTRAINT CK_AuditLogs_BranchCompany CHECK(BranchId IS NULL OR CompanyId IS NOT NULL), CONSTRAINT CK_AuditLogs_Action CHECK(LEN(LTRIM(RTRIM(ActionCode)))>0), CONSTRAINT CK_AuditLogs_EntityType CHECK(LEN(LTRIM(RTRIM(EntityType)))>0), CONSTRAINT CK_AuditLogs_Outcome CHECK(Outcome IN(1,2,3)), CONSTRAINT CK_AuditLogs_Json CHECK(SafeDetailJson IS NULL OR ISJSON(SafeDetailJson)=1)
);
/* Legacy procedure definitions are intentionally not materialized in this baseline.
EXEC(N'CREATE PROCEDURE dbo.ClaimNextProvisioningJob @LeaseOwner nvarchar(128), @LeaseSeconds int = 120 AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF LEN(LTRIM(RTRIM(@LeaseOwner)))=0 OR @LeaseSeconds NOT BETWEEN 1 AND 3600 THROW 51510,N''Tham so claim job khong hop le.'',1; DECLARE @Now datetime2(7)=SYSUTCDATETIME(),@Token uniqueidentifier=NEWID(); BEGIN TRANSACTION; EXEC sys.sp_set_session_context @key=N''TTSmart.ProvisioningWorkflow'',@value=N''1''; ;WITH Candidate AS (SELECT TOP(1) * FROM dbo.ProvisioningJobs WITH(UPDLOCK,READPAST,ROWLOCK) WHERE (Status=0 OR (Status=1 AND LeaseUntilUtc<@Now)) AND NextAttemptAtUtc<=@Now ORDER BY RequestedAtUtc,ProvisioningJobId) UPDATE Candidate SET Status=1,LeaseOwner=@LeaseOwner,LeaseToken=@Token,LeaseUntilUtc=DATEADD(SECOND,@LeaseSeconds,@Now),StartedAtUtc=COALESCE(StartedAtUtc,@Now),RetryCount=RetryCount+1 WHERE Status=0 OR LeaseUntilUtc<@Now; EXEC sys.sp_set_session_context @key=N''TTSmart.ProvisioningWorkflow'',@value=NULL; SELECT ProvisioningJobId,LeaseToken,LeaseUntilUtc FROM dbo.ProvisioningJobs WHERE LeaseToken=@Token; COMMIT TRANSACTION; END;');
EXEC(N'CREATE PROCEDURE dbo.RenewProvisioningLease @ProvisioningJobId uniqueidentifier,@LeaseToken uniqueidentifier,@LeaseSeconds int=120 AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @LeaseToken IS NULL OR @LeaseSeconds NOT BETWEEN 1 AND 3600 THROW 51514,N''Lease renew khong hop le.'',1; BEGIN TRANSACTION; EXEC sys.sp_set_session_context @key=N''TTSmart.ProvisioningWorkflow'',@value=N''1''; UPDATE dbo.ProvisioningJobs SET LeaseUntilUtc=DATEADD(SECOND,@LeaseSeconds,SYSUTCDATETIME()) WHERE ProvisioningJobId=@ProvisioningJobId AND Status=1 AND LeaseToken=@LeaseToken AND LeaseUntilUtc>=SYSUTCDATETIME(); IF @@ROWCOUNT<>1 THROW 51515,N''Lease khong con hieu luc.'',1; EXEC sys.sp_set_session_context @key=N''TTSmart.ProvisioningWorkflow'',@value=NULL; COMMIT TRANSACTION; END;');
EXEC(N'CREATE PROCEDURE dbo.CompleteProvisioningJob @ProvisioningJobId uniqueidentifier,@LeaseToken uniqueidentifier AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; BEGIN TRANSACTION; EXEC sys.sp_set_session_context @key=N''TTSmart.ProvisioningWorkflow'',@value=N''1''; UPDATE dbo.ProvisioningJobs SET Status=2,LeaseOwner=NULL,LeaseToken=NULL,LeaseUntilUtc=NULL,FinishedAtUtc=SYSUTCDATETIME(),FailureCode=NULL,SafeFailureDetail=NULL WHERE ProvisioningJobId=@ProvisioningJobId AND Status=1 AND LeaseToken=@LeaseToken AND LeaseUntilUtc>=SYSUTCDATETIME(); IF @@ROWCOUNT<>1 THROW 51516,N''Khong the complete job voi lease cu.'',1; EXEC sys.sp_set_session_context @key=N''TTSmart.ProvisioningWorkflow'',@value=NULL; COMMIT TRANSACTION; END;');
EXEC(N'CREATE PROCEDURE dbo.FailProvisioningJob @ProvisioningJobId uniqueidentifier,@LeaseToken uniqueidentifier,@FailureCode nvarchar(100),@SafeFailureDetail nvarchar(1000)=NULL,@RetryDelaySeconds int=60,@IsTerminal bit=0 AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF LEN(LTRIM(RTRIM(@FailureCode)))=0 OR @RetryDelaySeconds NOT BETWEEN 0 AND 86400 THROW 51517,N''Thong tin fail job khong hop le.'',1; BEGIN TRANSACTION; EXEC sys.sp_set_session_context @key=N''TTSmart.ProvisioningWorkflow'',@value=N''1''; UPDATE dbo.ProvisioningJobs SET Status=CASE WHEN @IsTerminal=1 THEN 3 ELSE 0 END,LeaseOwner=NULL,LeaseToken=NULL,LeaseUntilUtc=NULL,NextAttemptAtUtc=DATEADD(SECOND,@RetryDelaySeconds,SYSUTCDATETIME()),FinishedAtUtc=CASE WHEN @IsTerminal=1 THEN SYSUTCDATETIME() ELSE NULL END,FailureCode=@FailureCode,SafeFailureDetail=@SafeFailureDetail WHERE ProvisioningJobId=@ProvisioningJobId AND Status=1 AND LeaseToken=@LeaseToken AND LeaseUntilUtc>=SYSUTCDATETIME(); IF @@ROWCOUNT<>1 THROW 51518,N''Khong the fail job voi lease cu.'',1; EXEC sys.sp_set_session_context @key=N''TTSmart.ProvisioningWorkflow'',@value=NULL; COMMIT TRANSACTION; END;');
*/
/* Worker provisioning chi duoc doc metadata can thiet va EXECUTE workflow; khong co DML truc tiep. */
CREATE ROLE ControlPlaneProvisioningWorker AUTHORIZATION dbo;
CREATE USER ControlPlaneProvisioningWorkerUser WITHOUT LOGIN;
ALTER ROLE ControlPlaneProvisioningWorker ADD MEMBER ControlPlaneProvisioningWorkerUser;
DENY INSERT, UPDATE, DELETE ON dbo.ProvisioningJobs TO ControlPlaneProvisioningWorker;
DENY INSERT, UPDATE, DELETE ON dbo.ManagedDatabases TO ControlPlaneProvisioningWorker;
DENY INSERT, UPDATE, DELETE ON dbo.DatabaseReleases TO ControlPlaneProvisioningWorker;
GRANT SELECT ON dbo.ProvisioningJobs TO ControlPlaneProvisioningWorker;
GRANT SELECT ON dbo.ManagedDatabases TO ControlPlaneProvisioningWorker;
GRANT SELECT ON dbo.DatabaseReleases TO ControlPlaneProvisioningWorker;

/* Khong dung co phien do client dat lam ranh gioi bao mat. Trigger chi bao toan bat bien du lieu. */
EXEC(N'CREATE OR ALTER TRIGGER dbo.TR_ProvisioningJobs_ValidateTarget ON dbo.ProvisioningJobs AFTER INSERT, UPDATE AS BEGIN SET NOCOUNT ON; IF EXISTS(SELECT 1 FROM inserted AS i JOIN dbo.ManagedDatabases AS md ON md.ManagedDatabaseId=i.ManagedDatabaseId LEFT JOIN dbo.DatabaseReleases AS r ON r.DatabaseReleaseId=i.TargetReleaseId WHERE i.TargetReleaseId IS NOT NULL AND (r.DatabaseReleaseId IS NULL OR r.TemplateId<>md.TemplateId OR r.ScriptChecksum<>i.TargetChecksum OR r.Status<>2 OR r.ReleasedAtUtc IS NULL)) BEGIN ROLLBACK TRANSACTION; THROW 51520,N''Target release/checksum phai la release da phat hanh dung template cua database.'',1; END; IF EXISTS(SELECT 1 FROM inserted AS i JOIN deleted AS d ON d.ProvisioningJobId=i.ProvisioningJobId WHERE (i.Status IN(0,1) OR d.Status IN(0,1)) AND (i.ManagedDatabaseId<>d.ManagedDatabaseId OR ISNULL(i.TargetReleaseId,CONVERT(uniqueidentifier,0x0))<>ISNULL(d.TargetReleaseId,CONVERT(uniqueidentifier,0x0)) OR ISNULL(i.TargetChecksum,N'''')<>ISNULL(d.TargetChecksum,N''''))) BEGIN ROLLBACK TRANSACTION; THROW 51521,N''Job Pending/Running phai giu nguyen target tu luc tao.'',1; END; END;');
EXEC(N'CREATE OR ALTER TRIGGER dbo.TR_ProvisioningJobs_PreventDirectDelete ON dbo.ProvisioningJobs AFTER DELETE AS BEGIN SET NOCOUNT ON; ROLLBACK TRANSACTION; THROW 51522,N''Khong duoc xoa truc tiep job provisioning.'',1; END;');
EXEC(N'CREATE OR ALTER PROCEDURE dbo.ClaimNextProvisioningJob @LeaseOwner nvarchar(128),@LeaseSeconds int=120 WITH EXECUTE AS OWNER AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @LeaseOwner IS NULL OR LEN(LTRIM(RTRIM(@LeaseOwner)))=0 OR @LeaseOwner<>LTRIM(RTRIM(@LeaseOwner)) OR @LeaseSeconds NOT BETWEEN 1 AND 3600 THROW 51510,N''Tham so claim job khong hop le.'',1; BEGIN TRY BEGIN TRANSACTION; DECLARE @Now datetime2(7)=SYSUTCDATETIME(),@Token uniqueidentifier=NEWID(); ;WITH Candidate AS (SELECT TOP(1) * FROM dbo.ProvisioningJobs WITH(UPDLOCK,READPAST,ROWLOCK) WHERE (Status=0 OR (Status=1 AND LeaseUntilUtc<@Now)) AND NextAttemptAtUtc<=@Now ORDER BY RequestedAtUtc,ProvisioningJobId) UPDATE Candidate SET Status=1,LeaseOwner=@LeaseOwner,LeaseToken=@Token,LeaseUntilUtc=DATEADD(SECOND,@LeaseSeconds,@Now),StartedAtUtc=COALESCE(StartedAtUtc,@Now),RetryCount=RetryCount+1; SELECT ProvisioningJobId,LeaseToken,LeaseUntilUtc FROM dbo.ProvisioningJobs WHERE LeaseToken=@Token; COMMIT TRANSACTION; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH END;');
EXEC(N'CREATE OR ALTER PROCEDURE dbo.RenewProvisioningLease @ProvisioningJobId uniqueidentifier,@LeaseToken uniqueidentifier,@LeaseSeconds int=120 WITH EXECUTE AS OWNER AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @ProvisioningJobId IS NULL OR @LeaseToken IS NULL OR @LeaseSeconds NOT BETWEEN 1 AND 3600 THROW 51514,N''Lease renew khong hop le.'',1; BEGIN TRY BEGIN TRANSACTION; UPDATE dbo.ProvisioningJobs SET LeaseUntilUtc=DATEADD(SECOND,@LeaseSeconds,SYSUTCDATETIME()) WHERE ProvisioningJobId=@ProvisioningJobId AND Status=1 AND LeaseToken=@LeaseToken AND LeaseUntilUtc>=SYSUTCDATETIME(); IF @@ROWCOUNT<>1 THROW 51515,N''Lease khong con hieu luc.'',1; COMMIT TRANSACTION; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH END;');
EXEC(N'CREATE OR ALTER PROCEDURE dbo.CompleteProvisioningJob @ProvisioningJobId uniqueidentifier,@LeaseToken uniqueidentifier WITH EXECUTE AS OWNER AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @ProvisioningJobId IS NULL OR @LeaseToken IS NULL THROW 51516,N''Lease complete khong hop le.'',1; BEGIN TRY BEGIN TRANSACTION; UPDATE dbo.ProvisioningJobs SET Status=2,LeaseOwner=NULL,LeaseToken=NULL,LeaseUntilUtc=NULL,FinishedAtUtc=SYSUTCDATETIME(),FailureCode=NULL,SafeFailureDetail=NULL WHERE ProvisioningJobId=@ProvisioningJobId AND Status=1 AND LeaseToken=@LeaseToken AND LeaseUntilUtc>=SYSUTCDATETIME(); IF @@ROWCOUNT<>1 THROW 51516,N''Khong the complete job voi lease cu.'',1; COMMIT TRANSACTION; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH END;');
EXEC(N'CREATE OR ALTER PROCEDURE dbo.FailProvisioningJob @ProvisioningJobId uniqueidentifier,@LeaseToken uniqueidentifier,@FailureCode nvarchar(100),@SafeFailureDetail nvarchar(1000)=NULL,@RetryDelaySeconds int=60,@IsTerminal bit=0 WITH EXECUTE AS OWNER AS BEGIN SET NOCOUNT ON; SET XACT_ABORT ON; IF @ProvisioningJobId IS NULL OR @LeaseToken IS NULL OR @FailureCode IS NULL OR LEN(LTRIM(RTRIM(@FailureCode)))=0 OR @FailureCode<>LTRIM(RTRIM(@FailureCode)) OR @RetryDelaySeconds NOT BETWEEN 0 AND 86400 THROW 51517,N''Thong tin fail job khong hop le.'',1; BEGIN TRY BEGIN TRANSACTION; UPDATE dbo.ProvisioningJobs SET Status=CASE WHEN @IsTerminal=1 THEN 3 ELSE 0 END,LeaseOwner=NULL,LeaseToken=NULL,LeaseUntilUtc=NULL,NextAttemptAtUtc=DATEADD(SECOND,@RetryDelaySeconds,SYSUTCDATETIME()),FinishedAtUtc=CASE WHEN @IsTerminal=1 THEN SYSUTCDATETIME() ELSE NULL END,FailureCode=@FailureCode,SafeFailureDetail=@SafeFailureDetail WHERE ProvisioningJobId=@ProvisioningJobId AND Status=1 AND LeaseToken=@LeaseToken AND LeaseUntilUtc>=SYSUTCDATETIME(); IF @@ROWCOUNT<>1 THROW 51518,N''Khong the fail job voi lease cu.'',1; COMMIT TRANSACTION; END TRY BEGIN CATCH IF @@TRANCOUNT>0 ROLLBACK; THROW; END CATCH END;');
GRANT EXECUTE ON dbo.ClaimNextProvisioningJob TO ControlPlaneProvisioningWorker;
GRANT EXECUTE ON dbo.RenewProvisioningLease TO ControlPlaneProvisioningWorker;
GRANT EXECUTE ON dbo.CompleteProvisioningJob TO ControlPlaneProvisioningWorker;
GRANT EXECUTE ON dbo.FailProvisioningJob TO ControlPlaneProvisioningWorker;
INSERT dbo.SchemaVersions(SchemaVersionId,ModuleCode,MigrationNumber,MigrationName,ScriptChecksum) VALUES(NEWID(),N'ControlPlane',5,N'005_CreateProvisioningAndAuditTables.sql','$(ScriptChecksum)');
COMMIT TRANSACTION;
