SET NOCOUNT ON; SET XACT_ABORT ON;
IF DB_NAME() <> N'TTSmart_Company_V1_Test' THROW 59620,N'Chi chay tren dung database Company v1 test.',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Company' AND MigrationNumber=2 AND ScriptChecksum='$(ScriptChecksum)') RETURN;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Company' AND MigrationNumber=2) THROW 59621,N'Migration 002 checksum khong khop.',1;
BEGIN TRANSACTION;
DECLARE @lockResult int;
EXEC @lockResult=sys.sp_getapplock @Resource=N'TTSmart.Company.V1.Baseline',@LockMode=N'Exclusive',@LockOwner=N'Transaction',@LockTimeout=60000;
IF @lockResult<0 THROW 59622,N'Khong lay duoc application lock Company v1.',1;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Company' AND MigrationNumber=2 AND ScriptChecksum='$(ScriptChecksum)') BEGIN COMMIT; RETURN; END;
IF EXISTS(SELECT 1 FROM dbo.SchemaVersions WHERE ModuleCode=N'Company' AND MigrationNumber=2) THROW 59621,N'Migration 002 checksum khong khop.',1;
CREATE INDEX IX_Products_BrandId ON dbo.Products(BrandId) WHERE BrandId IS NOT NULL;
CREATE INDEX IX_ProductVariants_ProductId ON dbo.ProductVariants(ProductId);
CREATE INDEX IX_ProductCodes_ProductVariantId ON dbo.ProductCodes(ProductVariantId);
CREATE INDEX IX_ProductCategoryAssignments_CategoryId ON dbo.ProductCategoryAssignments(CategoryId);
CREATE INDEX IX_ProductFiles_FileId ON dbo.ProductFiles(FileId);
CREATE UNIQUE INDEX UX_ProductFiles_Product_File_Usage ON dbo.ProductFiles(ProductId,FileId,UsageType) WHERE ProductId IS NOT NULL;
CREATE UNIQUE INDEX UX_ProductFiles_Variant_File_Usage ON dbo.ProductFiles(ProductVariantId,FileId,UsageType) WHERE ProductVariantId IS NOT NULL;
CREATE INDEX IX_ActivityLogs_Resource_OccurredAtUtc ON dbo.ActivityLogs(ResourceType,ResourceId,OccurredAtUtc DESC);
CREATE INDEX IX_ActivityLogs_CorrelationId ON dbo.ActivityLogs(CorrelationId) WHERE CorrelationId IS NOT NULL;
CREATE INDEX IX_ActivityLogDetails_LogId ON dbo.ActivityLogDetails(ActivityLogId);
CREATE INDEX IX_MigrationMappings_Target ON dbo.MigrationMappings(TargetTable,TargetId);
CREATE INDEX IX_MigrationIssues_Run_Status ON dbo.MigrationIssues(MigrationRunId,Status);
CREATE INDEX IX_MigrationFileManifests_RunId ON dbo.MigrationFileManifests(MigrationRunId);
CREATE ROLE CompanyMigrationWriter AUTHORIZATION dbo;
CREATE ROLE CompanyRuntime AUTHORIZATION dbo;
DENY UPDATE, DELETE ON dbo.ActivityLogs TO CompanyRuntime;
DENY UPDATE, DELETE ON dbo.ActivityLogDetails TO CompanyRuntime;
INSERT dbo.SchemaVersions(SchemaVersionId,ModuleCode,MigrationNumber,MigrationName,ScriptChecksum) VALUES(NEWID(),N'Company',2,N'CreateIndexesAndDatabaseOptions','$(ScriptChecksum)');
COMMIT;
GO
