using System.Globalization;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using TTSmartEcom.Application.Orders;
using TTSmartEcom.Domain.Orders;

namespace TTSmartEcom.Infrastructure.SqlServer.Orders;

#pragma warning disable CA1725

public sealed class SqlOrderRepository(ISqlConnectionFactory factory) : IOrderRepository
{
    public async Task<(IReadOnlyList<SalesOrder> Orders,long Total)> ListAsync(SalesOrderListQuery query,CancellationToken ct)
    {
        await using SqlConnection c=factory.Create();await c.OpenAsync(ct);List<string> filters=[];await using SqlCommand count=new(){Connection=c};AddFilters(filters,count,query);count.CommandText=$"SELECT COUNT(*) FROM dbo.SalesOrders{Where(filters)};";long total=Convert.ToInt64(await count.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);await using SqlCommand q=new(){Connection=c};AddFilters(filters,q,query);string sort=query.SortField=="completedAt"?"CompletedAtUtc":"SourceCreatedAtUtc";q.CommandText=$"SELECT SalesOrderId,PublicId,OrderCode,CustomerPhoneSnapshot,CustomerNameSnapshot,Total,Status,Paid,State,CompletedAtUtc,ImagesJson,SourceCreatedAtUtc,SourceUpdatedAtUtc,Version FROM dbo.SalesOrders{Where(filters)} ORDER BY {sort} DESC OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY;";q.Parameters.AddWithValue("@skip",checked((query.Page-1)*query.Limit));q.Parameters.AddWithValue("@take",query.Limit);return(await ReadManyAsync(c,q,ct),total);
    }
    public async Task<IReadOnlyList<SalesOrder>> ListByPhoneAsync(string phone,string? state,CancellationToken ct)
    {
        await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new(){Connection=c};q.CommandText="SELECT SalesOrderId,PublicId,OrderCode,CustomerPhoneSnapshot,CustomerNameSnapshot,Total,Status,Paid,State,CompletedAtUtc,ImagesJson,SourceCreatedAtUtc,SourceUpdatedAtUtc,Version FROM dbo.SalesOrders WHERE CustomerPhoneSnapshot=@phone"+(string.IsNullOrWhiteSpace(state)?"":state.Equals("Cancelled",StringComparison.OrdinalIgnoreCase)?" AND State=N'Cancelled'":" AND State=N'Processing' AND Status=@status")+" ORDER BY SourceCreatedAtUtc DESC;";q.Parameters.AddWithValue("@phone",phone);if(!string.IsNullOrWhiteSpace(state)&&!state.Equals("Cancelled",StringComparison.OrdinalIgnoreCase))q.Parameters.AddWithValue("@status",state);return await ReadManyAsync(c,q,ct);
    }
    public async Task<SalesOrder?> FindAsync(string id,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT SalesOrderId,PublicId,OrderCode,CustomerPhoneSnapshot,CustomerNameSnapshot,Total,Status,Paid,State,CompletedAtUtc,ImagesJson,SourceCreatedAtUtc,SourceUpdatedAtUtc,Version FROM dbo.SalesOrders WHERE PublicId=@id;",c);q.Parameters.AddWithValue("@id",id);await using SqlDataReader r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?await MapAsync(c,r,ct):null;}
    public async Task<SalesOrder> InsertAsync(SalesOrder order,CancellationToken ct)
    {
        string id=SqlPublicIds.New();DateTime now=DateTime.UtcNow;await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlTransaction tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{Guid key=Guid.NewGuid();await using(SqlCommand q=OrderCommand(c,tx,"INSERT dbo.SalesOrders(SalesOrderId,PublicId,OrderCode,CustomerPhoneSnapshot,CustomerNameSnapshot,Total,TotalRaw,Status,Paid,State,CompletedAtUtc,ImagesJson,SourceCreatedAtUtc,SourceUpdatedAtUtc,Version) VALUES(@key,@id,@code,@phone,@name,@total,@raw,@status,@paid,@state,@completed,@images,@created,@updated,0);",key,id,order,now)){await q.ExecuteNonQueryAsync(ct);}await ReplaceItemsAsync(c,tx,key,order.CartItems,ct);await tx.CommitAsync(ct);return order with{Id=id,CreatedAt=order.CreatedAt??new DateTimeOffset(now,TimeSpan.Zero),UpdatedAt=new DateTimeOffset(now,TimeSpan.Zero),Version=0};}catch{await tx.RollbackAsync(ct);throw;}}
    public async Task<SalesOrder?> UpdateAsync(SalesOrder order,int expectedVersion,CancellationToken ct)
    {
        await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlTransaction tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{Guid? key=await ClaimAsync(c,tx,order,expectedVersion,ct);if(key is null){await tx.RollbackAsync(ct);return null;}await ReplaceItemsAsync(c,tx,key.Value,order.CartItems,ct);await tx.CommitAsync(ct);return order with{Version=checked(expectedVersion+1),UpdatedAt=DateTimeOffset.UtcNow};}catch{await tx.RollbackAsync(ct);throw;}}
    public async Task<bool> DeleteAsync(string id,int expectedVersion,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlTransaction tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{await using(SqlCommand lines=new("DELETE i FROM dbo.SalesOrderItems i JOIN dbo.SalesOrders o ON o.SalesOrderId=i.SalesOrderId WHERE o.PublicId=@id AND o.Version=@version AND (o.Status IS NULL OR o.Status<>N'Completed');",c,tx)){lines.Parameters.AddWithValue("@id",id);lines.Parameters.AddWithValue("@version",expectedVersion);await lines.ExecuteNonQueryAsync(ct);}await using SqlCommand q=new("DELETE FROM dbo.SalesOrders WHERE PublicId=@id AND Version=@version AND (Status IS NULL OR Status<>N'Completed');",c,tx);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@version",expectedVersion);bool result=await q.ExecuteNonQueryAsync(ct)==1;await tx.CommitAsync(ct);return result;}catch{await tx.RollbackAsync(ct);throw;}}
    public async Task<long> CountProcessingAsync(CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT COUNT(*) FROM dbo.SalesOrders WHERE State=N'Processing' AND Status=N'Processing';",c);return Convert.ToInt64(await q.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);}
    public async Task<long> NextOrderCodeAsync(CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlTransaction tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{await using SqlCommand q=new("MERGE dbo.NumberSequences WITH(HOLDLOCK) AS target USING(SELECT N'orderCode' AS SequenceCode) AS source ON target.SequenceCode=source.SequenceCode WHEN MATCHED THEN UPDATE SET NextValue=target.NextValue+1,Version=target.Version+1,UpdatedAtUtc=SYSUTCDATETIME() WHEN NOT MATCHED THEN INSERT(NumberSequenceId,SequenceCode,NextValue,Version) VALUES(NEWID(),N'orderCode',2,0) OUTPUT inserted.NextValue;",c,tx);long next=Convert.ToInt64(await q.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture)-1;await tx.CommitAsync(ct);return next;}catch{await tx.RollbackAsync(ct);throw;}}
    private static SqlCommand OrderCommand(SqlConnection c,SqlTransaction tx,string sql,Guid key,string id,SalesOrder x,DateTime now){SqlCommand q=new(sql,c,tx);q.Parameters.AddWithValue("@key",key);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@code",(object?)x.OrderCode??DBNull.Value);q.Parameters.AddWithValue("@phone",x.UserPhone);q.Parameters.AddWithValue("@name",(object?)x.UserName??DBNull.Value);q.Parameters.AddWithValue("@total",x.Total);q.Parameters.AddWithValue("@raw",x.Total.ToString(CultureInfo.InvariantCulture));q.Parameters.AddWithValue("@status",x.Status);q.Parameters.AddWithValue("@paid",x.Payment);q.Parameters.AddWithValue("@state",x.State);q.Parameters.AddWithValue("@completed",(object?)x.CompletedAt?.UtcDateTime??DBNull.Value);q.Parameters.AddWithValue("@images",JsonSerializer.Serialize(x.Images));q.Parameters.AddWithValue("@created",x.CreatedAt?.UtcDateTime??now);q.Parameters.AddWithValue("@updated",now);return q;}
    private static async Task<Guid?> ClaimAsync(SqlConnection c,SqlTransaction tx,SalesOrder x,int version,CancellationToken ct){await using SqlCommand q=OrderCommand(c,tx,"UPDATE dbo.SalesOrders SET OrderCode=@code,CustomerPhoneSnapshot=@phone,CustomerNameSnapshot=@name,Total=@total,TotalRaw=@raw,Status=@status,Paid=@paid,State=@state,CompletedAtUtc=@completed,ImagesJson=@images,SourceUpdatedAtUtc=@updated,Version=Version+1 OUTPUT inserted.SalesOrderId WHERE PublicId=@id AND Version=@version;",Guid.Empty,x.Id,x,DateTime.UtcNow);q.Parameters.AddWithValue("@version",version);object? result=await q.ExecuteScalarAsync(ct);return result is Guid value?value:null;}
    private static async Task ReplaceItemsAsync(SqlConnection c,SqlTransaction tx,Guid order,IReadOnlyList<SalesOrderItem> items,CancellationToken ct){await using(SqlCommand clear=new("DELETE FROM dbo.SalesOrderItems WHERE SalesOrderId=@order;",c,tx)){clear.Parameters.AddWithValue("@order",order);await clear.ExecuteNonQueryAsync(ct);}for(int i=0;i<items.Count;i++){SalesOrderItem x=items[i];await using SqlCommand q=new("INSERT dbo.SalesOrderItems(SalesOrderItemId,PublicId,SalesOrderId,ProductId,ProductVariantId,SourceProductId,VariantIndex,Quantity,DetailsJson,SortOrder,Version) VALUES(NEWID(),@id,@order,(SELECT ProductId FROM dbo.Products WHERE PublicId=@product),(SELECT TOP(1) ProductVariantId FROM dbo.ProductVariants WHERE ProductId=(SELECT ProductId FROM dbo.Products WHERE PublicId=@product) AND SortOrder=@variant),@product,@variant,@quantity,N'{}',@sort,0);",c,tx);q.Parameters.AddWithValue("@id",string.IsNullOrWhiteSpace(x.SubdocumentId)?SqlPublicIds.New():x.SubdocumentId);q.Parameters.AddWithValue("@order",order);q.Parameters.AddWithValue("@product",x.ProductId);q.Parameters.AddWithValue("@variant",x.VariantIndex);q.Parameters.AddWithValue("@quantity",x.Quantity);q.Parameters.AddWithValue("@sort",i);await q.ExecuteNonQueryAsync(ct);}}
    private static void AddFilters(List<string> f,SqlCommand q,SalesOrderListQuery x){if(!string.IsNullOrWhiteSpace(x.IdOrCode)){f.Add("(PublicId=@key OR OrderCode LIKE @keyLike)");q.Parameters.AddWithValue("@key",x.IdOrCode);q.Parameters.AddWithValue("@keyLike","%"+x.IdOrCode+"%");}if(x.ByCompletedDate)f.Add("Status=N'Completed'");else if(!string.IsNullOrWhiteSpace(x.Status)){f.Add("Status=@status");q.Parameters.AddWithValue("@status",x.Status);}if(x.Payment.HasValue){f.Add("Paid=@paid");q.Parameters.AddWithValue("@paid",x.Payment);}if(!string.IsNullOrWhiteSpace(x.State)){f.Add("State=@state");q.Parameters.AddWithValue("@state",x.State);}if(!string.IsNullOrWhiteSpace(x.Phone)){f.Add("CustomerPhoneSnapshot LIKE @phone");q.Parameters.AddWithValue("@phone","%"+x.Phone+"%");}if(!string.IsNullOrWhiteSpace(x.Name)){f.Add("CustomerNameSnapshot LIKE @name");q.Parameters.AddWithValue("@name","%"+x.Name+"%");}string date=x.ByCompletedDate?"CompletedAtUtc":"SourceCreatedAtUtc";if(x.StartDate.HasValue){f.Add(date+">=@start");q.Parameters.AddWithValue("@start",x.StartDate.Value.UtcDateTime.Date);}if(x.EndDate.HasValue){f.Add(date+"<=@end");q.Parameters.AddWithValue("@end",x.EndDate.Value.UtcDateTime.Date.AddDays(1).AddTicks(-1));}}
    private static string Where(List<string> f)=>f.Count==0?string.Empty:" WHERE "+string.Join(" AND ",f);
    private static async Task<IReadOnlyList<SalesOrder>> ReadManyAsync(SqlConnection c,SqlCommand q,CancellationToken ct){List<SalesOrder> result=[];await using SqlDataReader r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))result.Add(await MapAsync(c,r,ct));return result;}
    private static async Task<SalesOrder> MapAsync(SqlConnection c,SqlDataReader r,CancellationToken ct){Guid key=r.GetGuid(0);List<SalesOrderItem> items=[];await using SqlCommand q=new("SELECT PublicId,SourceProductId,VariantIndex,Quantity FROM dbo.SalesOrderItems WHERE SalesOrderId=@id ORDER BY SortOrder;",c);q.Parameters.AddWithValue("@id",key);await using SqlDataReader lines=await q.ExecuteReaderAsync(ct);while(await lines.ReadAsync(ct))items.Add(new(lines.IsDBNull(1)?string.Empty:lines.GetString(1),lines.IsDBNull(2)?0:lines.GetInt32(2),lines.IsDBNull(3)?0:(int)lines.GetDecimal(3),lines.GetString(0)));return new SalesOrder(r.GetString(1),r.IsDBNull(2)?null:r.GetString(2),r.IsDBNull(3)?string.Empty:r.GetString(3),r.IsDBNull(4)?null:r.GetString(4),items,r.IsDBNull(5)?0:r.GetDecimal(5),r.IsDBNull(6)?"Processing":r.GetString(6),!r.IsDBNull(7)&&r.GetBoolean(7),r.IsDBNull(8)?"Processing":r.GetString(8),Offset(r,9),Strings(r.IsDBNull(10)?null:r.GetString(10)),Offset(r,11),Offset(r,12),checked((int)r.GetInt64(13)));}
    private static DateTimeOffset? Offset(SqlDataReader r,int i)=>r.IsDBNull(i)?null:new DateTimeOffset(r.GetDateTime(i),TimeSpan.Zero);private static string[] Strings(string? json){try{return string.IsNullOrWhiteSpace(json)?[]:JsonSerializer.Deserialize<string[]>(json)??[];}catch(JsonException){return[];}}
}
