using System.Globalization;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using TTSmartEcom.Application.Inventory;
using TTSmartEcom.Domain.Inventory;
using TTSmartEcom.Infrastructure.SqlServer.Products;

namespace TTSmartEcom.Infrastructure.SqlServer.Inventory;

#pragma warning disable CA1725

public sealed class SqlInventoryOrderRepository(
    IOperationalDbConnectionFactory factory,
    SqlBranchProductReader branchProducts) : IInventoryOrderRepository
{
    public async Task<(IReadOnlyList<InventoryOrder> Orders,long Total)> ListAsync(InventoryOrderKind kind,InventoryOrderListQuery query,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);List<string> f=[];await using SqlCommand count=new(){Connection=c};Filters(f,count,kind,query);count.CommandText=$"SELECT COUNT(*) FROM dbo.InventoryOrders{Where(f)};";long total=Convert.ToInt64(await count.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);await using SqlCommand q=new(){Connection=c};Filters(f,q,kind,query);q.CommandText=$"SELECT InventoryOrderId,PublicId,OrderName,Note,UserName,TotalRaw,Status,TransactionDateUtc,CompletedAtUtc,ImagesJson,SourceCreatedAtUtc,SourceUpdatedAtUtc,Version,Direction FROM dbo.InventoryOrders{Where(f)} ORDER BY {(query.ByCompletedDate?"TransactionDateUtc":"SourceCreatedAtUtc")} DESC OFFSET @skip ROWS FETCH NEXT 20 ROWS ONLY;";q.Parameters.AddWithValue("@skip",checked((query.Page-1)*20));return(await ReadManyAsync(c,q,ct),total);}
    public async Task<(IReadOnlyList<InventoryOrderProductSummary> Products,long Total)> ListProductsAsync(InventoryOrderKind kind,int page,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);string direction=kind==InventoryOrderKind.Import?"Import":"Export";await using SqlCommand count=new("SELECT COUNT(DISTINCT i.SourceProductId) FROM dbo.InventoryOrderItems i JOIN dbo.InventoryOrders o ON o.InventoryOrderId=i.InventoryOrderId WHERE o.Direction=@direction AND i.SourceProductId IS NOT NULL;",c);count.Parameters.AddWithValue("@direction",direction);long total=Convert.ToInt64(await count.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);await using SqlCommand q=new("SELECT i.SourceProductId,COALESCE(SUM(i.Quantity),0) FROM dbo.InventoryOrderItems i JOIN dbo.InventoryOrders o ON o.InventoryOrderId=i.InventoryOrderId WHERE o.Direction=@direction AND i.SourceProductId IS NOT NULL GROUP BY i.SourceProductId ORDER BY i.SourceProductId OFFSET @skip ROWS FETCH NEXT 10 ROWS ONLY;",c);q.Parameters.AddWithValue("@direction",direction);q.Parameters.AddWithValue("@skip",checked((page-1)*10));List<(string Id,double Total)> source=[];await using(SqlDataReader r=await q.ExecuteReaderAsync(ct)){while(await r.ReadAsync(ct))source.Add((r.GetString(0),r.IsDBNull(1)?0:(double)r.GetDecimal(1)));}IReadOnlyList<SqlBranchProductSnapshot> catalog=await branchProducts.FindVariantsAsync(source.Select(x=>x.Id).ToArray(),requireActiveAssignment:false,ct);Dictionary<string,List<SqlBranchProductSnapshot>> byProduct=catalog.GroupBy(x=>x.ProductPublicId,StringComparer.OrdinalIgnoreCase).ToDictionary(x=>x.Key,x=>x.OrderBy(v=>v.VariantIndex).ToList(),StringComparer.OrdinalIgnoreCase);List<InventoryOrderProductSummary> result=[];foreach((string id,double ordered)in source){List<SqlBranchProductSnapshot> variants=byProduct.GetValueOrDefault(id)??[];SqlBranchProductSnapshot? first=variants.FirstOrDefault();result.Add(new InventoryOrderProductSummary(id,first?.ProductName,first?.BrandName,variants.Select(ToInventoryVariant).ToArray(),ordered));}return(result,total);}
    public async Task<InventoryOrder?> FindAsync(InventoryOrderKind kind,string id,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("SELECT InventoryOrderId,PublicId,OrderName,Note,UserName,TotalRaw,Status,TransactionDateUtc,CompletedAtUtc,ImagesJson,SourceCreatedAtUtc,SourceUpdatedAtUtc,Version,Direction FROM dbo.InventoryOrders WHERE PublicId=@id AND Direction=@direction;",c);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@direction",Direction(kind));await using SqlDataReader r=await q.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?await MapAsync(c,r,ct):null;}
    public async Task<InventoryOrder> InsertAsync(InventoryOrder order,CancellationToken ct){IReadOnlyDictionary<string,SqlBranchProductSnapshot> products=await ResolveLinesAsync(order.ProductList,true,ct);string id=SqlPublicIds.New();DateTime now=DateTime.UtcNow;await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlTransaction tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{Guid key=Guid.NewGuid();await using(SqlCommand q=Command(c,tx,"INSERT dbo.InventoryOrders(InventoryOrderId,PublicId,Direction,OrderName,Note,UserName,Total,TotalRaw,Status,TransactionDateUtc,CompletedAtUtc,ImagesJson,SourceCreatedAtUtc,SourceUpdatedAtUtc,Version) VALUES(@key,@id,@direction,@name,@note,@user,@total,@raw,@status,@transactionDate,@completed,@images,@created,@updated,0);",key,id,order,now)){await q.ExecuteNonQueryAsync(ct);}await LinesAsync(c,tx,key,order.ProductList,products,ct);await tx.CommitAsync(ct);return order with{Id=id,CreatedAt=order.CreatedAt??new DateTimeOffset(now,TimeSpan.Zero),UpdatedAt=new DateTimeOffset(now,TimeSpan.Zero),Version=0};}catch{await tx.RollbackAsync(ct);throw;}}
    public async Task<InventoryOrder?> UpdateAsync(InventoryOrder order,int expectedVersion,CancellationToken ct){IReadOnlyDictionary<string,SqlBranchProductSnapshot> products=await ResolveLinesAsync(order.ProductList,false,ct);await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlTransaction tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{Guid? key=await ClaimAsync(c,tx,order,expectedVersion,ct);if(key is null){await tx.RollbackAsync(ct);return null;}await LinesAsync(c,tx,key.Value,order.ProductList,products,ct);await tx.CommitAsync(ct);return order with{Version=checked(expectedVersion+1),UpdatedAt=DateTimeOffset.UtcNow};}catch{await tx.RollbackAsync(ct);throw;}}
    public async Task<bool> DeleteAsync(InventoryOrderKind kind,string id,int expectedVersion,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlTransaction tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{await using(SqlCommand x=new("DELETE i FROM dbo.InventoryOrderItems i JOIN dbo.InventoryOrders o ON o.InventoryOrderId=i.InventoryOrderId WHERE o.PublicId=@id AND o.Direction=@direction AND o.Version=@version;",c,tx)){x.Parameters.AddWithValue("@id",id);x.Parameters.AddWithValue("@direction",Direction(kind));x.Parameters.AddWithValue("@version",expectedVersion);await x.ExecuteNonQueryAsync(ct);}await using SqlCommand q=new("DELETE FROM dbo.InventoryOrders WHERE PublicId=@id AND Direction=@direction AND Version=@version;",c,tx);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@direction",Direction(kind));q.Parameters.AddWithValue("@version",expectedVersion);bool found=await q.ExecuteNonQueryAsync(ct)==1;await tx.CommitAsync(ct);return found;}catch{await tx.RollbackAsync(ct);throw;}}
    private static SqlCommand Command(SqlConnection c,SqlTransaction tx,string sql,Guid key,string id,InventoryOrder x,DateTime now){SqlCommand q=new(sql,c,tx);q.Parameters.AddWithValue("@key",key);q.Parameters.AddWithValue("@id",id);q.Parameters.AddWithValue("@direction",Direction(x.Kind));q.Parameters.AddWithValue("@name",x.OrderName);q.Parameters.AddWithValue("@note",x.Note);q.Parameters.AddWithValue("@user",x.UserName);q.Parameters.AddWithValue("@total",Parse(x.Total));q.Parameters.AddWithValue("@raw",x.Total);q.Parameters.AddWithValue("@status",x.Status);q.Parameters.AddWithValue("@transactionDate",(object?)x.TransactionDate?.UtcDateTime??now);q.Parameters.AddWithValue("@completed",(object?)x.CompletedAt?.UtcDateTime??DBNull.Value);q.Parameters.AddWithValue("@images",JsonSerializer.Serialize(x.Images));q.Parameters.AddWithValue("@created",x.CreatedAt?.UtcDateTime??now);q.Parameters.AddWithValue("@updated",now);return q;}
    private static async Task<Guid?> ClaimAsync(SqlConnection c,SqlTransaction tx,InventoryOrder x,int version,CancellationToken ct){await using SqlCommand q=Command(c,tx,"UPDATE dbo.InventoryOrders SET OrderName=@name,Note=@note,UserName=@user,Total=@total,TotalRaw=@raw,Status=@status,TransactionDateUtc=@transactionDate,CompletedAtUtc=@completed,ImagesJson=@images,SourceUpdatedAtUtc=@updated,Version=Version+1 OUTPUT inserted.InventoryOrderId WHERE PublicId=@id AND Direction=@direction AND Version=@version;",Guid.Empty,x.Id,x,DateTime.UtcNow);q.Parameters.AddWithValue("@version",version);object? value=await q.ExecuteScalarAsync(ct);return value is Guid id?id:null;}
    private static async Task LinesAsync(SqlConnection c,SqlTransaction tx,Guid order,IReadOnlyList<InventoryOrderLine> lines,IReadOnlyDictionary<string,SqlBranchProductSnapshot> products,CancellationToken ct)
    {
        await using(SqlCommand clear=new("DELETE FROM dbo.InventoryOrderItems WHERE InventoryOrderId=@order;",c,tx)){clear.Parameters.AddWithValue("@order",order);await clear.ExecuteNonQueryAsync(ct);}
        for(int i=0;i<lines.Count;i++)
        {
            InventoryOrderLine x=lines[i];
            SqlBranchProductSnapshot? product=x.ProductId is null?null:products.GetValueOrDefault(x.ProductId);
            if(x.ProductId is not null&&product is null)throw new UnauthorizedAccessException("Inventory product is not available in the current Branch.");
            await using SqlCommand q=new("INSERT dbo.InventoryOrderItems(InventoryOrderItemId,PublicId,InventoryOrderId,ProductId,ProductVariantId,SourceProductId,Price,PriceRaw,Vat,VatRaw,Quantity,ProgressQuantity,StockAppliedQuantity,Unit,Note,DetailsJson,SortOrder,Version) VALUES(NEWID(),@id,@order,@productId,@variantId,@product,@price,@raw,@vat,@vatraw,@quantity,@progress,@applied,@unit,@note,@details,@sort,0);",c,tx);
            q.Parameters.AddWithValue("@id",string.IsNullOrWhiteSpace(x.SubdocumentId)?SqlPublicIds.New():x.SubdocumentId);
            q.Parameters.AddWithValue("@order",order);
            q.Parameters.AddWithValue("@productId",(object?)product?.ProductId??DBNull.Value);
            q.Parameters.AddWithValue("@variantId",(object?)product?.ProductVariantId??DBNull.Value);
            q.Parameters.AddWithValue("@product",(object?)x.ProductId??DBNull.Value);
            q.Parameters.AddWithValue("@price",(object?)Parse(x.Price)??DBNull.Value);
            q.Parameters.AddWithValue("@raw",(object?)x.Price??DBNull.Value);
            q.Parameters.AddWithValue("@vat",(object?)Parse(x.Vat)??DBNull.Value);
            q.Parameters.AddWithValue("@vatraw",(object?)x.Vat??DBNull.Value);
            q.Parameters.AddWithValue("@quantity",x.Quantity);
            q.Parameters.AddWithValue("@progress",x.ProgressQuantity);
            q.Parameters.AddWithValue("@applied",(object?)x.StockAppliedQuantity??DBNull.Value);
            q.Parameters.AddWithValue("@unit",(object?)x.Unit??DBNull.Value);
            q.Parameters.AddWithValue("@note",(object?)x.Note??DBNull.Value);
            q.Parameters.AddWithValue("@details",JsonSerializer.Serialize(new
            {
                status=x.Status,
                importPriceSnapshot=x.ImportPriceSnapshot,
                profitPercent=x.ProfitPercent,
                stockUpdateSkipped=x.StockUpdateSkipped,
                productCodeSnapshot=x.ProductCodeSnapshot??product?.Code,
                productNameSnapshot=x.Name??product?.ProductName,
                variantNameSnapshot=x.VariantNameSnapshot??product?.VariantName,
                variantPublicIdSnapshot=x.VariantPublicIdSnapshot??product?.ProductVariantPublicId,
                unitPriceSnapshot=x.UnitPriceSnapshot??x.Price,
            }));
            q.Parameters.AddWithValue("@sort",i);
            await q.ExecuteNonQueryAsync(ct);
        }
    }
    private static void Filters(List<string> f,SqlCommand q,InventoryOrderKind kind,InventoryOrderListQuery x){f.Add("Direction=@direction");q.Parameters.AddWithValue("@direction",Direction(kind));if(!string.IsNullOrWhiteSpace(x.OrderName)){f.Add("OrderName LIKE @name");q.Parameters.AddWithValue("@name","%"+x.OrderName+"%");}if(!string.IsNullOrWhiteSpace(x.UserName)){f.Add("UserName LIKE @user");q.Parameters.AddWithValue("@user","%"+x.UserName+"%");}if(x.ByCompletedDate)f.Add("Status=1");else if(x.Status.HasValue){f.Add("Status=@status");q.Parameters.AddWithValue("@status",x.Status);}string date=x.ByCompletedDate?"TransactionDateUtc":"SourceCreatedAtUtc";if(x.StartDate.HasValue){f.Add(date+">=@start");q.Parameters.AddWithValue("@start",x.StartDate.Value.UtcDateTime);}if(x.EndDate.HasValue){f.Add(date+"<=@end");q.Parameters.AddWithValue("@end",x.EndDate.Value.UtcDateTime);}}
    private static string Where(List<string> f)=>" WHERE "+string.Join(" AND ",f);private static string Direction(InventoryOrderKind x)=>x==InventoryOrderKind.Import?"Import":"Export";
    private static async Task<IReadOnlyList<InventoryOrder>> ReadManyAsync(SqlConnection c,SqlCommand q,CancellationToken ct){List<InventoryOrder> result=[];await using SqlDataReader r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))result.Add(await MapAsync(c,r,ct));return result;}
    private static async Task<InventoryOrder> MapAsync(SqlConnection c,SqlDataReader r,CancellationToken ct){Guid id=r.GetGuid(0);InventoryOrderKind kind=r.GetString(13)=="Import"?InventoryOrderKind.Import:InventoryOrderKind.Export;List<InventoryOrderLine> lines=[];await using SqlCommand q=new("SELECT PublicId,SourceProductId,PriceRaw,Quantity,ProgressQuantity,StockAppliedQuantity,Unit,Note,VatRaw,DetailsJson FROM dbo.InventoryOrderItems WHERE InventoryOrderId=@id ORDER BY SortOrder;",c);q.Parameters.AddWithValue("@id",id);await using SqlDataReader rows=await q.ExecuteReaderAsync(ct);while(await rows.ReadAsync(ct)){using JsonDocument d=JsonDocument.Parse(rows.IsDBNull(9)?"{}":rows.GetString(9));JsonElement root=d.RootElement;lines.Add(new InventoryOrderLine(Bool(root,"status"),rows.IsDBNull(1)?null:rows.GetString(1),rows.IsDBNull(2)?null:rows.GetString(2),Text(root,"importPriceSnapshot"),Double(root,"profitPercent"),rows.IsDBNull(6)?null:rows.GetString(6),rows.IsDBNull(3)?0:(int)rows.GetDecimal(3),rows.IsDBNull(4)?0:(double)rows.GetDecimal(4),rows.IsDBNull(5)?null:(double)rows.GetDecimal(5),Bool(root,"stockUpdateSkipped"),rows.IsDBNull(7)?null:rows.GetString(7),rows.IsDBNull(8)?null:rows.GetString(8),Name:Text(root,"productNameSnapshot"),Brand:null,Image:null,SubdocumentId:rows.GetString(0),ProductCodeSnapshot:Text(root,"productCodeSnapshot"),VariantNameSnapshot:Text(root,"variantNameSnapshot"),VariantPublicIdSnapshot:Text(root,"variantPublicIdSnapshot"),UnitPriceSnapshot:Text(root,"unitPriceSnapshot")));}return new InventoryOrder(r.GetString(1),r.IsDBNull(2)?string.Empty:r.GetString(2),r.IsDBNull(3)?string.Empty:r.GetString(3),r.IsDBNull(4)?string.Empty:r.GetString(4),lines,Strings(r.IsDBNull(9)?null:r.GetString(9)),r.IsDBNull(5)?"0":r.GetString(5),!r.IsDBNull(6)&&r.GetBoolean(6),Offset(r,8),Offset(r,10),Offset(r,11),checked((int)r.GetInt64(12)),kind,Offset(r,7)??Offset(r,10));}
    private async Task<IReadOnlyDictionary<string,SqlBranchProductSnapshot>> ResolveLinesAsync(IReadOnlyList<InventoryOrderLine> lines,bool requireAssignment,CancellationToken ct){string[] ids=lines.Select(x=>x.ProductId).Where(x=>!string.IsNullOrWhiteSpace(x)).Cast<string>().Distinct(StringComparer.OrdinalIgnoreCase).ToArray();if(ids.Length==0)return new Dictionary<string,SqlBranchProductSnapshot>(StringComparer.OrdinalIgnoreCase);IReadOnlyList<SqlBranchProductSnapshot> values=await branchProducts.FindVariantsAsync(ids,requireAssignment,ct);Dictionary<string,SqlBranchProductSnapshot> result=values.Where(x=>x.VariantIndex==0).ToDictionary(x=>x.ProductPublicId,StringComparer.OrdinalIgnoreCase);foreach(string id in ids)if(!result.ContainsKey(id))throw new UnauthorizedAccessException("Product is not actively assigned to the current Branch.");return result;}
    private static InventoryOrderProductVariant ToInventoryVariant(SqlBranchProductSnapshot value){using JsonDocument d=JsonDocument.Parse(value.DetailsJson);JsonElement x=d.RootElement;return new(value.ProductVariantPublicId,value.PriceRaw,value.ImportPriceRaw,Double(x,"earn"),Text(x,"imgUrl"),Text(x,"color"),Text(x,"shape"),Text(x,"buttonCount"),Text(x,"frame"),value.QuantityForSale,value.QuantityInStorage,Text(x,"note"));}
    private static decimal? Parse(string? x)=>decimal.TryParse(x,NumberStyles.Any,CultureInfo.InvariantCulture,out decimal n)?n:null;private static string[] Strings(string? x){try{return string.IsNullOrWhiteSpace(x)?[]:JsonSerializer.Deserialize<string[]>(x)??[];}catch{return[];}}private static DateTimeOffset? Offset(SqlDataReader r,int x)=>r.IsDBNull(x)?null:new DateTimeOffset(r.GetDateTime(x),TimeSpan.Zero);private static string? Text(JsonElement x,string p)=>x.TryGetProperty(p,out JsonElement y)&&y.ValueKind==JsonValueKind.String?y.GetString():null;private static bool Bool(JsonElement x,string p)=>x.TryGetProperty(p,out JsonElement y)&&y.ValueKind==JsonValueKind.True;private static double? Double(JsonElement x,string p)=>x.TryGetProperty(p,out JsonElement y)&&y.ValueKind==JsonValueKind.Number&&y.TryGetDouble(out double z)?z:null;
}
