using System.Globalization;
using System.Text.Json;
using Microsoft.Data.SqlClient;
using TTSmartEcom.Application.Audit;
using TTSmartEcom.Domain.Audit;

namespace TTSmartEcom.Infrastructure.SqlServer.Audit;

#pragma warning disable CA1725

public sealed class SqlStorageHistoryRepository(ISqlConnectionFactory factory) : IStorageHistoryRepository, IStorageHistoryWriter
{
    public async Task AppendAsync(StorageHistoryWriteEntry entry,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlTransaction tx=(SqlTransaction)await c.BeginTransactionAsync(ct);try{Guid operation=Guid.NewGuid();string publicId=SqlPublicIds.New();string details=JsonSerializer.Serialize(new{productName=entry.ProductName,userName=entry.UserName,orderId=entry.OrderId,orderName=entry.OrderName,note=entry.Note,isAIScan=entry.IsAiScan,source=entry.Source});await using(SqlCommand q=new("INSERT dbo.StockOperations(StockOperationId,PublicId,OperationType,SourceReference,OccurredAtUtc,DetailsJson,Version) VALUES(@id,@public,@type,@ref,SYSUTCDATETIME(),@details,0);",c,tx)){q.Parameters.AddWithValue("@id",operation);q.Parameters.AddWithValue("@public",publicId);q.Parameters.AddWithValue("@type",(object?)entry.Source??DBNull.Value);q.Parameters.AddWithValue("@ref",(object?)entry.OrderId??DBNull.Value);q.Parameters.AddWithValue("@details",details);await q.ExecuteNonQueryAsync(ct);}await using(SqlCommand q=new("INSERT dbo.StockMovementLines(StockMovementLineId,PublicId,StockOperationId,ProductId,SourceProductId,Quantity,DetailsJson,SortOrder,Version) VALUES(NEWID(),@public,@operation,(SELECT ProductId FROM dbo.Products WHERE PublicId=@product),@product,@quantity,@details,0,0);",c,tx)){q.Parameters.AddWithValue("@public",SqlPublicIds.New());q.Parameters.AddWithValue("@operation",operation);q.Parameters.AddWithValue("@product",entry.ProductId);q.Parameters.AddWithValue("@quantity",entry.Quantity);q.Parameters.AddWithValue("@details",details);await q.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);}catch{await tx.RollbackAsync(ct);throw;}}
    public async Task<StorageHistoryPage> QueryAsync(StorageHistoryQuery query,CancellationToken ct)=>await QueryCoreAsync(query,null,ct);
    public async Task<StorageHistoryPage> QueryProductAsync(string productId,int page,int limit,DateTimeOffset? startDate,DateTimeOffset? endDate,CancellationToken ct)=>await QueryCoreAsync(new StorageHistoryQuery(page,limit,startDate,endDate,null,null,null,null,false),productId,ct);
    public async Task<StorageHistoryFilterOptions> GetFilterOptionsAsync(CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);List<string> users=await DistinctAsync(c,"userName",ct);List<string> orders=await DistinctAsync(c,"orderName",ct);return new StorageHistoryFilterOptions(true,users,orders);}
    public async Task<long> UpdateOrderNameAsync(string orderId,string newOrderName,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);await using SqlCommand q=new("UPDATE dbo.StockOperations SET DetailsJson=JSON_MODIFY(DetailsJson,'$.orderName',@name) WHERE SourceReference=@id;",c);q.Parameters.AddWithValue("@name",newOrderName);q.Parameters.AddWithValue("@id",orderId);return await q.ExecuteNonQueryAsync(ct);}
    private async Task<StorageHistoryPage> QueryCoreAsync(StorageHistoryQuery x,string? product,CancellationToken ct){await using SqlConnection c=factory.Create();await c.OpenAsync(ct);List<string> f=[];await using SqlCommand count=new(){Connection=c};Filters(f,count,x,product);count.CommandText=$"SELECT COUNT(*) FROM dbo.StockMovementLines l JOIN dbo.StockOperations o ON o.StockOperationId=l.StockOperationId{Where(f)};";long total=Convert.ToInt64(await count.ExecuteScalarAsync(ct),CultureInfo.InvariantCulture);int take=x.ExportAll?Math.Min(10000,(int)Math.Min(total,10000)):x.Limit;int skip=x.ExportAll?0:checked((x.Page-1)*x.Limit);await using SqlCommand q=new(){Connection=c};Filters(f,q,x,product);q.CommandText=$"SELECT l.PublicId,l.SourceProductId,l.Quantity,o.DetailsJson,o.OccurredAtUtc FROM dbo.StockMovementLines l JOIN dbo.StockOperations o ON o.StockOperationId=l.StockOperationId{Where(f)} ORDER BY o.OccurredAtUtc DESC OFFSET @skip ROWS FETCH NEXT @take ROWS ONLY;";q.Parameters.AddWithValue("@skip",skip);q.Parameters.AddWithValue("@take",take);List<StorageHistoryEntry> values=[];await using SqlDataReader r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct)){using JsonDocument d=JsonDocument.Parse(r.IsDBNull(3)?"{}":r.GetString(3));JsonElement root=d.RootElement;DateTimeOffset when=r.IsDBNull(4)?DateTimeOffset.MinValue:new DateTimeOffset(r.GetDateTime(4),TimeSpan.Zero);values.Add(new StorageHistoryEntry(r.GetString(0),r.IsDBNull(1)?null:r.GetString(1),Text(root,"productName"),r.IsDBNull(2)?0:(double)r.GetDecimal(2),Text(root,"userName"),Text(root,"orderId"),Text(root,"orderName"),Text(root,"note"),Bool(root,"isAIScan"),Text(root,"source"),when,when));}long limit=x.ExportAll?Math.Min(total,10000):x.Limit;int pages=x.ExportAll?(total>0?1:0):(int)Math.Ceiling(total/(double)x.Limit);return new StorageHistoryPage(true,x.Page,limit,total,pages,values);}
    private static void Filters(List<string> f,SqlCommand q,StorageHistoryQuery x,string? product){if(product is not null){f.Add("l.SourceProductId=@product");q.Parameters.AddWithValue("@product",product);}if(x.StartDate.HasValue){f.Add("o.OccurredAtUtc>=@start");q.Parameters.AddWithValue("@start",x.StartDate.Value.UtcDateTime);}if(x.EndDate.HasValue){f.Add("o.OccurredAtUtc<=@end");q.Parameters.AddWithValue("@end",x.EndDate.Value.UtcDateTime);}if(!string.IsNullOrWhiteSpace(x.OrderName)){f.Add("o.DetailsJson LIKE @order");q.Parameters.AddWithValue("@order","%"+x.OrderName+"%");}if(!string.IsNullOrWhiteSpace(x.UserName)){f.Add("o.DetailsJson LIKE @user");q.Parameters.AddWithValue("@user","%"+x.UserName+"%");}if(x.Direction=="import")f.Add("l.Quantity>0");if(x.Direction=="export")f.Add("l.Quantity<0");if(!string.IsNullOrWhiteSpace(x.NoteType)) {f.Add("o.DetailsJson LIKE @note");q.Parameters.AddWithValue("@note","%"+x.NoteType+"%");}}
    private static async Task<List<string>> DistinctAsync(SqlConnection c,string property,CancellationToken ct){await using SqlCommand q=new($"SELECT DISTINCT JSON_VALUE(DetailsJson,'$.{property}') FROM dbo.StockOperations WHERE JSON_VALUE(DetailsJson,'$.{property}') IS NOT NULL AND JSON_VALUE(DetailsJson,'$.{property}')<>N'' ORDER BY JSON_VALUE(DetailsJson,'$.{property}');",c);List<string> result=[];await using SqlDataReader r=await q.ExecuteReaderAsync(ct);while(await r.ReadAsync(ct))result.Add(r.GetString(0));return result;}
    private static string Where(List<string> f)=>f.Count==0?string.Empty:" WHERE "+string.Join(" AND ",f);private static string? Text(JsonElement x,string p)=>x.TryGetProperty(p,out JsonElement y)&&y.ValueKind==JsonValueKind.String?y.GetString():null;private static bool Bool(JsonElement x,string p)=>x.TryGetProperty(p,out JsonElement y)&&y.ValueKind==JsonValueKind.True;
}
