SET NOCOUNT ON; SET XACT_ABORT OFF;
IF DB_NAME() <> N'TTSmart_Company_V1_Test' THROW 59640,N'Chi chay tren dung Company v1 test.',1;
BEGIN TRANSACTION;
DECLARE @brand uniqueidentifier=NEWID(),@catA uniqueidentifier=NEWID(),@catB uniqueidentifier=NEWID(),@unit uniqueidentifier=NEWID(),@product uniqueidentifier=NEWID(),@variant uniqueidentifier=NEWID(),@file uniqueidentifier=NEWID(),@log uniqueidentifier=NEWID(),@run uniqueidentifier=NEWID();
INSERT dbo.Brands(BrandId,PublicId,Name,NormalizedName,Version) VALUES(@brand,'000000000000000000000001',N'Nhan hieu',N'NHAN HIEU',0);
INSERT dbo.Categories(CategoryId,PublicId,Name,NormalizedName,Version) VALUES(@catA,'000000000000000000000002',N'Nhom A',N'NHOM A',0),(@catB,'000000000000000000000003',N'Nhom B',N'NHOM B',0);
INSERT dbo.Units(UnitId,PublicId,Name,NormalizedName,Symbol,Version) VALUES(@unit,'000000000000000000000004',N'Cai',N'CAI',N'cai',0);
INSERT dbo.Products(ProductId,PublicId,BrandId,Code,NormalizedCode,Name,Version) VALUES(@product,'000000000000000000000005',@brand,N'SP-01',N'SP-01',N'San pham',0);
INSERT dbo.ProductVariants(ProductVariantId,PublicId,ProductId,UnitId,Sku,NormalizedSku,Barcode,NormalizedBarcode,Version) VALUES(@variant,'000000000000000000000006',@product,@unit,N'SKU-01',N'SKU-01',N'893000000001',N'893000000001',0);
INSERT dbo.ProductCodes(ProductCodeId,ProductVariantId,CodeType,Code,NormalizedCode,Version) VALUES(NEWID(),@variant,N'SKU',N'SKU-01',N'SKU-01',0);
INSERT dbo.ProductCategoryAssignments(ProductCategoryAssignmentId,ProductId,CategoryId) VALUES(NEWID(),@product,@catA),(NEWID(),@product,@catB);
IF (SELECT COUNT(*) FROM dbo.ProductCategoryAssignments WHERE ProductId=@product)<>2 THROW 59641,N'Product phai ho tro nhieu Category.',1;
IF (SELECT Version FROM dbo.Products WHERE ProductId=@product)<>0 THROW 59642,N'Version 0 khong hop le.',1;
BEGIN TRY INSERT dbo.Products(ProductId,PublicId,Name) VALUES(NEWID(),'ABCDEFABCDEFABCDEFABCDEF',N'Sai'); THROW 59643,N'PublicId chu hoa khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()=59643 THROW; END CATCH;
BEGIN TRY INSERT dbo.Products(ProductId,PublicId,Code,NormalizedCode,Name) VALUES(NEWID(),'000000000000000000000007',N'SP-01',N'SP-01',N'Trung'); THROW 59644,N'Ma Product normalized trung khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>2601 AND ERROR_NUMBER()<>2627 THROW; END CATCH;
BEGIN TRY INSERT dbo.ProductVariants(ProductVariantId,PublicId,ProductId,NormalizedSku,Version) VALUES(NEWID(),'000000000000000000000008',@product,N'SKU-MISMATCH',0); THROW 59645,N'SKU khong dong bo khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>547 THROW; END CATCH;
BEGIN TRY INSERT dbo.ProductVariants(ProductVariantId,PublicId,ProductId,Sku,NormalizedSku,Version) VALUES(NEWID(),'000000000000000000000009',@product,N'SKU-02',N'SKU-01',0); THROW 59646,N'SKU normalized trung khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>2601 AND ERROR_NUMBER()<>2627 THROW; END CATCH;
BEGIN TRY INSERT dbo.ProductVariants(ProductVariantId,PublicId,ProductId,Barcode,NormalizedBarcode,Version) VALUES(NEWID(),'000000000000000000000010',@product,N'893000000001',N'893000000001',0); THROW 59647,N'Barcode normalized trung khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>2601 AND ERROR_NUMBER()<>2627 THROW; END CATCH;
BEGIN TRY INSERT dbo.ProductCodes(ProductCodeId,ProductVariantId,CodeType,Code,NormalizedCode,Version) VALUES(NEWID(),@variant,N'SKU',N'Khong dong bo',N'',0); THROW 59648,N'ProductCode normalized rong khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>547 THROW; END CATCH;
INSERT dbo.Files(FileId,PublicId,StorageKey,ContentSha256,MimeType,Extension,SizeBytes,Version) VALUES(@file,'000000000000000000000011',N'catalog/sp-01/a.pdf',REPLICATE('A',64),N'application/pdf',N'.pdf',10,0);
INSERT dbo.ProductFiles(ProductFileId,ProductId,FileId,UsageType) VALUES(NEWID(),@product,@file,N'PrimaryImage');
BEGIN TRY INSERT dbo.ProductFiles(ProductFileId,ProductId,ProductVariantId,FileId,UsageType) VALUES(NEWID(),@product,@variant,@file,N'Image'); THROW 59649,N'ProductFiles dong thoi hai owner khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>547 THROW; END CATCH;
BEGIN TRY INSERT dbo.ProductFiles(ProductFileId,FileId,UsageType) VALUES(NEWID(),@file,N'Image'); THROW 59650,N'ProductFiles khong owner khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>547 THROW; END CATCH;
DECLARE @badPath nvarchar(600); DECLARE paths CURSOR LOCAL FAST_FORWARD FOR SELECT Value FROM (VALUES(N'../a.pdf'),(N'a/../b.pdf'),(N'/absolute.pdf'),(N'a\\b.pdf'),(N'a//b.pdf'),(N'a/b.'))V(Value);
OPEN paths; FETCH NEXT FROM paths INTO @badPath; WHILE @@FETCH_STATUS=0 BEGIN BEGIN TRY INSERT dbo.Files(FileId,PublicId,StorageKey,ContentSha256,MimeType,Extension,SizeBytes,Version) VALUES(NEWID(),LOWER(LEFT(REPLACE(CONVERT(nvarchar(36),NEWID()),N'-',N''),24)),@badPath,REPLICATE('B',64),N'application/pdf',N'.pdf',1,0); THROW 59651,N'Storage key traversal khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>547 THROW; END CATCH; FETCH NEXT FROM paths INTO @badPath; END; CLOSE paths; DEALLOCATE paths;
INSERT dbo.CompanySettings(CompanySettingId,SettingKey,SettingValue,ValueType,Version) VALUES(NEWID(),N'AllowBranchCreateProduct',N'true',N'Boolean',0),(NEWID(),N'DefaultCurrency',N'VND',N'Currency',0);
BEGIN TRY INSERT dbo.CompanySettings(CompanySettingId,SettingKey,SettingValue,ValueType,Version) VALUES(NEWID(),N'Password',N'not-secret',N'String',0); THROW 59652,N'Setting key ngoai allowlist khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>547 THROW; END CATCH;
BEGIN TRY INSERT dbo.CompanySettings(CompanySettingId,SettingKey,SettingValue,ValueType,Version) VALUES(NEWID(),N'AllowBranchEditProduct',N'yes',N'Boolean',0); THROW 59653,N'Setting boolean sai khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>547 THROW; END CATCH;
INSERT dbo.ActivityLogs(ActivityLogId,ActorUserId,ActorType,CompanyId,ActionCode,ResourceType,ResourceId,SafeDetail) VALUES(@log,NEWID(),N'User',(SELECT CompanyId FROM dbo.DatabaseInfo WHERE SingletonKey=1),N'product.master.create',N'Product',@product,N'Nhanh audit da redact');
INSERT dbo.ActivityLogDetails(ActivityLogDetailId,ActivityLogId,DetailType,RedactedJson) VALUES(NEWID(),@log,N'After',N'{"name":"San pham"}');
BEGIN TRY INSERT dbo.ActivityLogs(ActivityLogId,ActorType,CompanyId,ActionCode,ResourceType,SafeDetail) VALUES(NEWID(),N'System',(SELECT CompanyId FROM dbo.DatabaseInfo WHERE SingletonKey=1),N'x',N'x',N'password=abc'); THROW 59655,N'Noi dung audit chua redact khong bi chan.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>547 THROW; END CATCH;
INSERT dbo.MigrationRuns(MigrationRunId,SourceSystem,Status,StartedAtUtc,SourceManifestSha256) VALUES(@run,N'Mongo',N'Completed',SYSUTCDATETIME(),REPLICATE('C',64));
INSERT dbo.MigrationMappings(MigrationMappingId,MigrationRunId,SourceSystem,SourceCollection,SourceKey,SourceKeyType,SourcePath,PreservationStatus,MappingFingerprint,TargetTable,TargetId) VALUES(NEWID(),@run,N'Mongo',N'products',N'aaaaaaaaaaaaaaaaaaaaaaaa',N'ObjectId',N'variants[0]',N'Mapped',REPLICATE('D',64),N'Products',@product);
INSERT dbo.LegacyRecords(LegacyRecordId,MigrationRunId,SourceDatabase,SourceCollection,SourceKey,SourceFingerprint,CanonicalExtendedJson,ContentSha256,PreservationStatus) VALUES(NEWID(),@run,N'ecom',N'unknown',N'x',REPLICATE('E',64),N'{"redacted":true}',REPLICATE('F',64),N'Archived');
ROLLBACK;
BEGIN TRANSACTION;
DECLARE @appendLog uniqueidentifier=NEWID(),@appendDetail uniqueidentifier=NEWID();
INSERT dbo.ActivityLogs(ActivityLogId,ActorType,CompanyId,ActionCode,ResourceType,SafeDetail) VALUES(@appendLog,N'System',(SELECT CompanyId FROM dbo.DatabaseInfo WHERE SingletonKey=1),N'test.append',N'Audit',N'redacted');
INSERT dbo.ActivityLogDetails(ActivityLogDetailId,ActivityLogId,DetailType,RedactedJson) VALUES(@appendDetail,@appendLog,N'After',N'{"safe":true}');
BEGIN TRY UPDATE dbo.ActivityLogs SET SafeDetail=N'sua' WHERE ActivityLogId=@appendLog; THROW 59654,N'ActivityLog khong append-only.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>59614 THROW; END CATCH;
IF XACT_STATE()<>0 ROLLBACK;
BEGIN TRANSACTION;
INSERT dbo.ActivityLogs(ActivityLogId,ActorType,CompanyId,ActionCode,ResourceType,SafeDetail) VALUES(@appendLog,N'System',(SELECT CompanyId FROM dbo.DatabaseInfo WHERE SingletonKey=1),N'test.append.detail',N'Audit',N'redacted');
INSERT dbo.ActivityLogDetails(ActivityLogDetailId,ActivityLogId,DetailType,RedactedJson) VALUES(@appendDetail,@appendLog,N'After',N'{"safe":true}');
BEGIN TRY UPDATE dbo.ActivityLogDetails SET RedactedJson=N'{"safe":false}' WHERE ActivityLogDetailId=@appendDetail; THROW 59656,N'ActivityLogDetails khong append-only.',1; END TRY BEGIN CATCH IF ERROR_NUMBER()<>59615 THROW; END CATCH;
IF XACT_STATE()<>0 ROLLBACK;
SELECT N'Company constraint tests passed' AS Result;
GO
